wiremock/wiremock

src/main/java/com/github/tomakehurst/wiremock/common/JettySettings.java, src/main/java/com/github/tomakehurst/wiremock/core/Options.java, src/main/java/com/github/tomakehurst/wiremock/core/WireMockConfiguration.java, src/main/java/com/github/tomakehurst/wiremock/jetty6/Jetty6HttpServer.java, src/main/java/com/github/tomakehurst/wiremock/standalone/CommandLineOptions.java, src/test/java/com/github/tomakehurst/wiremock/standalone/CommandLineOptionsTest.java
Two options we override when using wiremock for load tests
=> Jetty options: acceptors and accept queue size

build.gradle, gradle/wrapper/gradle-wrapper.properties, src/main/java/com/github/tomakehurst/wiremock/client/HttpAdminClient.java, src/main/java/com/github/tomakehurst/wiremock/client/WireMock.java, src/main/java/com/github/tomakehurst/wiremock/core/Admin.java, src/main/java/com/github/tomakehurst/wiremock/core/Container.java, src/main/java/com/github/tomakehurst/wiremock/core/Options.java, src/main/java/com/github/tomakehurst/wiremock/core/WireMockApp.java, src/main/java/com/github/tomakehurst/wiremock/core/WireMockConfiguration.java, src/main/java/com/github/tomakehurst/wiremock/junit/WireMockRule.java, src/main/java/com/github/tomakehurst/wiremock/servlet/NotImplementedContainer.java, src/main/java/com/github/tomakehurst/wiremock/standalone/WireMockServerRunner.java, src/test/java/com/github/tomakehurst/wiremock/AcceptanceTestBase.java, src/test/java/com/github/tomakehurst/wiremock/HttpsAcceptanceTest.java, src/test/java/com/github/tomakehurst/wiremock/MappingsLoaderAcceptanceTest.java, src/test/java/com/github/tomakehurst/wiremock/ProxyAcceptanceTest.java, src/test/java/com/github/tomakehurst/wiremock/RequestDelayAcceptanceTest.java, src/test/java/com/github/tomakehurst/wiremock/StandaloneAcceptanceTest.java, src/test/java/com/github/tomakehurst/wiremock/VerificationAcceptanceTest.java, src/test/java/com/github/tomakehurst/wiremock/WireMockServerTests.java, src/test/java/com/github/tomakehurst/wiremock/client/WireMockClientAcceptanceTest.java, src/test/java/com/github/tomakehurst/wiremock/testsupport/Network.java, src/test/java/com/github/tomakehurst/wiremock/testsupport/WireMockTestClient.java
Patch to use dynamically allocated ports during test run rather than using the defaults (8080/8443).
=> Dynamic port allocation during tests

src/main/java/com/github/tomakehurst/wiremock/http/ProxyResponseRenderer.java, src/main/java/com/github/tomakehurst/wiremock/http/Request.java, src/main/java/com/github/tomakehurst/wiremock/jetty6/Jetty6HandlerDispatchingServlet.java, src/main/java/com/github/tomakehurst/wiremock/jetty6/Jetty6HttpServletRequestAdapter.java, src/main/java/com/github/tomakehurst/wiremock/verification/LoggedRequest.java, src/test/java/com/github/tomakehurst/wiremock/ProxyAcceptanceTest.java, src/test/java/com/github/tomakehurst/wiremock/testsupport/MockRequestBuilder.java
When proxying binary data, for instance Spring Remoting, byte[] to/from String conversion can corrupt data. This PR introduces getBody() method on the Request class and stores the raw bytes instead of bytes converted to String.
Also I found that writeAndTranslateExceptions does not flush/close the ServletOutputStream, so that was added.
=> Fix binary data corruption when proxying requests

docs/source/running-standalone.rst, src/main/java/com/github/tomakehurst/wiremock/common/JettySettings.java, src/main/java/com/github/tomakehurst/wiremock/core/WireMockConfiguration.java, src/main/java/com/github/tomakehurst/wiremock/jetty6/Jetty6HttpServer.java, src/main/java/com/github/tomakehurst/wiremock/standalone/CommandLineOptions.java, src/test/java/com/github/tomakehurst/wiremock/StandaloneAcceptanceTest.java, src/test/java/com/github/tomakehurst/wiremock/common/JettySettingsTest.java, src/test/java/com/github/tomakehurst/wiremock/standalone/CommandLineOptionsTest.java
My apps have very large Headers which were overflowing Jetty's
Request Header Buffer, this resulted in response: 413 FULL head
This patch adds the ability to specify a Jetty Header Buffer
Size as a CLI flag when starting standalone Wiremock.
To recreate the problem do any GET with a single header larger
than 9k or so.  I added an acceptance test that demonstrates the
problem.
Also added console output confirmation when Jetty related command
line flags are specified (there are 3 now total). They previously
weren't output even when applied which leads to confusion.
=> CLI flag to set Jetty's request header buffer size

src/main/java/com/github/tomakehurst/wiremock/http/BasicResponseRenderer.java, src/main/java/com/github/tomakehurst/wiremock/http/HttpHeaders.java, src/test/java/com/github/tomakehurst/wiremock/http/HttpHeadersTest.java, src/test/java/com/github/tomakehurst/wiremock/stubbing/AdminRequestHandlerTest.java
Allows JavaScript clients to stage, reset, etc. without getting
Cross Site Scripting Errors.
See: http://en.wikipedia.org/wiki/Cross-origin_resource_sharing
=> Add CORS header to Admin requests

src/main/java/com/github/tomakehurst/wiremock/http/StubResponseRenderer.java, src/main/java/com/github/tomakehurst/wiremock/jetty6/Jetty6HandlerDispatchingServlet.java, src/test/java/com/github/tomakehurst/wiremock/ResponseDelayAcceptanceTest.java
Hi Tom, 
when a fixed response delay is configured and Jetty shuts down while the Thread is sleeping, a RuntimeException is thrown. This happens in every unit test where the test finishes execution before the fixed delay is over. Although this behaviour is ok, it clutters the log with stacktraces. 
My suggestion provides a graceful shutdown without throwing exceptions as well as a basic acceptance test for configuring response delays.
=> Graceful shutdown when Jetty is stopped during a fixed response delay sleep

src/main/java/com/github/tomakehurst/wiremock/http/ProxyResponseRenderer.java, src/main/java/com/github/tomakehurst/wiremock/standalone/CommandLineOptions.java, src/test/java/com/github/tomakehurst/wiremock/ProxyAcceptanceTest.java, src/test/java/com/github/tomakehurst/wiremock/standalone/CommandLineOptionsTest.java
According to the HTTP/1.1 standard, the "host" header should include trailing port information. If left out, it implies the default port for the service requested (http://www.w3.org/Protocols/rfc2616/rfc2616-sec14.html#sec14.23).
The changes in this pull request make WireMock adhere to this by always including trailing port information in the "host" header when proxying.
=> Include trailing port information in host header when proxying.

src/main/java/com/github/tomakehurst/wiremock/matching/RequestPattern.java, src/test/java/com/github/tomakehurst/wiremock/VerificationAcceptanceTest.java
Hi Tom,
Similar issue to https://github.com/tomakehurst/wiremock/pull/233 but in the context of verifying. (That PR was not merged but fixed in 026ff48).
Story: 
When the RequestPatternBuilder used for verifying was configured with an expected query parameter that is absent from the request an NPE is thrown. The verification fails as expected but with a strange reason: "com.github.tomakehurst.wiremock.client.VerificationException: Expected status 200 for http://localhost:8080/management/wiremock/__admin/requests/count but was 500".
The PR provides a passing test that shows the NPE in the first commit and a suggested solution in the second commit.
=> Fixes NPE when verifying an expected query parameter that is absent from the request

docs/source/stubbing.rst, src/main/java/com/github/tomakehurst/wiremock/client/UrlMatchingStrategy.java, src/main/java/com/github/tomakehurst/wiremock/client/WireMock.java, src/main/java/com/github/tomakehurst/wiremock/matching/RequestPattern.java, src/test/java/com/github/tomakehurst/wiremock/StubbingAcceptanceTest.java, src/test/java/com/github/tomakehurst/wiremock/VerificationAcceptanceTest.java, src/test/java/com/github/tomakehurst/wiremock/stubbing/RequestPatternTest.java
Adds a URL path matching strategy so regular expression matches on the path are possible in conjunction with query parameters to fix Issue #288.
=> Issue #288 Adds urlPathPattern matching strategy

src/main/java/com/github/tomakehurst/wiremock/common/Json.java, src/main/java/com/github/tomakehurst/wiremock/http/ResponseDefinition.java, src/test/java/com/github/tomakehurst/wiremock/MappingsAcceptanceTest.java, src/test/resources/mappings/testjsonmapping.json
Sometimes, when writing mappings as JSON, you want to mock a JSON response body. Having to escape the JSON inside the JSON can be a bit obnoxious, so this patch lets you specify a JSON object instead.
=> allow specifying response body as JSON

src/main/java/com/github/tomakehurst/wiremock/common/Json.java, src/test/java/com/github/tomakehurst/wiremock/stubbing/JsonTest.java
This PR allows you to use single quotes so that you don't have to escape double quotes (e.g. for JSON response body)
=> allow using single quotes for quoting Strings in JSON files

src/main/java/com/github/tomakehurst/wiremock/client/WireMock.java
Changed the WireMock class to use a thread local variable instead of a static variable.
=> WireMock to support parallel unit testing

src/main/java/com/github/tomakehurst/wiremock/client/HttpAdminClient.java
**With the following change, WireMock 2.0-beta successfully runs on Android**.
I was able to successfully create an ActivityInstrumentationTestCase2 using the @RunWith(AndroidJUnit4.class) class level annotation and the following WireMockRule:
```java
@Rule
public WireMockRule wireMockRule = new WireMockRule();
```
I did a lot of combinations of dependencies as I tried to figure out how to make this work, but when I simplified it down, the modification to make this work on android was VERY simple.  Thanks @tomakehurst for the great work.  
**How**
The only thing that wasn't supported was the StringEntity constructor that was being used in HttpAdminClient.  I reverted back to a constructor that was available on the 4.3.5.1 version of Android version of the Apache HttpClient and then …
=> WireMock 2.0-beta Android Support

docs/source/simulating-faults.rst, src/main/java/com/github/tomakehurst/wiremock/client/ResponseDefinitionBuilder.java, src/main/java/com/github/tomakehurst/wiremock/client/WireMock.java, src/main/java/com/github/tomakehurst/wiremock/global/GlobalSettings.java, src/main/java/com/github/tomakehurst/wiremock/http/DelayDistribution.java, src/main/java/com/github/tomakehurst/wiremock/http/LogNormal.java, src/main/java/com/github/tomakehurst/wiremock/http/ResponseDefinition.java, src/main/java/com/github/tomakehurst/wiremock/http/StubResponseRenderer.java, src/main/java/com/github/tomakehurst/wiremock/http/UniformDistribution.java, src/test/java/com/github/tomakehurst/wiremock/GlobalSettingsAcceptanceTest.java, src/test/java/com/github/tomakehurst/wiremock/StubbingAcceptanceTest.java, src/test/java/com/github/tomakehurst/wiremock/http/LogNormalTest.java, src/test/java/com/github/tomakehurst/wiremock/http/UniformDistributionTest.java, src/test/java/com/github/tomakehurst/wiremock/stubbing/ResponseDefinitionTest.java
This expands on the existing fixed delay functionality by providing a
more general feature to draw values from a random distribution.
This allows teams to simulate long tails in delays from downstream
systems, a common scenario in load and resiliency tests.
I've provided a log normal implementation out of the box, which gives a
pretty good long tail distribution for modeling delays. It also has the
nice benefit of being able to specify the 50th percentile which is a
commonly tracked metric.
Here is an example priming using the log normal delay:
```json
{
"request": {
"url": "/some/thing"
},
"response": {
"status": 200,
"body": "Hello world!",
"headers": {
"Content-Type": "text/plain"
},
"delayDistribution": {
"type": "lognormal",
"median": 80,
"sigma": 0.4
}
}
}
```
This …
=> Support randomly distributed delays for responses

build.gradle, src/main/java/com/github/tomakehurst/wiremock/standalone/CommandLineOptions.java, src/test/java/com/github/tomakehurst/wiremock/standalone/CommandLineOptionsTest.java
Prevent ClassCastException when adding custom RequestMatcher or
ResponseDefinitionTransformer via command line option.
=> Fix ClassCastException in CommandLineOptions.extensionOfType

src/main/java/com/github/tomakehurst/wiremock/http/Request.java, src/main/java/com/github/tomakehurst/wiremock/jetty9/JettyHttpServletRequestAdapter.java, src/main/java/com/github/tomakehurst/wiremock/verification/LoggedRequest.java, src/test/java/com/github/tomakehurst/wiremock/testsupport/MockRequestBuilder.java, src/test/java/com/github/tomakehurst/wiremock/verification/LoggedRequestTest.java
In order to pass back a binary body such as a zip or jpeg exactly as received in the original request for verification, we need a new `bodyAsBase64` element in the `LoggedRequest` JSON. The original string element `body` corrupts the stored byte array so this was needed as there was no way to retrieve it otherwise.
So calling the usual `http://<host>:<port>/__admin/requests/find` will return the same JSON as before but now it will also have something like this example...
`"bodyAsBase64": "TXkgdGV4dAo=",`
... at the same level as `"body": "My text"` element.
For the moment, this is only in the REST API, not the Java API. We tried the Java API after finding that the REST API didn't return binary but that has the same issue.
=> Added bodyAsBase64 element to LoggedRequest JSON in requests find output

src/main/java/com/github/tomakehurst/wiremock/http/HttpClientFactory.java
Calling useSystemProperties on the HttpClientBuilder allows the user to configure HttpClient's lower-level workings by setting system properties.
Low-risk alternative resolution to https://github.com/tomakehurst/wiremock/pull/381.
=> Made HttpClient respect system properties

build.gradle
**Fix**
This pull request fixes the issue described below by explicitly setting the file encoding to UTF-8 for the compile test task of build.gradle.
**Issue**
Running `gradlew.bat build` on Windows (8.1) yields,
```
[...]
:compileTestJava
warning: [options] bootstrap class path not set in conjunction with -source 1.7
E:\Git\wiremock\src\test\java\com\github\tomakehurst\wiremock\verification\LoggedRequestTest.java:47: error: unmappable character for encoding Cp1252
public static final String REQUEST_BODY = "some text Õ¢óÕú░Õ¡ùÕ¢óÞ?▓Õ¡ù";
^
Note: Some input files use or override a deprecated API.
Note: Recompile with -Xlint:deprecation for details.
Note: Some input files use unchecked or unsafe operations.
Note: Recompile with -Xlint:unchecked for details.
1 warning
:processTestResources …
```
=> Specify file encoding for gradle compile test task

src/main/java/com/github/tomakehurst/wiremock/common/Gzip.java, src/main/java/com/github/tomakehurst/wiremock/jetty9/JettyHttpServletRequestAdapter.java, src/test/java/com/github/tomakehurst/wiremock/GzipAcceptanceTest.java
Fixes #404 
My IDE's done a bit of tidying up in JettyHttpServletRequestAdapter, I can take that out if you'd prefer a cleaner diff.
Also we can maybe just rely on the Content-Encoding header rather than looking at the magic bytes. (That would also mean we can do it without turning the response back and forth between a stream and an array), let me know if you'd prefer it that way.
=> Accept gzipped request bodies

src/main/java/com/github/tomakehurst/wiremock/jetty9/JettyHttpServer.java, src/test/java/com/github/tomakehurst/wiremock/DateHeaderAcceptanceTest.java
In WireMock v1 no Date header is returned unless explicitly stubbed.
This PR returns WireMock v2 to that behaviour; previously it generated a Date header field regardless of stubbing, meaning that if you stubbed the Date header field you got two, with the stubbed one later in the header field order so ignored by most clients.
=> Reverts to WireMock 1 behaviour - Date header only returned if stubbed

src/test/java/com/github/tomakehurst/wiremock/StubbingAcceptanceTest.java, src/test/java/com/github/tomakehurst/wiremock/VerificationAcceptanceTest.java
matchers: urlEqualTo, urlPathEqualTo, urlPathMatching
I wanted to fix #408 but it turned out that the issue is already fixed in 2.0-beta.
These are the refined tests which I think should be added as enhanced regression tests anyway.
=> refine stubbing and verification acceptance tests for some matchers

sample-war/src/main/webapp/WEB-INF/web.xml, sample-war/src/main/webappCustomMapping/WEB-INF/web.xml, sample-war/src/main/webappLimitedRequestJournal/WEB-INF/web.xml, src/main/java/com/github/tomakehurst/wiremock/jetty9/JettyFaultInjector.java, src/main/java/com/github/tomakehurst/wiremock/jetty9/JettyFaultInjectorFactory.java, src/main/java/com/github/tomakehurst/wiremock/jetty9/JettyHttpServer.java, src/main/java/com/github/tomakehurst/wiremock/servlet/FaultInjectorFactory.java, src/main/java/com/github/tomakehurst/wiremock/servlet/WireMockHandlerDispatchingServlet.java, src/main/java/com/github/tomakehurst/wiremock/servlet/WireMockHttpServletRequestAdapter.java
The servlet and request adapters have moved to the "servlet" package.
The only dependency they had on jetty was conditional anyway, so
the condition was also modified to not even require jetty on the
classpath.
See gh-407. Not a complete modularization yet, but splits up the
servlet-only stuff from the jetty server.
=> Isolate jetty dependencies into a single package

src/test/java/com/github/tomakehurst/wiremock/VerificationAcceptanceTest.java, src/test/java/com/github/tomakehurst/wiremock/verification/DiffTest.java
The pretty print library used appears to create system specific
new line characters. Now the non-ignored unit tests pass on
Windows.
I suppose an alternative to this approach could be to change the 
configuration of the library to always use unix line endings.
=> Unit test fixes for pretty print

src/main/java/com/github/tomakehurst/wiremock/common/HttpsSettings.java, src/main/java/com/github/tomakehurst/wiremock/core/WireMockConfiguration.java, src/main/java/com/github/tomakehurst/wiremock/jetty9/CustomizedSslContextFactory.java, src/main/java/com/github/tomakehurst/wiremock/jetty9/JettyHttpServer.java
PR contains:
- patch for Android support for HTTPS communication, which needs the Keystore to be 'BKS' type instead of 'JKS'.  
- The PR is intended to give users an additional option to send KeyStoreType and TrustStoreType as Wiremock configuration when starting the server. For example,
```
WireMockServer wireMockServer  = new WireMockServer(wireMockConfig().port(9988).httpsPort(9943).keyStoreType("BKS").keystorePath("path/to/keystore")
```
Please note that the acceptance test could not be created for this addition, because the normal JVM only supports JKS keystore type and the acceptance test fails if the test is executed on desktop.  I was trying to forcefully set the  JVM security to support BKS just for the test, but couldn't find how to. The JVM settings have to be set manually by …
=> Android https support for wiremock

src/main/java/com/github/tomakehurst/wiremock/common/SilentErrorHandler.java, src/main/java/com/github/tomakehurst/wiremock/matching/MatchesXPathPattern.java
adding silent error handler to DocumentBuilder to suppress Fatal Error Logging occurring on attempt to evaluate XPath on non XML string
=> adding silent error handler to DocumentBuilder to suppress Fatal Error Logging

src/main/resources/raml/wiremock-admin-api.raml
This is a suggested change to the RAML file to document the shutdown command. I am familiar with Swagger, but not RAML unfortunately, so this is untested guesswork! Happy to tweak, or feel free to use this as a base for more changes before merging.
=> Add the shutdown function to the docs (#545)

src/main/java/com/github/tomakehurst/wiremock/http/ContentTypeHeader.java, src/test/java/com/github/tomakehurst/wiremock/http/ContentTypeHeaderTest.java
NullPointer exception was generated when getting MimeTypePart from ContentTypeHeader as described in #643. This commit fixes this behavior and return null value instead.
=> #643 Prevent null pointer exception when getting MimeTypePart

docs-v2/_docs/response-templating.md, src/main/java/com/github/tomakehurst/wiremock/extension/responsetemplating/ResponseTemplateTransformer.java, src/test/java/com/github/tomakehurst/wiremock/extension/responsetemplating/ResponseTemplateTransformerTest.java
This extends the response templating extension to work with proxy URLs. This is very useful when
using the proxy/intercept setup with multiple API providers, especially when the
endpoints aren't known ahead of time. The browser proxy mode is perhaps better suited to this use
case, but it's not an option for HTTPS-only APIs due to the lack of SSL support.
Specific use case: I'm working with a large legacy codebase that has many API tests that I want to stub with Wiremock for performance reasons. I don't know all the API endpoints involved, but I do have the ability to tamper with the request before it's sent. The example I added to the docs is what I want to do: set a header named `X-WM-Proxy-Url` with the API endpoint and template it with `"proxyBaseUrl": …
=> Add response templating for proxyBaseUrl

build.gradle
When checking some projects with DependencyCheck, I discovered that wiremock has a vulnerable dependency:
```
One or more dependencies were identified with known vulnerabilities:
commons-collections4-4.0.jar (cpe:/a:apache:commons_collections:4.0, org.apache.commons:commons-collections4:4.0) : CVE-2015-6420
```
(See http://commons.apache.org/proper/commons-collections/release_4_1.html or https://issues.apache.org/jira/browse/COLLECTIONS-580 for more details.)
Turns out this is dependency is added via zjsonpatch, which has just released a new version which is no longer depending on the vulnerable verison of commons-collections4 (https://github.com/flipkart-incubator/zjsonpatch/releases/tag/0.3.0)
Due to #623 I haven't been able to build wiremock successfully, but I didn't see any worse …
=> Upgrade to latest version of zjsonpatch

build.gradle, src/main/java/com/github/tomakehurst/wiremock/client/HttpAdminClient.java, src/main/java/com/github/tomakehurst/wiremock/client/WireMock.java, src/main/java/com/github/tomakehurst/wiremock/http/HttpClientFactory.java, src/test/java/com/github/tomakehurst/wiremock/client/WireMockClientWithProxyAcceptanceTest.java
e.g.
WireMock instance = new WireMock("https", "wiremock.server.url", 443, null, "" "proxyhost", proxyport);
=> Added proxy settings to connect to remote wiremock server over a http proxy

build.gradle
When writing tests for extensions, the test classes in `com.github.tomakehurst.wiremock.matching` and `com.github.tomakehurst.wiremock.matching` are very helpful. Since it's not possible to include those as Maven Central dependencies, [I had to add wiremock as a Git submodule](https://github.com/MasonM/wiremock-snapshot/commit/d9e9f1c4a4abd1f1209e5788426cc0fc90c88dca) in my wiremock-snapshot extension so I could use them.
Another extension, wiremock-velocity-transformer, seems to have had the same issue and just did a [straight copy of the test sources](https://github.com/adamyork/wiremock-velocity-transformer/tree/master/src/test/java/com/github/tomakehurst/wiremock/testsupport).
=> Publish testJar to Maven Central

src/main/java/com/github/tomakehurst/wiremock/WireMockServer.java, src/main/java/com/github/tomakehurst/wiremock/client/HttpAdminClient.java, src/main/java/com/github/tomakehurst/wiremock/core/Admin.java, src/main/java/com/github/tomakehurst/wiremock/core/WireMockApp.java, src/test/java/com/github/tomakehurst/wiremock/WireMockServerTests.java, src/test/java/com/github/tomakehurst/wiremock/client/HttpAdminClientTest.java
For the new recording API endpoint, we'll want to be able to extract response bodies to a file and load stub mapping transformer extensions. This means having access to `Options.filesSource()` so it can write out the extracted bodies, and `Options.extensionsOfType()` for loading the transformer extensions.
I'm not sure if `WireMockServer.getOptions()` and `WireMockApp.getOptions()` are really worth testing, since they're simple getters. I wrote a test for former since there's already a test class for it.
(I'll reply to your comments in PR #674 tomorrow. Just wanted to get this out here)
=> Add getOptions() to Admin interface

src/main/java/com/github/tomakehurst/wiremock/common/UniqueFilenameGenerator.java, src/main/java/com/github/tomakehurst/wiremock/common/Urls.java, src/main/java/com/github/tomakehurst/wiremock/stubbing/StubMappingJsonRecorder.java, src/test/java/com/github/tomakehurst/wiremock/common/UniqueFilenameGeneratorTest.java, src/test/java/com/github/tomakehurst/wiremock/common/UrlsTest.java
This is split off from PR #674  to make it easier to review. I extracted some logic in `UniqueFilenameGenerator` for turning URL paths into a hyphen-delimited string over to a method in Urls, `urlToPathParts()`, and wrote tests for it. I also changed `UniqueFilenameGenerator` to accept a URL string instead of a Request so it can be used by the Snapshot API in PR #674.
=> Refactoring to extract URL path logic to a method

src/main/java/com/github/tomakehurst/wiremock/common/Strings.java, src/main/java/com/github/tomakehurst/wiremock/http/ContentTypeHeader.java, src/main/java/com/github/tomakehurst/wiremock/http/LoggedResponse.java, src/main/java/com/github/tomakehurst/wiremock/http/Response.java, src/test/java/com/github/tomakehurst/wiremock/RequestQueryAcceptanceTest.java, src/test/java/com/github/tomakehurst/wiremock/http/ContentTypeHeaderTest.java, src/test/java/com/github/tomakehurst/wiremock/verification/LoggedResponseTest.java
While working on the snapshot feature, I discovered that binary response bodies were getting corrupted. This is happening because the `LoggedResponse.from()` method sets the body by calling `Response.getBodyAsString()`, which encodes the body in the charset for the content type header (or UTF-8, if that's absent). Any invalid characters in the body get silently replaced with the default replacement character (U+FFFD for Unicode).
I fixed this by just copying what `LoggedRequest` is doing: instantiate the body using a Base64-encoded string and have a `getBodyAsString()` method that does necessary encoding.
I moved the `Response.encodingFromContentTypeHeaderOrUtf8()` method to `ContentTypeHeader.encodingOrUtf8()` so both `Response` and `LoggedResponse` could use it.
=> Fix binary body corruption for logged responses

docs-v2/_docs/record-playback.md
Since version 2 the name pattern of the standalone jar seems to have changed to e.g. "wiremock-standalone-2.6.0.jar"
=> Updated "record and replay" docs

docs-v2/_docs/running-standalone.md, docs-v2/_docs/stubbing.md
I added additional information about file serving, especially when using the standard JAR. 
I love this feature for its simplicity and think more people should be aware of it.
=> Add additional information about file serving to the documentation

docs-v2/_docs/extending-wiremock.md
Seems that that the documentation is behind.  My IDE had me override 'getName' instead of 'name'.  Hope this is correct.
=> Update docs to extending docs to new getName method

build.gradle, src/main/java/com/github/tomakehurst/wiremock/extension/responsetemplating/ResponseTemplateTransformer.java, src/main/java/com/github/tomakehurst/wiremock/extension/responsetemplating/helpers/HandlebarsHelper.java, src/main/java/com/github/tomakehurst/wiremock/extension/responsetemplating/helpers/HandlebarsJsonHelper.java, src/main/java/com/github/tomakehurst/wiremock/extension/responsetemplating/helpers/HandlebarsSoapHelper.java, src/main/java/com/github/tomakehurst/wiremock/extension/responsetemplating/helpers/HandlebarsXmlHelper.java, src/main/java/com/github/tomakehurst/wiremock/extension/responsetemplating/helpers/WiremockHelpers.java, src/test/java/com/github/tomakehurst/wiremock/extension/responsetemplating/helpers/HandlebarsHelperTestBase.java, src/test/java/com/github/tomakehurst/wiremock/extension/responsetemplating/helpers/HandlebarsJsonHelperTest.java, src/test/java/com/github/tomakehurst/wiremock/extension/responsetemplating/helpers/HandlebarsSoapHelperTest.java, src/test/java/com/github/tomakehurst/wiremock/extension/responsetemplating/helpers/HandlebarsXmlHelperTest.java
Hi,
as I promised in  #704 . Here the three helpers for xml, soap and json content. Xml and soap are plain old Java but Json via JsonPath uses a lib described below. I also added some tests. Here some other points:
1.  Feel free to rename the classes. I was not sure about the naming
2.  I was not sure about the handling of errors if xml/json or xPath/jsonPath are invalid. Currently it fails gracefully and shows an error message in the response. The intention was that it is easier to find the issue.
Best regards,
Christopher
-added com.jayway.jsonpath:json-path:2.2.0 to dependencies which allows the JsonPath implementation
=> added wiremock exclusive handlebars helpers:

build.gradle, src/main/java/com/github/tomakehurst/wiremock/common/ContentTypes.java, src/main/java/com/github/tomakehurst/wiremock/common/Strings.java, src/main/java/com/github/tomakehurst/wiremock/http/ContentTypeHeader.java, src/main/java/com/github/tomakehurst/wiremock/http/Response.java, src/main/java/com/github/tomakehurst/wiremock/servlet/WireMockHttpServletRequestAdapter.java, src/main/java/com/github/tomakehurst/wiremock/verification/LoggedRequest.java, src/test/java/com/github/tomakehurst/wiremock/MappingsAcceptanceTest.java, src/test/java/com/github/tomakehurst/wiremock/RequestQueryAcceptanceTest.java, src/test/java/com/github/tomakehurst/wiremock/testsupport/MappingJsonSamples.java, src/test/java/com/github/tomakehurst/wiremock/testsupport/WireMockTestClient.java
Wiremock was not considering the charset of the submitted data.  The clearest example of this was in the existing unit test requestBodyEncodingRemainsUtf8().  The test posts a body containing utf-8 data, but specifies a content type of ContentType.TEXT_PLAIN, which attaches a HTTP header of "Content-Type" : "text/plain; charset=ISO-8859-1" to the post.   So in this test, the body's charset does not match what is advertised in content-type header, yet the test passed because the request-handling methods ignored the charset value, assuming the submitted content would be utf-8.  
In these changes, I've modified the Wiremock code to use the charset of the submitted data, falling back to utf-8 if the charset is not specified.
=> obeying the charset specified in the content-type header

src/main/java/com/github/tomakehurst/wiremock/WireMockServer.java, src/test/java/com/github/tomakehurst/wiremock/WireMockServerTests.java
It's often required to build fully qualified URLs to the WireMock server when interacting with it. This PR adds a `WireMockServer.url` method that produces a fully qualified URL from a given path.
=> Add convenience WireMockServer.url builder method

src/main/java/com/github/tomakehurst/wiremock/core/WireMockConfiguration.java, src/main/java/com/github/tomakehurst/wiremock/jetty9/JettyHttpServer.java, src/test/java/com/github/tomakehurst/wiremock/core/WireMockConfigurationTest.java, src/test/java/com/github/tomakehurst/wiremock/jetty9/JettyHttpServerTest.java, src/test/java/ignored/Examples.java
This PR wires up the jetty stop timeout for use with embedded jetty. 
It adds jettyStopTimeout to WireMockConfiguration and changes JettyHttpServer.finalizeSetup() to not overwrite the timeout value on setup.
=> Wire up stop timeout for embedded Jetty server

src/main/java/com/github/tomakehurst/wiremock/client/VerificationException.java, src/main/java/com/github/tomakehurst/wiremock/junit/WireMockRule.java, src/test/java/com/github/tomakehurst/wiremock/junit/WireMockRuleFailOnUnmatchedRequestsTest.java
changes 'failOnUnmatchedStubs' to 'failOnUnmatchedRequests' like intended.
Fixes #676.
=> changes 'failOnUnmatchedStubs' to 'failOnUnmatchedRequests'

docs-v2/_docs/extending-wiremock.md
Just wanted to document the usage of a `RequestMatcherExtension` in verification.
https://stackoverflow.com/questions/46703213/wiremock-verify-headers-contains-many-values-via-custom-valuematcherstrategy/46726960#comment80478529_46726960
=> Document the usage of RequestMatcherExtension with WireMock.verify

src/main/java/com/github/tomakehurst/wiremock/client/ResponseDefinitionBuilder.java, src/test/java/com/github/tomakehurst/wiremock/client/ResponseDefinitionBuilderTest.java
This fixes issue #592. When `ResponseDefinitionBuilder.like()` was called with a ResponseDefinition that had transformer parameters, it just copied the reference. This means subsequent calls to `withTransformerParameter()` would modify the original object.
=> Issue #592- Fix ResponseDefinitionBuilder.like() to copy transformerParameters

src/main/java/com/github/tomakehurst/wiremock/matching/RequestPattern.java, src/main/java/com/github/tomakehurst/wiremock/matching/RequestPatternBuilder.java, src/test/java/com/github/tomakehurst/wiremock/matching/RequestPatternBuilderTest.java
Sometimes, when writing a StubMappingTransformer extension, you want to change a single field in the RequestPattern (e.g. the URL). This is difficult because RequestPattern is immutable and RequestPatternBuilder can't build off an existing object the way ResponseDefinitionBuilder can.
This adds two new methods to RequestPatternBuilder, like() and but(), that do the same thing as the corresponding methods in ResponseDefinitionBuilder.
=> Add RequestPatternBuilder.like() and but() methods

docs-v2/_docs/request-matching.md, src/main/java/com/github/tomakehurst/wiremock/matching/EqualToJsonPattern.java, src/main/java/com/github/tomakehurst/wiremock/matching/StringValuePatternJsonDeserializer.java, src/test/java/com/github/tomakehurst/wiremock/matching/EqualToJsonTest.java
This allows setting "equalToJson" to a raw JSON value when submitting a request matcher to the API, as requested in #763 . I updated the serialization code so it will write an unencoded string if the original was unencoded.
=> Allow equalToJson to accept unencoded JSON (issue #763)

src/main/java/com/github/tomakehurst/wiremock/common/Encoding.java
Better performing according to this: http://java-performance.info/base64-encoding-and-decoding-performance/
Been profiling stubs with base64 encoded JSON objects and base64->encoding/decoding is by far the hottest method.
=> Switched base64 encoding to native Java library

docs-v2/_docs/simulating-faults.md, src/main/java/com/github/tomakehurst/wiremock/client/ResponseDefinitionBuilder.java, src/main/java/com/github/tomakehurst/wiremock/http/ChunkedDribbleDelay.java, src/main/java/com/github/tomakehurst/wiremock/http/Response.java, src/main/java/com/github/tomakehurst/wiremock/http/ResponseDefinition.java, src/main/java/com/github/tomakehurst/wiremock/http/StubResponseRenderer.java, src/main/java/com/github/tomakehurst/wiremock/servlet/BodyChunker.java, src/main/java/com/github/tomakehurst/wiremock/servlet/WireMockHandlerDispatchingServlet.java, src/test/java/com/github/tomakehurst/wiremock/ResponseDribbleAcceptanceTest.java, src/test/java/com/github/tomakehurst/wiremock/StubbingAcceptanceTest.java, src/test/java/com/github/tomakehurst/wiremock/client/ResponseDefinitionBuilderTest.java, src/test/java/com/github/tomakehurst/wiremock/servlet/BodyChunkerTest.java, src/test/java/com/github/tomakehurst/wiremock/stubbing/ResponseDefinitionTest.java
Allow setting configurable delay after each byte WireMock is sending in the response body.
This resolves #472
Example:
```
stubFor(get(urlEqualTo("/delayedDribble")).willReturn(
.aResponse()
.withStatus(200)
.withBody(new byte[] {1, 2, 3})
.withByteDribbleDelay(10)));
```
Removed some spurious white spaces as a separate commit because they were inconsistent within the same class file (WireMockHandlerDispatchingServlet) we were working on.
=> Byte dribble delay support

docs-v2/_docs/extending-wiremock.md
maxLemgth -> maxLength
Note: I don't know why Github is showing me this as well in the diff:
```
-you can use the ```CollectingNetworkTrafficListener```.
+you can use the ```CollectingNetworkTrafficListener```.
```
But it doesn't show in rich-diff view & made sure they're the same sentences. Conclusion: Safe to ignore.
=> Fixed typo in _docs/extending-wiremock

src/main/java/com/github/tomakehurst/wiremock/extension/responsetemplating/ResponseTemplateTransformer.java, src/test/java/com/github/tomakehurst/wiremock/extension/responsetemplating/ResponseTemplateTransformerTest.java
So that e.g. escaping of single quotes can be disabled.
There are a few `Handlebars.with` methods that can be used to configure it. Rather than adding a parameter per one of those, it seemed less invasive to just expose the entire `Handlebars` object as a parameter.
=> Allow custom Handlebars instance to be used 

src/main/java/com/github/tomakehurst/wiremock/common/AbstractFileSource.java, src/test/java/com/github/tomakehurst/wiremock/common/SingleRootFileSourceTest.java
Sometimes you might want to provide the rootPath relative to the current directory, for example ../external/wiremock-files-root. I have made that possible now.
=> Relative rootPath in FileSource

src/main/java/com/github/tomakehurst/wiremock/client/VerificationException.java
If there were more  requests than expected, the error message is misleading:
Expected exactly 1 requests [...] but received only 2
=> Misleading error message

src/main/java/com/github/tomakehurst/wiremock/core/Options.java, src/main/java/com/github/tomakehurst/wiremock/core/WireMockConfiguration.java, src/main/java/com/github/tomakehurst/wiremock/http/ThreadPoolFactory.java, src/main/java/com/github/tomakehurst/wiremock/jetty9/JettyHttpServer.java, src/main/java/com/github/tomakehurst/wiremock/jetty9/QueuedThreadPoolFactory.java, src/main/java/com/github/tomakehurst/wiremock/servlet/WarConfiguration.java, src/main/java/com/github/tomakehurst/wiremock/standalone/CommandLineOptions.java, src/test/java/com/github/tomakehurst/wiremock/QueuedThreadPoolAcceptanceTest.java, src/test/java/com/github/tomakehurst/wiremock/core/WireMockConfigurationTest.java
Allow setting a ThreadPool for Jetty server.
Useful when needs to use a InstrumentedQueuedThreadPool.
=> Add ThreadPoolFactory to enable custom ThreadPool for Jetty.

src/main/java/com/github/tomakehurst/wiremock/http/ProxyResponseRenderer.java, src/test/java/com/github/tomakehurst/wiremock/ProxyAcceptanceTest.java
The original issue in #655 was a misunderstanding of how curl behaves.
=> Preserve trailing slashes if the original request had them

src/main/java/com/github/tomakehurst/wiremock/common/AbstractFileSource.java
Replace the usage of Path and Paths with File for backward compatibility issues with android API before 26. Connected to issue [#843](https://github.com/tomakehurst/wiremock/issues/843)
=> Replace the usage of Path and Paths with File 

src/main/java/com/github/tomakehurst/wiremock/common/Base64Encoder.java, src/main/java/com/github/tomakehurst/wiremock/common/DatatypeConverterBase64Encoder.java, src/main/java/com/github/tomakehurst/wiremock/common/Encoding.java, src/main/java/com/github/tomakehurst/wiremock/common/GuavaBase64Encoder.java, src/test/java/com/github/tomakehurst/wiremock/common/Base64EncoderTest.java
Resolves #840 
As discussed in the Issue this PR adds a runtime check if the `DatatypeConverter` class is available and otherwise falls back to the previous Guava implementation.
=> add runtime switch for base64 encoder

src/main/java/com/github/tomakehurst/wiremock/client/WireMock.java, src/test/java/com/github/tomakehurst/wiremock/MultithreadConfigurationInheritanceTest.java
After upgrading from 1.x to 2.x I saw an issue where tests that used a timeout were failing due to the configuration set in a before class being lost. This change moves the WireMock from a ThreadLocal to an InheritableThreadLocal so that configuration is preserved but can still be overriden by new threads.
=> Use a InheritableThreadLocal for WireMock 

docs-v2/_docs/running-standalone.md, src/main/java/com/github/tomakehurst/wiremock/standalone/CommandLineOptions.java, src/main/java/com/github/tomakehurst/wiremock/standalone/WireMockServerRunner.java, src/test/java/com/github/tomakehurst/wiremock/standalone/CommandLineOptionsTest.java
Fixes #898
Starting WireMock with `--port 0` will denote the correct port in the output
Also, to prevent further questions like mine, added some documentation of the possibility of running with `--port 0` at
* the [running standalone page](http://wiremock.org/docs/running-standalone/#command-line-options)
* and when running with `--help`.
Feedback always welcome. Wasn't sure about tabs vs spaces, current file contains both... lemme know what you prefer.
=> #898 Show the resulting port number instead of 0

src/main/java/com/github/tomakehurst/wiremock/common/StreamSource.java, src/main/java/com/github/tomakehurst/wiremock/common/StreamSources.java, src/main/java/com/github/tomakehurst/wiremock/http/Response.java, src/main/java/com/github/tomakehurst/wiremock/http/StubResponseRenderer.java, src/main/java/com/github/tomakehurst/wiremock/servlet/WireMockHandlerDispatchingServlet.java
Now with fewer whitespace changes.
A colleague and I have done some work to use streams when generating the response body.
The work we have done might not be a complete fix (there may be more work with regard to the journaling due to the way disabling journaling is implemented).
All the unit tests passed without modification. We didn't write more unit tests since what we were changing was an implementation detail (the behavior/api didn't change and all current tests passed).
=> Using streams for building responses.

build.gradle
On some cases it's not possible to record using HTTPS, because of BUG
in httpclient, see https://issues.apache.org/jira/browse/HTTPCLIENT-1836
=> Update httpclient to fix hostname verification

src/main/java/com/github/tomakehurst/wiremock/common/KeyStoreSettings.java, src/test/java/com/github/tomakehurst/wiremock/common/KeyStoreSettingsTest.java
Fix for #475 
Added a fallback in `KeyStoreSettings` to try loading the truststore from classpath if not found as file.
Added relevant test cases
=> SSL truststore tries to load from classpath

src/main/resources/raml/schemas/delay-distribution.schema.json, src/main/resources/raml/schemas/global-settings.schema.json, src/main/resources/raml/schemas/response-definition.schema.json, src/main/resources/raml/wiremock-admin-api.raml
Split off from PR #888 to make it easier to review. This adds an API schema for the `/__admin/settings` endpoint, which is required for OpenAPI 3 conversion to work, and splits off the delay distribution schema into a separate file, since it's now referenced by both the new schema and `response-definition.schema.json`.
=> Add API schema for /_admin/settings

src/main/resources/raml/schemas/scenario.schema.json, src/main/resources/raml/wiremock-admin-api.raml
Split off from PR #888 to make it easier to review. This makes a couple minor backwards-compatible fixes for OpenAPI 3.0 compatibility:
1. Remove the "id" properties in `scenario.schema.json`, which aren't present in any of the other schema files, and cause validation errors.
2. Define the baseUri to be "/__admin". Besides simplifying all the other URLs, this gets translated to the server object URL, which is required in OpenAPI 3.0:
https://github.com/OAI/OpenAPI-Specification/blob/master/versions/3.0.0.md#serverObject
=> Fixes for OpenAPI 3.0 compatibility

src/main/resources/raml/schemas/record-spec.schema.json, src/main/resources/raml/schemas/snapshot.schema.json, src/main/resources/raml/schemas/start-recording.schema.json, src/main/resources/raml/wiremock-admin-api.raml
Split off from PR #888 to make it easier to review. Both `/__admin/recordings/start` and `/__admin/recordings/snapshot` were using the same API spec (`record-spec.schema.json`), but they take different parameters. This changes `record-spec.schema.json` to only contain the common parameters, and adds separate schemas that extend it with the endpoint-specific parameters.
=> Add proper API specs for recordings API endpoints

src/main/resources/raml/schemas/logged-request.schema.json, src/main/resources/raml/wiremock-admin-api.raml
Split off from PR #888 to make it easier to review. This adds an API schema for `/__admin/near-misses/request`, which is required for OpenAPI 3 conversion to work.
=> Add API schema for /__admin/near-misses/request

docs-v2/_docs/record-playback.md, src/main/resources/raml/schemas/scenario.schema.json, src/main/resources/raml/schemas/stub-mapping.schema.json
Split off from PR #888 to make it easier to review. This fixes a few mistakes in the docs and API specs:
1. The recording API takes a 'persist' parameter, not 'persistent'
2. The `stub-mapping.schema.json` spec used 'descrption' instead of 'description'
3. The `scenario.schema.json` spec used 'examples' instead of 'example'. While 'examples' is valid JSON Schema, everything else uses 'example', and this is what api-spec-converter looks for.
The latter 2 are required for OpenAPI 3 conversion to work
=> Fix typos in documentation and API specs

src/test/java/com/github/tomakehurst/wiremock/AcceptanceTestBase.java, src/test/java/com/github/tomakehurst/wiremock/matching/EqualToXmlPatternTest.java
The tests AdminApiTest and EqualToXmlPatternTest assert English XML parser
error messages. To make those tests succeed for users having a non-English
default locale we set the default locale to English in those tests.
We refrain from setting the system property user.language in build.gradle
because that would only fix the tests when run from the command line, not when
run from some IDE.
=> Fix build (tests) for users having a non-English default locale

src/main/java/com/github/tomakehurst/wiremock/servlet/WireMockHttpServletRequestAdapter.java, src/test/java/com/github/tomakehurst/wiremock/MultipartBodyMatchingAcceptanceTest.java
The underlying jetty code does only support multipart/form-data. Any other multipart content like multipart/mixed can not be used with the MultipartValuePattern! (fixes #920)
=> Do not fail in case of multipart/mixed requests. 

src/main/resources/raml/wiremock-admin-api.raml
This adds https support explicitly for swagger.  The root issue appears to be in swagger, but if you list https and then http explicitly as supported schemes it will function correctly in the UI and follow the base protocol in the URL
Fix worked locally for me.
=> issue-965 - fix issue with swagger-ui and https

src/main/java/com/github/tomakehurst/wiremock/WireMockServer.java, src/test/java/com/github/tomakehurst/wiremock/WireMockServerTests.java
I wanted to get url like `http://localhost:34567` but `url(String path)` method allowed only to get url  with a tailing slash (when I passed empty string), so I created method named `baseUrl()` that allows to get wiremock url without a slash at the end.
=> Add base url method to wiremock server

src/main/java/com/github/tomakehurst/wiremock/common/ProxySettings.java, src/main/java/com/github/tomakehurst/wiremock/http/HttpClientFactory.java, src/main/java/com/github/tomakehurst/wiremock/standalone/CommandLineOptions.java, src/test/java/com/github/tomakehurst/wiremock/common/ProxySettingsTest.java, src/test/java/com/github/tomakehurst/wiremock/standalone/CommandLineOptionsTest.java
Hi,
I added the support of proxy-via that needs a proxy with authentication.
ie: http://user:password@proxy.com
PS: I had 2 broken UT related to internationalization:
Expected: is "Content is not allowed in prolog.; line 1; column 1"
but: was "Contenu non autorisé dans le prologue.; line 1; column 1"
com.github.tomakehurst.wiremock.matching.EqualToXmlPatternTest > logsASensibleErrorMessageWhenActualXmlIsBadlyFormed FAILED
com.github.tomakehurst.wiremock.AdminApiTest > returnsBadEntityStatusWhenInvalidEqualToXmlSpecified FAILED
Kevin
=> Add user authentication for the Proxy via

src/main/java/com/github/tomakehurst/wiremock/standalone/WireMockServerRunner.java, src/test/java/com/github/tomakehurst/wiremock/StandaloneAcceptanceTest.java
`isRunning()` no longer throws NPE if executed prior to `run()`.
=> Remove temporal coupling between run() and isRunning()

docs-v2/_docs/request-matching.md
Fix two typos in request-matching documentation found when reviewing documentation.
=> [fix_typos_in_request_matching] Fix docs typos

src/main/java/com/github/tomakehurst/wiremock/matching/MatchesJsonPathPattern.java, src/main/java/com/github/tomakehurst/wiremock/matching/MatchesXPathPattern.java, src/main/java/com/github/tomakehurst/wiremock/matching/PathPattern.java, src/main/java/com/github/tomakehurst/wiremock/matching/RequestPattern.java
We try to use Wiremock for performance tests, but there is a bottleneck.
We have a mix of XML and Json stubs, and Wiremock try to parse json request in XML (see issue #776 and #652).
Or parsing data in XML is a heavy operation (CPU intensive, generate exception, ...), so don't try to parse non XML value in XPath matcher
**With this simple test case:**
```java
@Test
public void perfXmlTest() {
perfRunXPath("matchingXPath on XML datas", "<perf-test>perf-data</perf-test>");
perfRunXPath("matchingXPath on JSON datas", "{\"perf-test\": \"perf-data\"}");
}
private void perfRunXPath(String message, String value) {
long ts = System.currentTimeMillis();
for (int i = 0; i < 100000; i++) {
WireMock.matchingXPath("//perf-test").match(value);
}
System.out.println(message + ":\t" + …
```
=> Don't try to parse non XML value in XPath matcher

src/main/java/com/github/tomakehurst/wiremock/http/CaseInsensitiveKey.java, src/main/java/com/github/tomakehurst/wiremock/http/HttpHeader.java, src/main/java/com/github/tomakehurst/wiremock/jetty9/JettyUtils.java, src/main/java/com/github/tomakehurst/wiremock/servlet/WireMockHttpServletRequestAdapter.java
With a performance test and this stub config:
```java
WireMockServer wireMockServer = new WireMockServer(options().port(0));
wireMockServer.start();
wireMockServer.stubFor(get(urlEqualTo("/something")).willReturn(aResponse().withStatus(200)));
```
CPU profile usage give this :
**java.lang.String.toLowerCase():** 7% of CPU time
**java.lang.Class.forName():** 11% of CPU time
**java.lang.Class.getDeclaredMethod():** 1% of CPU time
This PR fixes these problems:
- Replace [string].toLowerCase().equals([string].toLowerCase()) by [string].equalsIgnoreCase([string]), it is more efficient
- detect if we are in Jetty server only once at startup
- optimize JettyUtils.getUri() method by caching getDeclaredMethod
=> Fix CPU Utilization Issues

src/main/java/com/github/tomakehurst/wiremock/matching/MatchesJsonPathPattern.java
We have a mix of XML and JSON stubs, and Wiremock try to parse XML request body in JSON.
So, if request body starts with a '<', don't try to parse it in JSON
**With this simple test case:**
```java
@Test
public void perfJsonTest() {
perfRunJsonPath("matchingJsonPath on XML datas", " <perf-test>perf-data</perf-test> ");
perfRunJsonPath("matchingJsonPath on JSON datas", " {\"perf-test\": \"perf-data\"} ");
}
private void perfRunJsonPath(String message, String value) {
long ts = System.currentTimeMillis();
for (int i = 0; i < 100000; i++) {
WireMock.matchingJsonPath("$.perf-test").match(value);
}
System.out.println(message + ":\t" + (System.currentTimeMillis() - ts) + "ms");
}
```
**Without my merge request:**
matchingJsonPath on XML datas:	1411ms
matchingJsonPath on JSON datas:	487ms
**With …
=> For performance reason, don't try to parse XML value in MatchesJsonPathPattern

src/main/java/com/github/tomakehurst/wiremock/common/Xml.java
This commit fixes problem of using `DocumentBuilderFactoryImpl` from `com.sun.org.apache.xerces.internal.jaxp` package. Problem arises as this package is not public (not exported) since JDK 9. Solution is to replace use of this class with `DocumentBuilderFactory` from exported package `java.xml.parsers`.
=> Replace usage of internal java.xml class with public abstraction

src/main/java/com/github/tomakehurst/wiremock/extension/responsetemplating/HandlebarsOptimizedTemplate.java, src/main/java/com/github/tomakehurst/wiremock/extension/responsetemplating/ResponseTemplateTransformer.java
See #1077 and #1082 
See also https://github.com/jknack/handlebars.java/issues/681
Response time with a text file without any {{ }}:
|  Size  | Without this PR | With this PR  |
| ------------- | ------------- | ------------- |
|  500kb  | 15 sec | 50 ms |
|  1Mb | 35 sec | 50 ms |
=> Only template datas between first '{{' and last '}}'

docs-v2/_docs/response-templating.md, src/main/java/com/github/tomakehurst/wiremock/extension/responsetemplating/helpers/RenderableDate.java, src/test/java/com/github/tomakehurst/wiremock/extension/responsetemplating/helpers/HandlebarsCurrentDateHelperTest.java
Fixes #1110 by adding support for `{{now format='unix'}}`
=> Add support for unix timestamp in seconds

src/main/java/com/github/tomakehurst/wiremock/extension/responsetemplating/ResponseTemplateTransformer.java, src/test/java/com/github/tomakehurst/wiremock/ResponseTemplatingAcceptanceTest.java
The `disableBodyFileTemplating` property provides a useful way to disable templating for body files on a per stub basis. However, it can cause problems with a stub such as this one:
```
{
"request": {
"urlPattern": "/asset/.*"
},
"response": {
"status": 200,
"bodyFileName": "{{request.path.1}}",
"headers": {
"Content-Type": "image/jpeg"
},
"transformerParameters": {
"disableBodyFileTemplating": true
}
}
}
```
In this case the body file is an image, but the file name is derived through templating. If I don't pass `"disableBodyFileTemplating": true`, WireMock crashes as it tries to apply the handlebar templating to a binary `.jpg` file. However, if I do pass `"disableBodyFileTemplating": true` it also breaks because the file name is not expanded (WireMock tries to find the …
=> Apply disableBodyFileTemplating only to body content

README.md
I couldn't work out how to build since the `shadowJar` task advised in the README was missing. Actually, I discovered how in the './go' task, then later found this thread: https://groups.google.com/forum/#!topic/wiremock-user/Mt6R04oU0Nw
I don't know if there's other places in the docs to update, but this would help newcomers...
(force pushed to branch in my fork as accidentally included an unrelated commit)
=> Update docs with how to build standalone jar

build.gradle
jackson-databind 2.9.8 by CVE-2019-12086, which is fixed in jackson-databind 2.9.9.
See: https://github.com/FasterXML/jackson-databind/issues/2326
=> Upgrade jackson to avoid CVEs

src/main/java/com/github/tomakehurst/wiremock/recording/ScenarioProcessor.java, src/test/java/com/github/tomakehurst/wiremock/RecordApiAcceptanceTest.java, src/test/java/com/github/tomakehurst/wiremock/SnapshotDslAcceptanceTest.java, src/test/java/com/github/tomakehurst/wiremock/recording/ScenarioProcessorTest.java
Without this playback gets confused when the same url is
hit (such as is typical with a SOAP API) but groups differently
based on payload or headers.
=> Add scenario index on record: differentiates per RequestPattern group

build.gradle, src/main/java/com/github/tomakehurst/wiremock/common/Json.java, src/test/java/com/github/tomakehurst/wiremock/AdminApiTest.java
Changes in _Json.java_ are due to: https://github.com/FasterXML/jackson-databind/issues/1675
Changes in _AdminApiTest.java_ are due to: https://github.com/FasterXML/jackson-core/blob/master/src/main/java/com/fasterxml/jackson/core/json/JsonParserBase.java#L110
=> Upgrade to Jackson 2.10.0

build.gradle
`zjsonpatch` adds older `jackson` dependencies than the ones that are already being added by wiremock itself.
=> Exclude transitive jackson dependencies

build.gradle
Still running into dependency convergence errors in 2.25.1
This fixes https://github.com/tomakehurst/wiremock/issues/1083
=> Fix asm dependency convergence errors

docs-v2/_docs/https.md, docs-v2/_docs/running-standalone.md, src/main/java/com/github/tomakehurst/wiremock/WireMockServer.java, src/main/java/com/github/tomakehurst/wiremock/core/Options.java, src/main/java/com/github/tomakehurst/wiremock/core/WireMockConfiguration.java, src/main/java/com/github/tomakehurst/wiremock/jetty9/JettyHttpServer.java, src/main/java/com/github/tomakehurst/wiremock/servlet/WarConfiguration.java, src/main/java/com/github/tomakehurst/wiremock/standalone/CommandLineOptions.java, src/test/java/com/github/tomakehurst/wiremock/HttpsAcceptanceTest.java, src/test/java/com/github/tomakehurst/wiremock/jetty9/JettyHttpServerTest.java, src/test/java/com/github/tomakehurst/wiremock/standalone/CommandLineOptionsTest.java, src/test/java/ignored/Examples.java
**Context:**
By default, Wiremock has always an HTTP listener started on 8080 if the flag `port` is not set even if you are setting an HTTPS listener.
**Goal:**
Adding a flag `--http-disabled` allowing the Wiremock server to be reached only from HTTPS.
=> Feature: Add --http-disabled flag

docs-v2/_docs/running-standalone.md
Link to download standalone JAR from Maven central was using HTTP rather than HTTPS.
The HTTP URL now gives a `501` error:
> 501 HTTPS Required. 
> Use https://repo1.maven.org/maven2/
>More information at https://links.sonatype.com/central/501-https-required
=> Update link to standalone JAR to use HTTPS

docs-v2/_docs/download-and-installation.md, docs-v2/_docs/getting-started.md
Maven central recently moved to HTTPS only, the links were returning a 501 error.
Found 2 other locations that were not covered by #1244
=> Use HTTPS for Maven central links in documentation

docs-v2/_docs/response-templating.md
The handlebars in the example does not line up - I guess you could use two or three curly brackets as long as they match. I got it working with the changes I made.
=> Docs: Fix handlebar syntax in formData example

src/main/java/com/github/tomakehurst/wiremock/http/HttpHeaders.java, src/test/java/com/github/tomakehurst/wiremock/http/HttpHeadersTest.java
Actually, cache doesn't work because of incorrect HttpHeaders.hashCode() implementation.
This pull request fix this bug 😃
=> Make response template caching works

src/main/java/com/github/tomakehurst/wiremock/extension/responsetemplating/ResponseTemplateTransformer.java, src/test/java/com/github/tomakehurst/wiremock/extension/responsetemplating/ResponseTemplateTransformerTest.java
With configuration like this:
```
"response": {
"proxyBaseUrl": "http://127.0.0.1:8080/test",
"additionalProxyRequestHeaders": {
"X-Wiremock-Uuid": "{{randomValue type='UUID'}}"
},
"transformers": ["response-template"]
}
```
`X-Wiremock-Uuid` header is not forwarded to `proxyBaseUrl`
This pull request fix this bug 😃
=> Fix proxy options additionalRequestHeaders bug

src/main/java/com/github/tomakehurst/wiremock/client/VerificationException.java, src/test/java/com/github/tomakehurst/wiremock/junit/WireMockRuleFailOnUnmatchedRequestsTest.java
The intent behind the exception message is that request must be printed but it was not being done due to the lack of formatter in `String.format`, this PR fixes that issue and modifies the tests to assert the same.
=> Add request details to VerificationException

docs-v2/_docs/response-templating.md
It took me a while to work out why my parameters weren't showing up in my template, and it was because I didn't realise I needed a `parameters.` prefix to select them from the model (I ended up debugging it to work out why it wasn't working). Thought I'd update the documentation to hopefully prevent others making the same mistake with this great tool!
=> Doc update to "Response Templating" adding `parameters.` prefix

src/main/java/com/github/tomakehurst/wiremock/extension/responsetemplating/RequestTemplateModel.java, src/test/java/com/github/tomakehurst/wiremock/extension/responsetemplating/ResponseTemplateTransformerTest.java
This changes adaptedHeaders in `RequestTemplateModel.from(..)` to TreeMap with CASE_INSENSITIVE_ORDER to ignore case for headers in response templating.
E.g. allows that `{{request.headers.X-CorrelationID}}` also matches `x-correlationid`.
Resolves issue https://github.com/tomakehurst/wiremock/issues/1313
=> Response Templating: Case-Insensitive Headers

build.gradle, src/main/java/com/github/tomakehurst/wiremock/jetty9/JettyHttpServer.java, src/test/java/com/github/tomakehurst/wiremock/BrowserProxyAcceptanceTest.java, src/test/java/com/github/tomakehurst/wiremock/testsupport/WireMockTestClient.java
This allows WireMock to act as a forward (browser) proxy for HTTPS as well as
HTTP origins.
At present it is a pure HTTP tunnel, so stubbing & recording are not supported
and the client will get the precise byte stream (including TLS certificate)
from the endpoint.
First step towards implementing #401.
=> Allow pass through forward proxying of HTTPS

README.md, java8/src/main/java/com/github/tomakehurst/wiremock/jetty94/Jetty94HttpServer.java, java8/src/main/java/com/github/tomakehurst/wiremock/jetty94/ManInTheMiddleSslConnectHandler.java, java8/src/test/java/com/github/tomakehurst/wiremock/Http2BrowserProxyAcceptanceTest.java, src/main/java/com/github/tomakehurst/wiremock/jetty9/JettyHttpServer.java, src/main/java/com/github/tomakehurst/wiremock/junit/WireMockClassRule.java, src/test/java/com/github/tomakehurst/wiremock/BrowserProxyAcceptanceTest.java, src/test/java/com/github/tomakehurst/wiremock/ResponseDribbleAcceptanceTest.java, src/test/java/com/github/tomakehurst/wiremock/testsupport/WireMockTestClient.java
This allows WireMock to act as a forward (browser) proxy for HTTPS as well
as HTTP origins whilst stubbing & recording.
Step towards implementing #401.
=> Stub & record forward proxy https traffic

docs-v2/_docs/proxying.md, docs-v2/_docs/running-standalone.md, java8/build.gradle, java8/src/test/java/com/github/tomakehurst/wiremock/HttpsBrowserProxyAcceptanceTest.java, src/main/java/com/github/tomakehurst/wiremock/core/Options.java, src/main/java/com/github/tomakehurst/wiremock/core/WireMockApp.java, src/main/java/com/github/tomakehurst/wiremock/core/WireMockConfiguration.java, src/main/java/com/github/tomakehurst/wiremock/http/HttpClientFactory.java, src/main/java/com/github/tomakehurst/wiremock/http/ProxyResponseRenderer.java, src/main/java/com/github/tomakehurst/wiremock/servlet/WarConfiguration.java, src/main/java/com/github/tomakehurst/wiremock/standalone/CommandLineOptions.java, src/test/java/com/github/tomakehurst/wiremock/crypto/CertificateSpecification.java, src/test/java/com/github/tomakehurst/wiremock/crypto/InMemoryKeyStore.java, src/test/java/com/github/tomakehurst/wiremock/crypto/Secret.java, src/test/java/com/github/tomakehurst/wiremock/crypto/X509CertificateSpecification.java, src/test/java/com/github/tomakehurst/wiremock/crypto/X509CertificateVersion.java, src/test/java/com/github/tomakehurst/wiremock/http/ProxyResponseRendererTest.java, src/test/java/com/github/tomakehurst/wiremock/standalone/CommandLineOptionsTest.java
Provide an option `--trust-all` to allow turning this behaviour off.
=> Validate certs by default on forward proxy

java8/build.gradle
conscrypt:2.4.0 depends on an OpenSSL version only found in OS/X Catalina, so
forces users to upgrade their O/S. Reverting to old version.
=> Revert upgrading conscrypt

build.gradle
Updating version of httpclient as new version fixes [CVE-2020-13956](https://bugzilla.redhat.com/show_bug.cgi?id=1886587)
=> updates httpclient version to 4.5.13

src/main/java/com/github/tomakehurst/wiremock/common/JettySettings.java, src/main/java/com/github/tomakehurst/wiremock/core/WireMockConfiguration.java, src/main/java/com/github/tomakehurst/wiremock/jetty9/JettyHttpServer.java, src/main/java/com/github/tomakehurst/wiremock/standalone/CommandLineOptions.java, src/test/java/com/github/tomakehurst/wiremock/common/JettySettingsTest.java, src/test/java/com/github/tomakehurst/wiremock/core/WireMockConfigurationTest.java, src/test/java/com/github/tomakehurst/wiremock/standalone/CommandLineOptionsTest.java
The purpose of this PR is to add the ability to set Jetty's idleTimeout parameter.
This PR solves the issue of the nginx LB returning 502 errors when calling a downstream Wiremock Jetty server. This nginx / Jetty issue is a known one:
https://github.com/eclipse/jetty.project/issues/2791#issuecomment-413173044
https://stackoverflow.com/questions/51865009/http-502-bad-gateway-writev-failed-104-connection-reset-by-peer
Nginx holds an open connection to Wiremock for a set amount of time: https://www.nginx.com/blog/http-keepalives-and-web-performance/
If the nginx keepalive is longer than the Jetty idleTimeout, the result is sporadic closing of connections by Jetty that causes nginx to return a 502 error to the upstream caller.
As you can see from the attached issues, given a system where it …
=> Add the ability to specify Jetty's idleTimeout

build.gradle
Currently the WireMock standalone .jar distribution includes a Java module information file `module-info.class` that is coming from a transitive dependency during the class relocation by the shadow jar builder.
That module-info contains an incorrect module declaration unrelated to WireMock (I think it is for jackson data bind module).
The problem is that the module-info.class is getting recognized by the Maven compiler plugin as well as in runtime preventing the use of WireMock for testing  module Java applications due class loading error.
A compile time error looks like:
`package com.github.tomakehurst.wiremock does not exist
cannot find symbol
symbol:   class WireMockServer`
A runtime error:  
```
java.lang.NoClassDefFoundError: com/github/tomakehurst/wiremock/WireMockServer
Caused by: …
```
=> Exclude module-info form standalone jar

testlogging/pom.xml
[![mitm_build](https://user-images.githubusercontent.com/1323708/59226671-90645200-8ba1-11e9-8ab3-39292bef99e9.jpeg)](https://medium.com/@jonathan.leitschuh/want-to-take-over-the-java-ecosystem-all-you-need-is-a-mitm-1fc329d898fb?source=friends_link&sk=3c99970c55a899ad9ef41f126efcde0e)
- [Want to take over the Java ecosystem? All you need is a MITM!](https://medium.com/@jonathan.leitschuh/want-to-take-over-the-java-ecosystem-all-you-need-is-a-mitm-1fc329d898fb?source=friends_link&sk=3c99970c55a899ad9ef41f126efcde0e)
- [Update: Want to take over the Java ecosystem? All you need is a MITM!](https://medium.com/bugbountywriteup/update-want-to-take-over-the-java-ecosystem-all-you-need-is-a-mitm-d069d253fe23?source=friends_link&sk=8c8e52a7d57b98d0b7e541665688b454)
---
This is a security fix for …
=> [SECURITY] Use HTTPS to resolve dependencies in Maven Build

docs-v2/_docs/proxying.md
http://wiremock.org/docs/proxying/ has a broken link to a script to create a self-signed root certificate. This link was added in 396e4c870775f37e4ff2efe80c8e6af91ca7ef8e, and I'm pretty sure it was intended to link to https://github.com/tomakehurst/wiremock/blob/master/scripts/create-ca-keystore.sh
=> Fix broken link to script on "Proxying" page

docs-v2/_docs/getting-started.md
The standalone-jar link in getting-started was broken, so I made it the same as download-and-installation and running-standalone.
=> Fix broken link

docs-v2/_docs/response-templating.md, src/main/java/com/github/tomakehurst/wiremock/extension/responsetemplating/helpers/HandlebarsJsonPathHelper.java, src/test/java/com/github/tomakehurst/wiremock/extension/responsetemplating/ResponseTemplateTransformerTest.java, src/test/java/com/github/tomakehurst/wiremock/extension/responsetemplating/helpers/HandlebarsHelperTestBase.java, src/test/java/com/github/tomakehurst/wiremock/extension/responsetemplating/helpers/HandlebarsJsonPathHelperTest.java
This PR includes two related changes to the JsonPath template helper:
1. output nothing (empty string) when no path matched instead of error message
2. allow overriding the default value when no path matched
The default value is static only. There may be a more generic solution to apply defaults for example by adding a "default" helper.
Gradle build didn't work for me on Oracle JDK 14 so I just ran a subset of the unit tests in Intellij.
Let me know if you want docs updated.
=> Add support for jsonpath defaults

docs-v2/_docs/response-templating.md, src/main/java/com/github/tomakehurst/wiremock/extension/responsetemplating/helpers/HandlebarsRandomValuesHelper.java, src/test/java/com/github/tomakehurst/wiremock/extension/responsetemplating/helpers/HandlebarsRandomValuesHelperTest.java
I would like to be able to use the standalone mock to generate hexadecimal strings without having to write any Java code, but it seems that the current version of wiremock does not support this.
With this merge request, a hexadecimal string can be generated using the [response templating](http://wiremock.org/docs/response-templating/) feature.
=> Response templating: Add support for random hexadecimal strings

docs-v2/package-lock.json, src/main/java/com/github/tomakehurst/wiremock/recording/LoggedResponseDefinitionTransformer.java, src/test/java/com/github/tomakehurst/wiremock/recording/LoggedResponseDefinitionTransformerTest.java
NPE observed when proxied server errored out and returned no header.  Null header collection was not being checked for in the `bodyDecompressedIfRequired` helper.
=> Fixes #1528, NPE when proxied response contains no headers

src/main/java/com/github/tomakehurst/wiremock/extension/responsetemplating/helpers/ParseJsonHelper.java, src/test/java/com/github/tomakehurst/wiremock/extension/responsetemplating/helpers/ParseJsonHelperTest.java
fixes #1547
- Adds a ParseJsonHelperTest.java test file.
- Adds 5 test cases including 2 where the array is at the top level.
- Checks whether the json is enclosed by array tags.
- If it is then a List <Object> is returned instead of a Map <String, Object>.
- This way it does not interfere with other test cases.
=> Fix 1547 parse json helper

src/main/java/com/github/tomakehurst/wiremock/extension/responsetemplating/helpers/ParseJsonHelper.java, src/test/java/com/github/tomakehurst/wiremock/extension/responsetemplating/helpers/ParseJsonHelperTest.java
fixes #1545 
- Add 2 unit tests for if null is passed in (TAGTYPE.Section as an extra condition)
- Add 2 unit tests for if "{}" is passed in (TAGTYPE.Section as an extra condition)  
- Fix these two edge cases by adding a conditional at the beginning and returning an empty map in this case
=> Fix #1545 - Parse null json

docs-v2/_docs/getting-started.md
At first glance it looks like JUnit 5 is not well supported due to specific callout for JUnit 4 usage and no mention of JUnit 5. This should help fix that.
=> Add link to JUnit 5 docs from Getting Started page

src/main/java/com/github/tomakehurst/wiremock/junit5/WireMockExtension.java, src/test/java/com/github/tomakehurst/wiremock/junit5/JunitJupiterExtensionDeclarativeWithConfiguredNestedTest.java, src/test/java/com/github/tomakehurst/wiremock/junit5/JunitJupiterExtensionDeclarativeWithNestedTest.java
When using `@WireMockTest` with two or more nested classes WireMock server never become running after first nested test class is executed.
Closes #1596
=> Fixed Junit Jupiter extension issue with nested tests.

docs-v2/_docs/running-standalone.md, src/main/java/com/github/tomakehurst/wiremock/standalone/CommandLineOptions.java, src/test/java/com/github/tomakehurst/wiremock/standalone/CommandLineOptionsTest.java
To allow consumers to shade their standalone JAR with the stubs they
want to produce, for instance to allow there to be a single artefact
with all their stubs and code, we should allow this being specified to
be part of the classpath.
This introduces a new flag, `--root-dir-under-classpath`, to allow
configuring both the `__files` and `mappings` directories, as it's more
likely that they'll be configured together, especially as the underlying
`FileSource` is shared.
Closes #1502.
=> Allow standalone runner to fetch mappings from classpath

src/main/java/com/github/tomakehurst/wiremock/junit5/WireMockExtension.java, src/test/java/com/github/tomakehurst/wiremock/junit5/JUnitJupiterExtensionFailOnUnmatchedTest.java
(Final unsolicited MR, I promise :heart: )
In migrating both my own projects and [all project tests](https://github.com/wiremock/wiremock/pull/1616), I found that for [programmatic use](http://wiremock.org/docs/junit-jupiter/) there's a frequent need to compose URLs to instances of `WireMockExtension`. Since `WireMockExtension` does not expose the underlying `WireMockServer`, one is then forced to compose URLs by calling `baseUrl()` and appending/formatting the suffix. For such a common use case I think there's value in creating a direct delegate method to do the same.
As seen in `JUnitJupiterExtensionFailOnUnmatchedTest` this simplifies the URL composition, and reduces the need for `baseUrl()`. I understand it's not desirable to have delegates to all methods in `WireMockServer`, but for …
=> Delegate WireMockExtension.url(String) to WireMockServer

src/main/java/com/github/tomakehurst/wiremock/http/ResponseDefinition.java, src/test/java/com/github/tomakehurst/wiremock/http/ResponseDefinitionTest.java
This pull request is created to fix the issue mentioned in https://github.com/wiremock/wiremock/issues/1012.
Issue:
When using the wiremock recoder __admin/recorder/, if there's a space before the Target URL in the URL box, wiremock throws the IllegalArgumentException error.
Code change:
Trimmed the proxyBaseUrl in ResponseDefinition.java as below:
this.proxyBaseUrl = proxyBaseUrl == null ? null : proxyBaseUrl.trim();
Unit tests added.
=> fix for bug 1012 - Wiremock recorder space before the Target URL

build.gradle
It's unclear as to why this is no longer working, but as it's currently
blocking the release being published, we'll resolve it for now.
=> Add missing `description` to the slim JAR's generated POM

docs-v2/_docs/download-and-installation.md
Currently, the instructions for using WireMock with Gradle are incorrect. The Java 8 and deprecated Java 7 artifacts are swapped, and the deprecated Java 7 artifact uses the current version (when it should end at 2.27.2). 
This PR corrects this, so the Gradle instructions match the Maven instructions. 
Please let me know if there is anything else I need to do (like running the `gen-docs.sh` script?), or if this PR is otherwise unacceptable for some reason. 
I know this is a small thing, but I've seen people pull in the old Java 7 artifact when copy-pasting from here on a new project.
=> docs: Fix example Gradle configuration

src/main/java/com/github/tomakehurst/wiremock/servlet/WireMockHttpServletRequestAdapter.java
Speeds up `contentTypeHeader` and `getHeader` by avoiding intermediate `HashSet`s, `Enumeration`s, and `ArrayList`s.
21% of CPU time in my benchmark is spent in `WireMockHttpServletRequestAdapter.contentTypeHeader`. Current implementation creates multiple intermediate collections of _all_ the header names in order to fish out the case-insensitive version of the single header we're interested in.
Per the [servlet 3 javadocs](https://github.com/javaee/servlet-spec/blob/3.1.0/src/main/java/javax/servlet/http/HttpServletRequest.java#L171-L172), `getHeader(String)` is case-insensitive and should be able to get us what we need directly. I've verified that jetty 9's behavior seems to conform to the spec.
cc: @avinashanne @sumerjoshi
=> Speed up contentTypeHeader, getHeader

docs-v2/_docs/docker.md
It fixes docker commands in docker section documentation
=> Add missing backslashes in docker commands

.github/workflows/build-and-test.yml
NOTE: Adopt OpenJDK got moved to Eclipse Temurin and won't be updated anymore. It is highly recommended to migrate workflows from adopt to temurin to keep receiving software and security updates.
https://github.com/actions/setup-java/blob/main/README.md
﻿
=> Temurin JDK

src/main/java/com/github/tomakehurst/wiremock/client/ResponseDefinitionBuilder.java, src/main/java/com/github/tomakehurst/wiremock/extension/responsetemplating/ResponseTemplateTransformer.java, src/main/java/com/github/tomakehurst/wiremock/http/Body.java, src/main/java/com/github/tomakehurst/wiremock/http/ResponseDefinition.java
This is the more aggressive version of https://github.com/wiremock/wiremock/pull/1772 that eliminates _all four_ major stacks in the flame graph below--not just the highlighted ones.
Dealing in terms of `Body` as a first-class entity separates out concerns nicely. PR diff is LOC negative already, but we could also delete `ResponseDefinitionBuilder.with...Body(...)`, `ResponseDefinition.get...Body`, and `ResponseDefinition(..., bytes[] body, ...)` if you don't mind the breaking API changes. We could also deprecate them for a while, or just leave them as is. Let me know your preference.
I'm already enjoying the performance benefits of this change via `ResponseDefinition.class.getDeclaredField("body").setAccessible(true)` etc., but it'd be nice to switch back to public APIs.
=> perf: Avoid unnecessary intermediate `JsonNode`

src/test/java/com/github/tomakehurst/wiremock/direct/DirectCallHttpServerIntegrationTest.java
We're seeing this test failing quite a bit, in cases where the delay is
499ms instead of 500ms, and therefore failing.
To avoid this, we can instead reduce the threshold to >= 499ms, and give
us a bit of breathing room for us to remediate this longer-term.
=> Reduce threshold for flakey test

src/main/java/com/github/tomakehurst/wiremock/http/ProxyResponseRenderer.java, src/test/java/com/github/tomakehurst/wiremock/http/ProxyBaseUrlTest.java
fix request entity setting for any request methods
=> proxy request fix

README.md, src/main/java/com/github/tomakehurst/wiremock/extension/requestfilter/RequestWrapper.java, src/main/java/com/github/tomakehurst/wiremock/http/AbstractRequestHandler.java, src/main/java/com/github/tomakehurst/wiremock/http/Request.java, src/main/java/com/github/tomakehurst/wiremock/http/Response.java, src/main/java/com/github/tomakehurst/wiremock/servlet/WireMockHttpServletRequestAdapter.java, src/main/java/com/github/tomakehurst/wiremock/verification/LoggedRequest.java, src/main/java/com/github/tomakehurst/wiremock/verification/diff/EmptyToStringRequestWrapper.java, src/test/java/com/github/tomakehurst/wiremock/http/ProxyResponseRendererTest.java, src/test/java/com/github/tomakehurst/wiremock/matching/MockRequest.java, src/test/java/com/github/tomakehurst/wiremock/stubbing/StubRequestHandlerTest.java, src/test/java/com/github/tomakehurst/wiremock/testsupport/MockRequestBuilder.java, src/test/java/com/github/tomakehurst/wiremock/verification/LoggedRequestTest.java
=> Bugfix: response header not reflecting correct version of http #1689

src/main/java/com/github/tomakehurst/wiremock/matching/AbstractDateTimeMatchResult.java, src/main/java/com/github/tomakehurst/wiremock/matching/AbstractDateTimePattern.java, src/test/java/com/github/tomakehurst/wiremock/StubbingAcceptanceTest.java, src/test/java/com/github/tomakehurst/wiremock/matching/AfterDateTimePatternTest.java, src/test/java/com/github/tomakehurst/wiremock/matching/BeforeDateTimePatternTest.java, src/test/java/com/github/tomakehurst/wiremock/matching/EqualToDateTimePatternTest.java, src/test/java/com/github/tomakehurst/wiremock/matching/MultiValuePatternTest.java
- Adding failing test cases
- Apply a fix for the failing test cases
=> Closes #1882 - Enable multi value pattern matching for DateTime

testlogging/pom.xml, testlogging/src/test/java/WiremockTest.java, testlogging/src/test/resources/logback-test.xml
The whole point is to make sure the standalone jar does not shade the
logging classes.
=> Run the logging test against standalone

src/main/java/com/github/tomakehurst/wiremock/client/ResponseDefinitionBuilder.java
The proxyUrlPrefixToRemove  property wasn not being properly applied during runtime. It was not being persisted through the ResponseDefinitionBuilder as it was being stored as a (not static) local variable in a static class. 
Also it will now conditionally return builder of ProxyResponseDefinitionBuilder if proxyBaseUrl is set
=> Fix proxyUrlPrefixToRemove property not being applied 

src/main/java/com/github/tomakehurst/wiremock/http/ProxyResponseRenderer.java, src/test/java/com/github/tomakehurst/wiremock/http/ProxyResponseRendererTest.java
fixes #1872
To enable valid POST requests without a body, an empty entity is required.
Otherwise, the proxy request will not include the header content-length.
Additionally, the content-type will only be set if it is already present
in the originalRequest.
This prevents a new, additional header from being set.
=> Create request entity if content-length is set (#1872)

build.gradle
To ensure that this project can be correctly reproduced by an
independent build of the project, we should enable reproducible builds
in Gradle, across all projects.
=> Enable reproducible builds

build.gradle
I think this is okay as I cannot find a reference to it either in the code or in the dependencies of any of the build stages (transitive or otherwise).
=> removes maven dir in output shadow jar

src/main/java/com/github/tomakehurst/wiremock/stubbing/Scenarios.java, src/test/java/com/github/tomakehurst/wiremock/stubbing/ScenariosTest.java
Just because the old mapping is in a scenario doesn't mean its replacement is.
=> Fix NullPointerException

src/main/java/com/github/tomakehurst/wiremock/stubbing/StubMappingJsonRecorder.java, src/test/java/com/github/tomakehurst/wiremock/stubbing/StubMappingJsonRecorderTest.java
Recording the body instead.
This can happen when content of the multipart is not a file, so there is no header with content disposition giving it a filename. E.g. an OData $batch request.
Wiremock is currently failing the request, giving a 500 back because of the NPE, even when proxying when we got proper data back.
**edit** went a bit further on the library and saw what was going on, I assumed the lib I was using bad generating the request wrong and hence couldn't be parsed, but really wiremock assumes is going to be files whose parsing will work, not a bad assumption but it doesn't fit certain cases and the NPE is bad.
=> Skips NPE when a multipart could not be parsed

src/main/java/com/github/tomakehurst/wiremock/client/WireMock.java, src/main/java/com/github/tomakehurst/wiremock/matching/NotPattern.java, src/main/java/com/github/tomakehurst/wiremock/matching/StringValuePatternJsonDeserializer.java, src/test/java/com/github/tomakehurst/wiremock/VerificationAcceptanceTest.java, src/test/java/com/github/tomakehurst/wiremock/matching/NotPatternTest.java, src/test/java/com/github/tomakehurst/wiremock/matching/RequestPatternTest.java
Implemented a not method in WireMock.java which takes StringPatternValue parameter and returns the opposite of the result. 
For example, verify(getRequestedFor(urlEqualTo("/header/not")).withHeader("X-Thing", not(containing("Four"))));
The functionality has been properly tested, unit and acceptance tests are passing.
New File Added: NotPattern
File modified: StringValuePatternJsonDeserializer
=> New Feature: not() in verify #1892

src/main/java/com/github/tomakehurst/wiremock/http/ssl/CertificateAuthority.java
There is an issue when using dynamically generated certificates for TLS connections to Wiremock regarding the certificate validity start time. The certificates are generated with validity start time being the same instant as the request arrives. If Wiremock runs at the same machine as the client, the problem doesn't manifest itself as they are both using the same clock. However, if the client is somewhere else and its time lags behind the Wiremock machine's time, even if it's an infinitesimal difference, the certificates won't be marked as valid.
To fix the clock skew problem, the certificates are now generated using a day before the present moment as the start time. This avoids the problem.
=> Fixed clock skew problems with dynamically created certificates

src/main/java/com/github/tomakehurst/wiremock/common/ClasspathFileSource.java, src/test/java/com/github/tomakehurst/wiremock/common/ClasspathFileSourceTest.java
I sometimes experience problems with ClassPathFileSource when I am using a dependency with Wiremock files and the web framework changes the context class loader to do its own magic.
This small change allows to pin the class loader of a ClassPathFileSource. Existing behavior is not modified.
=> Allow fixing class loader in ClasspathFileSource

CONTRIBUTING.md, README.md
Just a quick fix. The real improvement for this situation will be https://github.com/wiremock/wiremock.org-sources/issues/28 . Addresses https://github.com/wiremock/wiremock.org-sources/issues/31 for now
=> Fix the Slack link in the contributing guide

src/main/java/com/github/tomakehurst/wiremock/standalone/RemoteMappingsLoader.java, src/main/java/com/github/tomakehurst/wiremock/stubbing/StubMapping.java, src/test/java/com/github/tomakehurst/wiremock/RemoteMappingsLoaderAcceptanceTest.java, src/test/resources/remoteloader/__files/body.xml, src/test/resources/remoteloader/mappings/with-several-mappings-in-one-file.json
This pull request adds field "mappings" to StubMapping class and processing to load() method of RemoteMappingsLoader class if present
- Resolves #2197 issue in a simple way for now, because I don't know plans for 3.0 imports
=> 2197 | added field "mappings" to StubMapping and its processing if it exists

build.gradle, src/main/java/com/github/tomakehurst/wiremock/common/Json.java, src/test/java/com/github/tomakehurst/wiremock/extension/ParametersTest.java
Fixes https://github.com/wiremock/wiremock/issues/1127
* registers JavaTimeModule, "Class that registers capability of serializing java.time objects with the Jackson core." https://fasterxml.github.io/jackson-modules-java8/javadoc/datetime/2.9/com/fasterxml/jackson/datatype/jsr310/JavaTimeModule.html
* I recommend disabling SerializationFeature.WRITE_DATES_AS_TIMESTAMPS as explained [here](https://www.baeldung.com/jackson-serialize-dates#iso-8601)
=> Configure default ObjectMapper with JavaTimeModule

src/main/java/com/github/tomakehurst/wiremock/junit5/WireMockExtension.java, src/test/java/com/github/tomakehurst/wiremock/junit5/JUnitJupiterExtensionDeclarativeProgrammaticMixTest.java
This fixes #2122, please see the issue described there for details.
This PR makes it so that the options of httpPort/httpsPort/httpsEnabled/proxyMode and anything else that might be configured through the `@WireMockTest` attribute for a declarative setup in JUnit5 does not override programmatically configured options.
=> Fix JUnit5 extension bug when using both declarative + programmatic simultaneously 

src/main/java/com/github/tomakehurst/wiremock/extension/responsetemplating/HandlebarsOptimizedTemplate.java, src/test/java/com/github/tomakehurst/wiremock/extension/responsetemplating/ResponseTemplateTransformerTest.java
Handlebars `TextStringBuilder` has a very poor buffer growth strategy.
It increases it by the length of the string to be appended, so *every* append causes *all* the existing data to be copied to a new location in memory.
`java.io.StringBuilder` has a much better approach of doubling the capacity of the buffer each time it is too small, resulting in far fewer copies.
Additionally, it seems to me that setting the initial capacity to double the size of the template will minimise the chances of a copy being needed at all.
=> Improve handlebars performance on large templates

CONTRIBUTING.md
This change should help us to increase velocity of changes
There are a lot of open pull requests that are important to end users and contribute to the WireMock 3.x scope. They keep accumulating overlaps and potential merge conflicts, and also do not get evaluation in the Beta releases.
The only current maintainer, Tom Akehurst, combines a number of roles and does not have much bandwidth to review and merge pull requests. So we need more review and maintainer bandwidth
I would suggest to make the following contributors co-maintainers, or to work towards enabling them.
- @oleg-nenashev 
- @Mahoney 
- @timtebeek 
- @oleg-nenashev 
- @rodolpheche - if we include WireMock Docker into the scope now or later
=> Add WireMock co-maintainers role and document the merge process

src/main/java/com/github/tomakehurst/wiremock/common/JettySettings.java, src/main/java/com/github/tomakehurst/wiremock/jetty11/Jetty11Utils.java
Proposal:
Jetty settings.
Removing Optional.
N/A
=> Proposal: Jetty settings. Removing Optional.

src/main/java/com/github/tomakehurst/wiremock/matching/MatchesJsonSchemaPattern.java, src/test/java/com/github/tomakehurst/wiremock/matching/MatchesJsonSchemaPatternTest.java
An HTTP request without a body (e.g. GET, DELETE) passes null to the matcher which it used not to handle, causing all requests to the WireMock instance to fail.
This PR fixes that bug.
=> MatchesJsonSchemaPattern will return no match for null input

.github/CODEOWNERS
Enables automatic review requests for https://github.com/wiremock/community/issues/42
=> Add WireMock Java Co-Maintainers as codeowners

src/main/java/com/github/tomakehurst/wiremock/common/Encoding.java, src/main/java/com/github/tomakehurst/wiremock/common/JdkBase64Encoder.java, src/main/java/com/github/tomakehurst/wiremock/matching/BinaryEqualToPattern.java, src/test/java/com/github/tomakehurst/wiremock/client/ResponseDefinitionBuilderTest.java, src/test/java/com/github/tomakehurst/wiremock/common/Base64EncoderTest.java, src/test/java/com/github/tomakehurst/wiremock/http/BodyTest.java, src/test/java/com/github/tomakehurst/wiremock/matching/BinaryEqualToPatternPatternTest.java
Replace com.google.common.io.BaseEncoding by java.util.Base64
https://github.com/wiremock/wiremock/issues/2111
=> Replace com.google.common.io.BaseEncoding by java.util.Base64

build.gradle
To avoid compilation error in Eclipse on `import sun.security.x509.*;`.
I found the solution here:
https://stackoverflow.com/a/71749829/2477084
=> add-exports in eclipse configuration

src/main/java/com/github/tomakehurst/wiremock/junit5/WireMockExtension.java
Having a JUnit 5 test that uses [`@DisabledInNativeImage`](https://junit.org/junit5/docs/5.9.1/api/org.junit.jupiter.api/org/junit/jupiter/api/condition/DisabledInNativeImage.html) and the `WireMockExtension` produces an exception when running tests in GraalVM native-image.
Fixes https://github.com/wiremock/wiremock/issues/2202
=> Fixed @WireMockTest not working with @DisabledInNativeImage

src/main/java/com/github/tomakehurst/wiremock/client/WireMock.java, src/test/java/com/github/tomakehurst/wiremock/VerificationAcceptanceTest.java
It is useful for parameterized test, when you also use `request(String method, UrlPattern urlPattern)`
So you are able to write your test like this:
```java
@ParameterizedTest
@ValueSource(strings = {"GET", "POST", "PUT", "HEAD", "TRACE", "PATCH", "OPTIONS", "DELETE", "ANY", "RANDOM"})
public void verifyRequestedForSameMethodAsRequest(String method) {
wiremock.stubFor(request(method, urlEqualTo("/methods")).willReturn(ok("response"));
// ... Test stuff here
verify(requestedFor(method, urlEqualTo("/methods")));
}
```
- I look at https://wiremock.org/docs/verifying/ and there is not an exhaustive list of the applicable method, so I did not modified the documentation
- https://github.com/wiremock/wiremock/issues/2174
=> feat: add a requestedFor method allowing to pass Http method as parameter

src/main/java/com/github/tomakehurst/wiremock/client/ResponseDefinitionBuilder.java, src/main/java/com/github/tomakehurst/wiremock/matching/MultipartValuePatternBuilder.java, src/main/java/com/github/tomakehurst/wiremock/matching/RequestPatternBuilder.java, src/main/java/com/github/tomakehurst/wiremock/recording/RecordSpecBuilder.java, src/test/java/com/github/tomakehurst/wiremock/client/ResponseDefinitionBuilderTest.java, src/test/java/com/github/tomakehurst/wiremock/matching/MultipartValuePatternBuilderTest.java, src/test/java/com/github/tomakehurst/wiremock/testsupport/MockRequestBuilder.java
A small step removing some imports from Guava.
#2111
=> Remove dependencies on new:ing collections with Guava (refs #2111)

src/main/java/com/github/tomakehurst/wiremock/common/AbstractFileSource.java, src/test/java/com/github/tomakehurst/wiremock/StandaloneAcceptanceTest.java, src/test/java/com/github/tomakehurst/wiremock/standalone/JsonFileMappingsSourceTest.java, src/test/java/com/github/tomakehurst/wiremock/store/files/BlobStoreFileSourceTest.java
Removing imports on Guava Files and using Java standard library.
#2111
=> Replace Guava Files management with STL (refs #2111)

src/main/java/com/github/tomakehurst/wiremock/matching/RequestPatternBuilder.java, src/test/java/com/github/tomakehurst/wiremock/VerificationAcceptanceTest.java, src/test/java/ignored/Examples.java
This pull request adds a convenient method for matching absence of query param in a request.
Usage example :
```java
//after this pull request
verify(
getRequestedFor(urlPathEqualTo("without/queryParam"))
.withoutQueryParam("test-param"));
```
It was possible to verify the same even without this method as shown below, but felt counter-intuitive (given there is already a `withoutHeader` method).
```java
//before this pull request
verify(
getRequestedFor(urlPathEqualTo("without/queryParam"))
.withQueryParam("test-param", absent()));
```
- This change was inspired by `withoutHeader` and follows similar pattern.
https://github.com/wiremock/wiremock/blob/2f8b5263d984b3cf212f898e52d4d1b4a52d338a/src/main/java/com/github/tomakehurst/wiremock/matching/RequestPatternBuilder.java#L166
- There is …
=> Add convenient method for matching absence of query param in a request

src/main/java/com/github/tomakehurst/wiremock/client/WireMock.java
In the original code, there was no 'patch' method available in the WireMock class. I added the 'patch' method, which allows creating a mapping from a url-string for HTTP PATCH requests.
(New PR because the [old ](https://github.com/wiremock/wiremock/pull/2222)one was closed due to accidental deletion of the fork.)
- Already existing code for the other methods (Get, Post, Put etc.)
=> Added patch Method with URL in WireMock.java

src/main/java/com/github/tomakehurst/wiremock/core/WireMockApp.java, src/main/java/com/github/tomakehurst/wiremock/stubbing/ServeEvent.java
These are the last imports of `Predicate` and `Function` from Guava. Perhaps they are left for a reason?
#2111
=> ServerEvent: replace Guava predicate and function with STL (refs #2111)

src/main/java/com/github/tomakehurst/wiremock/common/AbstractFileSource.java
As reported on Slack, the current error message in the response is confusing and does not contain a reason when a non-absolute path is passed through API
```
<title>Error 500 com.github.tomakehurst.wiremock.security.NotAuthorisedException: Access to file
../resources/__files/get-users-200.json is not permitted</title>
getting this error when i am trying to connect to my json file.
```
- [ x For new features, there's necessary documentation in this pull request or in a subsequent PR to [wiremock.org](https://github.com/wiremock/wiremock.org)
=> Improve error message in AbstractFileSource#assertFilePathIsUnderRoot()

build.gradle
Finalizes #2190 and also bumps Goole Java Format to a version with Java 21 support
=> Update Spotless to 6.17.0 and Google Java Format to 1.17.0

src/main/java/com/github/tomakehurst/wiremock/extension/responsetemplating/helpers/ParseJsonHelper.java, src/main/java/com/github/tomakehurst/wiremock/stubbing/StubMappingJsonRecorder.java, src/test/java/com/github/tomakehurst/wiremock/extension/responsetemplating/ResponseTemplateTransformerTest.java, src/test/java/com/github/tomakehurst/wiremock/extension/responsetemplating/helpers/ParseJsonHelperTest.java
Parse-Json-Helper for Handlebars should store the parsed json in variable specified and should evaluate to empty string for that section.
For example :
```Handlebars
{{#parseJson 'parsedObj'}}
{"key":"value"}
{{/parseJson}}
```
```Handlebars
{{#assign 'json'}}
{"key":"value"}
{{/assign}}
{{parseJson json 'parsedObj'}}
```
In both scenario, it will parse and store the json `{"key":"value"}` to a variable named `parsedObj`, and evaluate to an empty string for that section.
However, this was not happening when that inner-json was empty like below. Nothing was being stored in the variable, and the section was being evaluated to `{}`
```Handlebars
{{#parseJson 'parsedObj'}}
{}
{{/parseJson}}
```
```Handlebars
{{#assign 'json'}}
{}
{{/assign}}
{{parseJson json 'parsedObj'}}
```
closes #2085
=> Fix ParseJsonHelper not storing parsed result in variable (if any) when json is empty

src/main/java/com/github/tomakehurst/wiremock/matching/MatchesJsonPathPattern.java, src/test/java/com/github/tomakehurst/wiremock/matching/MatchesJsonPathPatternTest.java
When using body patterns and matchesJsonPath with either `$.` or `$[?.` there are several occasions that wiremock throws a warning with the error:
`Warning: JSON path expression {Expression} failed to match document 'null' because of error 'json string can not be null or empty'`
This floods the entire wiremock logs leaving verbose pretty useless.
https://github.com/wiremock/wiremock/issues/1817
=> Fix flood json string can not be null or empty from mapping matcher

.run/Build WireMock.run.xml, .run/Publish to Maven local.run.xml, .run/Run Spotless.run.xml, .run/Run Tests [clean].run.xml, .run/Run Tests.run.xml, CONTRIBUTING.md
Added IntelliJ run configurations for each Gradle commands mentioned in [CONTRIBUTING.md](https://github.com/wiremock/wiremock/blob/master/CONTRIBUTING.md).
#2273
=> Add IntelliJ Run Configurations

src/main/java/com/github/tomakehurst/wiremock/http/trafficlistener/ConsoleNotifyingWiremockNetworkTrafficListener.java, src/main/java/com/github/tomakehurst/wiremock/http/trafficlistener/NotifyingWiremockNetworkTrafficListener.java, src/main/java/com/github/tomakehurst/wiremock/http/trafficlistener/WiremockNetworkTrafficListeners.java, src/test/java/com/github/tomakehurst/wiremock/http/trafficlistener/ConsoleNotifyingWiremockNetworkTrafficListenerTest.java, src/test/java/com/github/tomakehurst/wiremock/http/trafficlistener/NotifyingWiremockNetworkTrafficListenerTest.java
Provides factory methods for creating arbitrary notifying traffic listeners.
https://github.com/wiremock/wiremock/pull/2139#discussion_r1265208536
=> Adds WiremockNetworkTrafficListeners

src/main/java/com/github/tomakehurst/wiremock/extension/ServeEventListener.java, src/main/java/com/github/tomakehurst/wiremock/http/StubRequestHandler.java, src/test/java/com/github/tomakehurst/wiremock/ServeEventListenerExtensionTest.java
Per #2294 - add a synchronous serve event listener callback triggered just before the rendered response is sent to the client.
=> Add a beforeResponseSent serve event listener hook

build.gradle
This solves the vulnerabilites [CVE-2023-26048](https://cve.mitre.org/cgi-bin/cvename.cgi?name=CVE-2023-26048) and [CVE-2023-26049](https://cve.mitre.org/cgi-bin/cvename.cgi?name=CVE-2023-26049). 
It seems that Dependabot hasn't picked it up patch updates to jetty since last year, so I figured I'd make this PR, to solve the above-mentioned vulnerabilities and hopefully get Dependabot to pick it up again.
=> Bump jetty-bom from 11.0.12 to 11.0.15

src/main/java/com/github/tomakehurst/wiremock/http/ProxyResponseRenderer.java, wiremock-webhooks-extension/build.gradle, wiremock-webhooks-extension/src/main/java/org/wiremock/webhooks/Webhooks.java, wiremock-webhooks-extension/src/test/java/functional/WebhooksAcceptanceTest.java
Allows configuring network address rules to permit / deny webhook usage.
Can be used to prevent Webhooks being used to call endpoints in the same private network as the WireMock instance.
=> Allow configuring webhook to forbid target endpoints

src/test/java/com/github/tomakehurst/wiremock/HttpsBrowserProxyAcceptanceTest.java
Fix HttpsBrowserProxyAcceptanceTest
Fix \wiremock\src\test\java\com\github\tomakehurst\wiremock\HttpsBrowserProxyAcceptanceTest.java:143: warning: [removal] getProxies() in ProxyConfiguration has been deprecated and marked for removal
proxyConfig.getProxies().add(httpProxy);
=> Fix HttpsBrowserProxyAcceptanceTest

build.gradle, src/main/java/com/github/tomakehurst/wiremock/admin/AdminRoutes.java, src/main/java/com/github/tomakehurst/wiremock/admin/tasks/OldEditStubMappingTask.java, src/main/resources/swagger/wiremock-admin-api.json, src/main/resources/swagger/wiremock-admin-api.yaml, ui/package-lock.json, ui/package.json
This restores the deprecated edit API so that 2.x WireMock can serve as a client to 3.x, allowing Java 8 users to benefit from 3.x via Testcontainers.
=> Restore old edit task for 2.x backwards compatibility

src/main/java/com/github/tomakehurst/wiremock/verification/diff/Diff.java, src/test/java/com/github/tomakehurst/wiremock/verification/diff/DiffTest.java
The Diff rendering did not handle the `SubExpressionException` thrown in
e.g. `MatchesJsonPathPattern`. This makes it catch that exception and
output it in the diff.
=> Stop returning 500s for unmatched path patterns

src/main/java/com/github/tomakehurst/wiremock/extension/requestfilter/FilterProcessor.java, src/test/java/com/github/tomakehurst/wiremock/RequestFilterV2AcceptanceTest.java
We should only continue to V2 filters if the V1 filters return a ContinueAction.
=> Respect StopAction in V1 Filter

build.gradle, src/main/resources/wiremock/joptsimple/HelpFormatterMessages.properties
Supplying relocated properties to avoid crash when they are read from relocated `joptsimple` when using `wiremock-standalone`.
In Wiremock `3.0.0` and `3.0.1` if you do:
```sh
java -jar wiremock-standalone-3.0.1.jar --help
```
You will get:
```
Exception in thread "main" java.util.MissingResourceException: Can't find resource for bundle java.util.PropertyResourceBundle, key wiremock.joptsimple.BuiltinHelpFormatter.option.header
at java.base/java.util.ResourceBundle.getObject(ResourceBundle.java:564)
at java.base/java.util.ResourceBundle.getString(ResourceBundle.java:521)
at wiremock.joptsimple.internal.Messages.message(Messages.java:42)
at wiremock.joptsimple.BuiltinHelpFormatter.message(BuiltinHelpFormatter.java:558)
at wiremock.joptsimple.BuiltinHelpFormatter.addHeaders(BuiltinHelpFormat …
```
=> fix: avoid crash when printing help in wiremock-standalone

build.gradle, src/test/java/com/github/tomakehurst/wiremock/JvmProxyConfigAcceptanceTest.java, src/test/java/com/github/tomakehurst/wiremock/ResponseTemplatingAcceptanceTest.java, src/test/java/com/github/tomakehurst/wiremock/extension/responsetemplating/helpers/SystemValueHelperTest.java
Resets system properties at end of tests that set them, preventing them affecting other tests
=> Reset system properties at end of test

build.gradle, src/main/resources/swagger/wiremock-admin-api.json, src/main/resources/swagger/wiremock-admin-api.yaml, ui/package.json, wiremock-webhooks-extension/build.gradle
The attempt at fixing the Gradle build to guarantee that the shaded JAR was published in 3.0.1 seems to have failed.
This PR attempts to fix this by disabling the Gradle JAR task completely.
=> Second attempt at fixing shaded webhooks plugin

src/test/java/com/github/tomakehurst/wiremock/StubbingAcceptanceTest.java, src/test/java/com/github/tomakehurst/wiremock/testsupport/WireMockTestClient.java
For methods that do not traditionally accept bodies like GET and DELETE
=> Add tests proving we match on request bodies

src/main/java/com/github/tomakehurst/wiremock/client/HttpAdminClient.java, src/test/java/com/github/tomakehurst/wiremock/client/HttpAdminClientTest.java
Changed admin client to add empty response entity for HTTP requests without body to have proper Content-Length header set in every case. Closes #1729
=> Fix admin requests with empty body to avoid response code 411

src/main/java/com/github/tomakehurst/wiremock/common/NetworkAddressRange.java, src/main/java/com/github/tomakehurst/wiremock/common/NetworkAddressRules.java, src/main/java/com/github/tomakehurst/wiremock/common/NetworkAddressUtils.java
Replace Guava by JDK (Partly)
https://github.com/wiremock/wiremock/issues/2111
=> Replace Guava by JDK (Partly)

src/main/java/com/github/tomakehurst/wiremock/WireMockServer.java, src/main/java/com/github/tomakehurst/wiremock/core/WireMockApp.java, src/main/java/com/github/tomakehurst/wiremock/extension/Extensions.java, src/main/java/com/github/tomakehurst/wiremock/standalone/WireMockServerRunner.java
Prints all loaded extensions in the startup info when running standalone
=> Print loaded extensions at startup

src/main/java/com/github/tomakehurst/wiremock/standalone/CommandLineOptions.java, src/test/java/com/github/tomakehurst/wiremock/standalone/CommandLineOptionsTest.java
This was intended before coming out of beta but got missed in standalone (but done when running programmatically).
There's now no significant performance gain from disabling response templating completely and since this causes a lot of confusion it makes sense to switch it on by default.
=> Enabled local response templating by default in standalone

src/main/java/com/github/tomakehurst/wiremock/core/Options.java, src/main/java/com/github/tomakehurst/wiremock/core/WireMockConfiguration.java, src/main/java/com/github/tomakehurst/wiremock/extension/Extensions.java, src/main/java/com/github/tomakehurst/wiremock/servlet/WarConfiguration.java, src/main/java/com/github/tomakehurst/wiremock/standalone/CommandLineOptions.java, src/test/java/com/github/tomakehurst/wiremock/ExtensionFactoryTest.java, src/test/java/com/github/tomakehurst/wiremock/standalone/CommandLineOptionsTest.java
When working with the WireMock server programmatically it's usually preferable not to scan the classpath for extensions and thus load all extensions into all instances.
However, we nearly always want to scan when running standalone (this is the main use case).
This change adds a startup option to toggle this behaviour with the sensible defaults.
=> Added a startup option to enable/disable extension scanning

src/main/java/com/github/tomakehurst/wiremock/store/files/FileSourceBlobStore.java, src/test/java/com/github/tomakehurst/wiremock/AdminApiTest.java, src/test/java/com/github/tomakehurst/wiremock/store/files/BlobStoreFileSourceTest.java, src/test/java/com/github/tomakehurst/wiremock/testsupport/WireMatchers.java
Fixed bug where absolute rather than relative path was being used for FileSource backed blob store keys, such that attempting to retrieve the file by a listed key produced a not found error
=> Fix FileSource backed blobstore keys bug

src/main/java/org/wiremock/webhooks/Webhooks.java, src/test/java/com/github/tomakehurst/wiremock/WebhooksAcceptanceViaPostServeActionTest.java, src/test/java/com/github/tomakehurst/wiremock/WebhooksAcceptanceViaServeEventTest.java
Otherwise, there's no context to trace it back to a stub
=> Include more info when webhook refusal logged

src/main/java/com/github/tomakehurst/wiremock/matching/MatchesJsonSchemaPattern.java, src/test/java/com/github/tomakehurst/wiremock/matching/MatchesJsonSchemaPatternTest.java, src/test/java/com/github/tomakehurst/wiremock/matching/RequestPatternTest.java
When a path param, header value, query string etc. matcher is
`matchesJsonSchema`, and the schema requires the value to be of type
string, then at present it will be rejected if it has value `123` or
`true` or `false` because it will be considered a number or a boolean.
As these are also possible strings, try validating them as text as well.
=> Fix json string schema rejecting numbers

src/main/java/com/github/tomakehurst/wiremock/jetty11/Jetty11Utils.java, src/test/java/com/github/tomakehurst/wiremock/UriComplianceTest.java, src/test/java/com/github/tomakehurst/wiremock/client/WireMockClientAcceptanceTest.java
[RFC 3986](https://datatracker.ietf.org/doc/html/rfc3986#section-3.3) disallows an empty segment for the _first_ segment of the path, but permits it in any remaining segments.
Jetty 9+ is stricter by default, disallowing _all_ empty segments.
We can revert to the older behaviour, allowing more general mocking, by setting Jetty's `UriCompliance` to `UNSAFE`.
=> Allow empty URI path segments after the first

src/main/resources/swagger/schemas/stub-mapping.yaml
I added the `BEFORE_RESPONSE_SENT` enum value to the stub-mapping schema as a possible serveEventListener request phase.
The related PR that added support for this was merged back in August, so it was missing from the schema.
- https://github.com/wiremock/wiremock/issues/2294
- https://github.com/wiremock/wiremock/pull/2295
=> Add BEFORE_RESPONSE_SENT request phase to the stub-mapping schema

src/main/java/com/github/tomakehurst/wiremock/junit5/WireMockExtension.java
Turned the referral link into an actual link so people can open it from their IDE.
=> doc: turn reference link into actual link

src/main/java/com/github/tomakehurst/wiremock/http/ssl/CompositeTrustManager.java, src/test/java/com/github/tomakehurst/wiremock/CustomMatchingAcceptanceTest.java, src/test/java/com/github/tomakehurst/wiremock/HttpsBrowserProxyAcceptanceTest.java, src/test/java/com/github/tomakehurst/wiremock/PortNumberTest.java, src/test/java/com/github/tomakehurst/wiremock/ResponseDefinitionTransformerAcceptanceTest.java, src/test/java/com/github/tomakehurst/wiremock/ResponseDefinitionTransformerV2AcceptanceTest.java, src/test/java/com/github/tomakehurst/wiremock/ScenarioAcceptanceTest.java, src/test/java/com/github/tomakehurst/wiremock/VerificationAcceptanceTest.java, src/test/java/com/github/tomakehurst/wiremock/WireMockJUnitRuleTest.java, src/test/java/com/github/tomakehurst/wiremock/common/DateTimeOffsetTest.java, src/test/java/com/github/tomakehurst/wiremock/common/ServletContextFileSourceTest.java, src/test/java/com/github/tomakehurst/wiremock/http/ContentTypeHeaderTest.java, src/test/java/com/github/tomakehurst/wiremock/http/HttpHeaderTest.java, src/test/java/com/github/tomakehurst/wiremock/http/ssl/CompositeTrustManagerTest.java, src/test/java/com/github/tomakehurst/wiremock/matching/MatchesJsonPathPatternTest.java, src/test/java/com/github/tomakehurst/wiremock/recording/SnapshotOutputFormatterTest.java, src/test/java/com/github/tomakehurst/wiremock/standalone/CommandLineOptionsTest.java, src/test/java/com/github/tomakehurst/wiremock/standalone/ProxySettingsTest.java, src/test/java/ignored/Examples.java
Replaces basic statement lambdas with expression ones.
=> feat: use expression lambdas over statement lambdas

CONTRIBUTING.md
Closes #2427 from @SimonVerhoeven
=> Update the co-maintainer policy beyond WireMock 3

src/main/java/com/github/tomakehurst/wiremock/admin/Conversions.java, src/main/java/com/github/tomakehurst/wiremock/common/Dates.java, src/test/java/com/github/tomakehurst/wiremock/AdminApiTest.java, src/test/java/com/github/tomakehurst/wiremock/admin/ConversionsTest.java, src/test/java/com/github/tomakehurst/wiremock/common/DateTimeOffsetTest.java, src/test/java/com/github/tomakehurst/wiremock/common/DatesTest.java, src/test/java/com/github/tomakehurst/wiremock/extension/responsetemplating/helpers/HandlebarsCurrentDateHelperTest.java, src/test/java/com/github/tomakehurst/wiremock/extension/responsetemplating/helpers/ParseDateHelperTest.java
The currently used Jackson ISO8601 class is deprecated
- TODO
=> Do not use deprecated jackson iso8601 class

src/main/java/com/github/tomakehurst/wiremock/WireMockServer.java, src/main/java/com/github/tomakehurst/wiremock/admin/AdminRoutes.java, src/main/java/com/github/tomakehurst/wiremock/common/AbstractFileSource.java, src/main/java/com/github/tomakehurst/wiremock/common/ClasspathFileSource.java, src/main/java/com/github/tomakehurst/wiremock/junit5/WireMockExtension.java, src/main/java/com/github/tomakehurst/wiremock/matching/MatchesJsonPathPattern.java, src/main/java/com/github/tomakehurst/wiremock/matching/RequestPattern.java
Replaced `Optional.orElse()` calls with `Optional.orElseGet()` where it was applicable, so that dynamic values are evaluated lazily, and only when needed.
#2442
=> Replace Optional.orElse() calls with Optional.orElseGet()

src/main/java/com/github/tomakehurst/wiremock/admin/AdminRoutes.java, src/main/java/com/github/tomakehurst/wiremock/common/Exceptions.java, src/main/java/com/github/tomakehurst/wiremock/http/HttpClientFactory.java, src/main/java/com/github/tomakehurst/wiremock/http/QueryParameter.java, src/main/java/com/github/tomakehurst/wiremock/http/ResponseDefinition.java, src/main/java/com/github/tomakehurst/wiremock/junit5/WireMockExtension.java, src/main/java/com/github/tomakehurst/wiremock/recording/SnapshotRecordResult.java, src/main/java/com/github/tomakehurst/wiremock/verification/FindRequestsResult.java, src/test/java/com/github/tomakehurst/wiremock/AdminApiTest.java, src/test/java/com/github/tomakehurst/wiremock/DateHeaderAcceptanceTest.java, src/test/java/com/github/tomakehurst/wiremock/StubLifecycleListenerAcceptanceTest.java, src/test/java/com/github/tomakehurst/wiremock/http/ProxyResponseRendererTest.java, src/test/java/com/github/tomakehurst/wiremock/http/ssl/CertificateGeneratingX509ExtendedKeyManagerChooseEngineServerAliasDefaultsTest.java, src/test/java/com/github/tomakehurst/wiremock/http/ssl/CertificateGeneratingX509ExtendedKeyManagerChooseServerAliasDefaultsTest.java, src/test/java/com/github/tomakehurst/wiremock/matching/EqualToXmlPatternTest.java, src/test/java/com/github/tomakehurst/wiremock/matching/MatchesXPathPatternTest.java, src/test/java/com/github/tomakehurst/wiremock/matching/MultipartValuePatternBuilderTest.java, src/test/java/com/github/tomakehurst/wiremock/verification/diff/PlainTextDiffRendererTest.java
Inferred explicit type arguments where possible
- TODO
=> chore: infer explicit type arguments where possible

src/main/java/com/github/tomakehurst/wiremock/common/DateTimeTruncation.java
A missing null check in `DateTimeTruncation#truncate` results in null pointer exceptions whenever the user uses a matcher which includes `truncateActual`. This largely makes `truncateActual` unusable since it breaks functionality, especially when the mapping including `truncateActual` is added last.
Fixes https://github.com/wiremock/wiremock/issues/2466
=> Add null check for actual date/time truncation (#2466)

src/test/java/com/github/tomakehurst/wiremock/AdminApiTest.java
Introduces a slight delay in the flakey test to hopefully avoid this in the future.
=> fix: introduce a slight delay given the 2-3 results is slightly flakey

src/main/java/com/github/tomakehurst/wiremock/common/UniqueFilenameGenerator.java, src/main/java/com/github/tomakehurst/wiremock/extension/responsetemplating/helpers/JsonData.java, src/main/java/com/github/tomakehurst/wiremock/extension/responsetemplating/helpers/ParseJsonHelper.java, src/test/java/com/github/tomakehurst/wiremock/client/ResponseDefinitionBuilderTest.java, src/test/java/com/github/tomakehurst/wiremock/matching/MultipartValuePatternBuilderTest.java, src/test/java/com/github/tomakehurst/wiremock/matching/RequestPatternBuilderTest.java
Cleaned up some Arrays.asList that were never adapted/only one arguments, and removed them in case they weren't used at all.
=> chore: use List.of where possible if only one argument is passed

src/main/java/com/github/tomakehurst/wiremock/verification/diff/Diff.java
We tried fixing issue #2047. To accomplish this, we first set out to refactor the Diff class. We extracted methods for better readability. Unfortunately we did not manage to fix the issue.
Issue #2047
=> Refactor: split getLines method of Diff class

src/main/resources/META-INF/services/wiremock.org.slf4j.spi.SLF4JServiceProvider
I tested it locally in a Maven project.
I had the warning before the fix, not after.
I'm not sure how to perform unit testing on it, though...
=> Fixed #2415 Gradle replaces SLF4J-API 1.7.36 with 2.0.7, causing warning in the log

build.gradle, src/main/java/com/github/tomakehurst/wiremock/common/DefaultNetworkAddressRules.java, src/main/java/com/github/tomakehurst/wiremock/common/NetworkAddressRules.java, src/main/java/com/github/tomakehurst/wiremock/core/WireMockConfiguration.java, src/main/java/com/github/tomakehurst/wiremock/http/HttpClientFactory.java, src/main/java/com/github/tomakehurst/wiremock/servlet/WarConfiguration.java, src/main/java/com/github/tomakehurst/wiremock/standalone/CommandLineOptions.java, src/main/resources/swagger/wiremock-admin-api.json, src/main/resources/swagger/wiremock-admin-api.yaml, src/test/java/com/github/tomakehurst/wiremock/ProxyAcceptanceTest.java, src/test/java/com/github/tomakehurst/wiremock/WebhooksAcceptanceViaPostServeActionTest.java, src/test/java/com/github/tomakehurst/wiremock/WebhooksAcceptanceViaServeEventTest.java, src/test/java/com/github/tomakehurst/wiremock/common/NetworkAddressRulesTest.java, src/test/java/com/github/tomakehurst/wiremock/http/HttpClientFactoryCertificateVerificationTest.java, src/test/java/com/github/tomakehurst/wiremock/http/NetworkAddressRulesAdheringDnsResolverTest.java, src/test/java/com/github/tomakehurst/wiremock/http/ProxyResponseRendererTest.java, ui/package.json
3.3.0 accidentally introduced a breaking change when `NetworkAddressRules` was renamed to `DefaultNetworkAddressRules`.
This change moves the static/builder methods etc. back up to the `NetworkAddressRules` interface.
=> Fix network address rules breaking change

src/main/java/com/github/tomakehurst/wiremock/standalone/CommandLineOptions.java
This is a very simple PR to add the version number to the output when wiremock starts. I added it to the `CommandlineOptions` `toString()` method so the version is output regardless of whether the banner is enabled or not.  I thought this might be better than adding the code in multiple places in the startup process. As far as I could tell there are no tests that validate the output of the startup process. 
Output looks like this:
```
██     ██ ██ ██████  ███████ ███    ███  ██████   ██████ ██   ██ 
██     ██ ██ ██   ██ ██      ████  ████ ██    ██ ██      ██  ██  
██  █  ██ ██ ██████  █████   ██ ████ ██ ██    ██ ██      █████   
██ ███ ██ ██ ██   ██ ██      ██  ██  ██ ██    ██ ██      ██  ██  
███ ███  ██ ██   ██ ███████ ██      ██  ██████   ██████ ██   ██ …
```
=> Add the version number to the output when wiremock starts

src/main/resources/swagger/wiremock-admin-api.json, src/main/resources/swagger/wiremock-admin-api.yaml
Add `operationId` values to the swagger/openApi json & yml documents.
From the[ swagger paths-and-operations reference:](https://swagger.io/docs/specification/paths-and-operations/)
> Some common use cases for operationId are:
> 
>  * Some code generators use this value to name the corresponding methods in code.
>  * Links can refer to the linked operations by operationId.
=> Add operationId to openApi/swagger documents

src/main/java/com/github/tomakehurst/wiremock/http/ResponseDefinition.java, src/test/java/com/github/tomakehurst/wiremock/http/ResponseDefinitionTest.java
Added safe programming when we instantiate `ResponseDefinition` class and use `getProxyUrl()` method when  `originalRequest` field is set to null
- Issue reported: [Issue-2489](https://github.com/wiremock/wiremock/issues/2489)
=> Fix `NullPointerException` in `ResponseDefinition.getProxyUrl()`

src/main/java/com/github/tomakehurst/wiremock/common/url/PathTemplate.java, src/test/java/com/github/tomakehurst/wiremock/common/url/PathTemplateTest.java
Some specifications (e.g. [OpenAPI v3](https://spec.openapis.org/oas/v3.0.3#path-templating-matching)) require choosing a path template by how specific they are.
Exposing the number of parameters allows sorting a set of templates by how specific they are.
=> Expose numberOfParameters on PathTemplate

src/main/java/com/github/tomakehurst/wiremock/store/InMemoryRequestJournalStore.java
Under heavy load it's possible that `serveEvents.get()` is called with an `UUID` that doesn't exist anymore in the `Map`. The reason for this is that the spliatator (required for `stream()`) of the `ConcurrentLinkedDeque` is weakly consistent. This means that it's not guaranteed that an element that is currently processed in a `Stream` still exists in the collection. So under heavy load it may happen, that one thread reads an element of the `ConcurrentLinkedDeque`. Then this thread gets paused and another thread gets activated which than completely runs the `remove` method of the `InMemoryRequestJournalStore`. Now the first thread gets activated again and calls the `get` method of the `serveEvents` with an `UUID` that doesn't exist anymore in the `Map` which results in a `null` value. As …
=> Do not return null objects in getAll of the InMemoryRequestJournalStore

src/main/java/com/github/tomakehurst/wiremock/client/WireMock.java, src/main/java/com/github/tomakehurst/wiremock/http/RequestMethod.java, src/test/java/com/github/tomakehurst/wiremock/client/WireMockClientAcceptanceTest.java, src/test/java/com/github/tomakehurst/wiremock/testsupport/WireMockTestClient.java
Closes #2414 . This PR adds a GET_OR_HEAD method. This stub method could be used for both get as well as head Http method. The response and http header information is returned accordingly
=> Added GET_OR_HEAD method.

src/main/java/com/github/tomakehurst/wiremock/matching/RequestPatternBuilder.java, src/test/java/com/github/tomakehurst/wiremock/matching/RequestPatternBuilderTest.java
In order to be able to customize `url` with every kind of `UrlPattern` from a `RequestPattern` using the `like` function, it would be useful if `RequestPatternBuilder` allows to do so.
I added test only for `urlPath` because I did not judge that it was necessary for other (since it wil be exactly the same and lead to a lot of duplicated code, but feel free to tell me otherwise.
- Related issue: https://github.com/wiremock/wiremock/issues/2531
=> Adding build function for all kind of UrlPattern in RequestPatternBuilder

src/main/java/com/github/tomakehurst/wiremock/junit5/WireMockExtension.java, src/test/java/com/github/tomakehurst/wiremock/ExtensionFactoryTest.java, src/test/java/com/github/tomakehurst/wiremock/junit5/JUnitJupiterExtensionExtensionScanningEnabledDeclarativeTest.java, src/test/java/com/github/tomakehurst/wiremock/junit5/JUnitJupiterExtensionExtensionScanningEnabledProgrammaticTest.java, src/test/java/com/github/tomakehurst/wiremock/junit5/MockExtension.java, src/test/resources/META-INF/services/com.github.tomakehurst.wiremock.extension.Extension
When using extensions that utilize service loading (e.g. [wiremock/wiremock-graphql-extension](https://github.com/wiremock/wiremock-graphql-extension)) it would be preferable to use the declarative option to enable extension scanning, rather than being forced to use the programmatic approach to manually define extensions.
- https://github.com/wiremock/wiremock.org/pull/242
=> Add extensionScanningEnabled option to @WireMockTest.

src/main/java/com/github/tomakehurst/wiremock/extension/ExtensionDeclarations.java, src/test/java/com/github/tomakehurst/wiremock/extension/webhooks/WebhooksRegistrationTest.java
Closes #2528.
This PR removes externally added webhooks as extensions and logs a warning that passing webhook class name is no longer required and may lead to compatibility issues in future.
Supersedes #2550
=> Remove and log warning before loading webhooks

src/main/java/com/github/tomakehurst/wiremock/extension/responsetemplating/helpers/HandlebarsJsonPathHelper.java, src/test/java/com/github/tomakehurst/wiremock/extension/responsetemplating/helpers/HandlebarsJsonPathHelperTest.java
Instead of having `jsonpath` in handlebars throwing an `IllegalArgumentException`, empty bodies are handled the same way as `null` bodies: as empty string.
#2546
=> correct handling of empty request body with Handlebars (#2546)

src/main/java/com/github/tomakehurst/wiremock/matching/MatchesJsonSchemaPattern.java, src/main/java/com/github/tomakehurst/wiremock/matching/StringValuePatternJsonDeserializer.java, src/test/java/com/github/tomakehurst/wiremock/matching/MatchesJsonSchemaPatternTest.java
https://wiremock.org/docs/request-matching/#json-schema shows an example of using the `matchesJsonSchema` with an escaped json string:
```json
{
"request" : {
"urlPath" : "/schema-match",
"method" : "POST",
"bodyPatterns" : [ {
"matchesJsonSchema" : "{\n  \"type\": \"object\",\n  \"required\": [\n    \"name\"\n  ],\n  \"properties\": {\n    \"name\": {\n      \"type\": \"string\"\n    },\n    \"tag\": {\n      \"type\": \"string\"\n    }\n  }\n}",
"schemaVersion" : "V202012"
} ]
},
"response" : {
"status" : 200
}
}
```
This PR would allow us to supply a json object (similar to `equalToJson`). For example:
```json
{
"request" : {
"urlPath" : "/schema-match",
"method" : "POST",
"bodyPatterns" : [ {
"matchesJsonSchema" : {
"type": "object",
"required": [
"name"
],
"properties": {
"name": { …
```
=> Allow matchesJsonSchema to be supplied as a json object.

src/main/java/com/github/tomakehurst/wiremock/common/Json.java, src/main/java/com/github/tomakehurst/wiremock/standalone/JsonFileMappingsSource.java
Hi, please look at this simple PR.
Description: Configuration file content passed as byte array to ObjectMapper readValue method so that it can skip BOM character.
=> Parsing config files with BOM character

src/main/java/com/github/tomakehurst/wiremock/extension/Extensions.java, src/main/java/com/github/tomakehurst/wiremock/extension/responsetemplating/LazyTemplateEngine.java, src/main/java/com/github/tomakehurst/wiremock/extension/responsetemplating/TemplateEngine.java, src/main/java/com/github/tomakehurst/wiremock/http/client/LazyHttpClient.java, src/main/java/com/github/tomakehurst/wiremock/http/client/LazyHttpClientFactory.java, src/main/java/org/wiremock/webhooks/Webhooks.java
Draft for issue in which ExtensionFactories are supplied a null TemplateEngine, HttpClientFactory, and DefaultHttpClient from Extensions. 
- closes https://github.com/wiremock/wiremock/issues/2562
=> Supply lazy TemplateEngine, HttpClientFactory, and DefaultHttpClient.

src/main/java/com/github/tomakehurst/wiremock/common/Json.java, src/main/java/com/github/tomakehurst/wiremock/http/Body.java, src/test/java/com/github/tomakehurst/wiremock/StandaloneAcceptanceTest.java, src/test/java/com/github/tomakehurst/wiremock/http/BodyTest.java, src/test/java/com/github/tomakehurst/wiremock/stubbing/JsonTest.java
This pull request fixes json-body not escaping special characters.
When Response-Body object is constructed from JSON file, it is stored as byte-array (plain text). So, the escape sequences are never replaced with their correct representation. They remain as is.
This creates problem when the JSON has special meaning after escaping. Such as the issue reported in : https://github.com/wiremock/wiremock/issues/2547
- `JsonNode` of Jackson offers a method `asText()` which return the actual value of `ValueNode`. This will return a escaped string for a `TextNode`
- [Javadoc for `JsonNode#asText()`](https://javadoc.io/doc/com.fasterxml.jackson.core/jackson-databind/2.10.0/com/fasterxml/jackson/databind/JsonNode.html#asText--)
- [Difference Between asText() and toString() in …
=> Fix json-body not escaping special characters

src/main/java/com/github/tomakehurst/wiremock/http/HttpClientFactory.java, src/main/java/com/github/tomakehurst/wiremock/http/client/ApacheHttpClientFactory.java, src/test/java/com/github/tomakehurst/wiremock/client/HttpAdminClientTest.java, src/test/java/com/github/tomakehurst/wiremock/client/SingleConnectionServer.java, src/test/java/com/github/tomakehurst/wiremock/http/HttpClientFactoryCertificateVerificationTest.java, src/test/java/com/github/tomakehurst/wiremock/http/ProxyResponseRendererTest.java
We are using WireMock for our integration tests. In one of our projects the test suite does ~ 29000 requests to the WireMock for stubbing, verifying, resetting ... requests. With the current implementation for each and every request a new TCP connection is created. This causes a lot of useless overhead. On powerful systems the test suite takes just 1 minute and a few seconds and it looks like we now reached a limit where some kind of ratelimiting (haven't yet found the reason for) on the network layer blocks the creation of new TCP connections to the WireMock. If I enable the connection reuse everything works as expected.
I just had a look through the history and it looks like disabling the connection reuse was introduced due to a bug that occurs when the WireMock server is running in …
=> Disable connection reuse only for proxy clients not for the admin client

src/main/java/com/github/tomakehurst/wiremock/stubbing/Scenario.java
Update the error message in 'setState' method of 'Scenario' class to contain the name of the scenario instead of 'my-scenario'. This makes the error message more informative and useful.
- TODO
=> Improve Scenario error message for unsupported state

src/main/java/com/github/tomakehurst/wiremock/matching/AbstractDateTimeMatchResult.java, src/test/java/com/github/tomakehurst/wiremock/matching/AfterDateTimePatternTest.java, src/test/java/com/github/tomakehurst/wiremock/matching/BeforeDateTimePatternTest.java, src/test/java/com/github/tomakehurst/wiremock/matching/EqualToDateTimePatternTest.java, src/test/java/com/github/tomakehurst/wiremock/matching/MultiValuePatternTest.java
Right now, multiple value matching for date/time values is broken for actual-to-expected differences smaller than a year.
For instance, given the matchers below:
```
"request": {
"urlPath": "/resource",
"queryParameters": {
"datetime" : {
"hasExactly" : [
{
"equalToDateTime": "now",
"truncateActual": "first hour of day",
"truncateExpected": "first hour of day"
},
{
"equalToDateTime": "now +10 days",
"truncateActual": "first hour of day",
"truncateExpected": "first hour of day"
}
]
}
}
}
```
Then (assuming the current date is `2023-12-20`) a GET request to the following URI should be matched:
`/resource?datetime=2023-12-20T00:00:00.000Z&datetime=2023-12-30T00:00:00.000Z`
Instead, we get a "request was not matched" message.
The root cause is in the granularity of the …
=> Generalize function calculating normalized distance between date/time values

src/main/java/com/github/tomakehurst/wiremock/common/Json.java
In PR [2588](https://github.com/wiremock/wiremock/pull/2588/files) the ObjectMapper was changed to not normalise BigDecimal values. This fixed the undesirable behavior of values such as this - {"float": 2.0} being changed to this - {"float": 2}. This PR maintains that behaviour.
To accomplish this a JsonNodeFactory was added to the ObjectMapper in the following way:
```java
objectMapper.setNodeFactory(new JsonNodeFactory(true));
```
The `true` parameter tells the object mapper to not normalise BigDecimal values.  This issue on the `jackson-databind` project explains that they will be deprecating the `JsonNodeFactory` method in favour of configuring the object mapper via a `JsonNodeFeature` - https://github.com/FasterXML/jackson-databind/issues/3651
This PR updates to configuring the …
=> Refactor JsonNodeFactory(true) in favour of a JsonNodeFeature

src/main/java/com/github/tomakehurst/wiremock/matching/EqualToJsonPattern.java, src/main/java/com/github/tomakehurst/wiremock/matching/NormalisedNumberComparator.java, src/test/java/com/github/tomakehurst/wiremock/MappingsAcceptanceTest.java, src/test/java/com/github/tomakehurst/wiremock/matching/MatchesJsonPathPatternTest.java, src/test/java/com/github/tomakehurst/wiremock/testsupport/MappingJsonSamples.java
In PR [2588](https://github.com/wiremock/wiremock/pull/2588/files) we set our ObjectMapper to not normalise BigDecimal values.  This fixed the undesirable behavior of values such as this - `{"float": 2.0}` being changed to this - `{"float": 2}`.  This PR maintains that behaviour.   
Because decimal values are no longer being normalised, this means we have an issue with the json Diff not seeing numbers like `1.2` and `1.2000` as the same values. This change adds a new `NumberComparator` to the Diff to normalise the BigDecimal values so we can continue to compare those values in the same way as we used to in versions prior to `3.4.0`.
fixes #2610
=> [FIX] Add a custom number comparator to the Json Diff to trim trailing zeros

src/main/java/com/github/tomakehurst/wiremock/matching/MatchResult.java, src/main/java/com/github/tomakehurst/wiremock/matching/MatchesJsonPathPattern.java, src/main/java/com/github/tomakehurst/wiremock/stubbing/ServeEvent.java, src/main/java/com/github/tomakehurst/wiremock/stubbing/SubEvent.java, src/test/java/com/github/tomakehurst/wiremock/SubServeEventsAcceptanceTest.java, src/test/java/com/github/tomakehurst/wiremock/matching/MatchesJsonPathPatternTest.java
To avoid resource exhaustion during matching per https://github.com/wiremock/wiremock/issues/2606
=> Fixes #2606 - avoid appending identical sub-events repeatedly

src/main/java/com/github/tomakehurst/wiremock/common/Json.java, src/main/java/com/github/tomakehurst/wiremock/http/Body.java, src/test/java/com/github/tomakehurst/wiremock/StandaloneAcceptanceTest.java, src/test/java/com/github/tomakehurst/wiremock/http/BodyTest.java, src/test/java/com/github/tomakehurst/wiremock/stubbing/JsonTest.java
This produces badly formed JSON where there are escaped quotes present. Given the potential for other undiscovered edge-cases, we'll release a patch version without this fix for now.
=> Revert "Fix json-body not escaped properly" 

src/main/java/com/github/tomakehurst/wiremock/common/xml/XmlNode.java
Using InheritableThreadLocal means that entity can be accessible by some threads at the same time, so access should be synced or entity should be read-only. In the XmlDocument class there is a not synced write operation in xPath object that is InheritableThreadLocal.
I encountered the following problem. A am running a lot of requests to wiremock and mappings have different namespaces. And sometimes (random and rarely) at the evaluating xPath expression time (XmlDocument.findNodes() method) another thread (parent or child) is changing namespace context of current xPath object and error "Prefix must resolve to a namespace" appears, but namespaces in mapping file are correct. So I suggest to use simple ThreadLocal here. This change fixed my problem.
=> Fixed xPath concurrency issues

src/main/java/com/github/tomakehurst/wiremock/extension/responsetemplating/helpers/SystemValueHelper.java, src/test/java/com/github/tomakehurst/wiremock/extension/responsetemplating/helpers/SystemValueHelperTest.java
Allow an optional default value to be supplied when using the systemValue helper.
An example where this might be useful is having a safe default to proxy to a dev environment without requiring the environment variable to be set. It is also helpful to demonstrate what an appropriate value for the environment variable should be.
```json
{
"request": {
"method": "ANY",
"urlPattern": "/"
},
"response": {
"proxyBaseUrl": "{{systemValue type='ENVIRONMENT' key='WIREMOCK_PROXY_BASE_URL', default='https://dev.example.com'}}",
"transformers": [
"response-template"
]
}
}
```
- https://github.com/wiremock/wiremock.org/pull/262
=> Optional default for SystemValueHelper.

src/main/java/com/github/tomakehurst/wiremock/client/ResponseDefinitionBuilder.java, src/main/java/com/github/tomakehurst/wiremock/extension/responsetemplating/ResponseTemplateTransformer.java, src/main/java/com/github/tomakehurst/wiremock/http/ProxyResponseRenderer.java, src/main/java/com/github/tomakehurst/wiremock/http/ResponseDefinition.java, src/main/resources/swagger/schemas/response-definition.yaml, src/main/resources/swagger/wiremock-admin-api.json, src/test/java/com/github/tomakehurst/wiremock/client/ResponseDefinitionBuilderTest.java, src/test/java/com/github/tomakehurst/wiremock/http/ProxyResponseRendererTest.java, src/test/java/com/github/tomakehurst/wiremock/http/StubResponseRendererTest.java, src/test/java/com/github/tomakehurst/wiremock/stubbing/ResponseDefinitionTest.java
Along with the ability to add `additionalProxyRequestHeaders`, it may be beneficial to `removeProxyRequestHeaders`. For example, if you want to remove the existing value(s) of a header before additional are added or if there are headers you don't want sent downstream.
- https://github.com/wiremock/wiremock.org/pull/268
=> Allow removal of headers from a proxied request.

src/main/java/com/github/tomakehurst/wiremock/core/Options.java, src/main/java/com/github/tomakehurst/wiremock/core/WireMockConfiguration.java, src/main/java/com/github/tomakehurst/wiremock/jetty/JettyHttpServer.java, src/main/java/com/github/tomakehurst/wiremock/jetty11/Jetty11HttpServer.java, src/main/java/com/github/tomakehurst/wiremock/jetty11/SslContexts.java, src/main/java/com/github/tomakehurst/wiremock/servlet/WarConfiguration.java, src/main/java/com/github/tomakehurst/wiremock/standalone/CommandLineOptions.java, src/test/java/com/github/tomakehurst/wiremock/jetty11/Http2AcceptanceTest.java, src/test/java/com/github/tomakehurst/wiremock/jetty11/Http2DisabledAcceptanceTest.java, wiremock-jetty12/src/main/java/com/github/tomakehurst/wiremock/jetty12/Jetty12HttpServer.java, wiremock-jetty12/src/test/java/com/github/tomakehurst/wiremock/jetty12/Http2AcceptanceTest.java, wiremock-jetty12/src/test/java/com/github/tomakehurst/wiremock/jetty12/Http2DisabledAcceptanceTest.java
Support enabling/disabling of HTTP/2 separate on plain text and TLS.
It remains enabled by default for both.
=> Added toggles for plain text and TLS HTTP/2

build.gradle
Fix publications by excluding testFixturesApi components. Those cause an invalid POM file being generated:
```
[WARNING] The POM for org.wiremock:wiremock:jar:3.5.1 is invalid, transitive dependencies (if any) will not be available: 3 problems were encountered while building the effective model for org.wiremock:wiremock:3.5.1
```
Verified locally with `./gradlew localRelease`
Closes https://github.com/wiremock/wiremock/issues/2660
=> Fix publications by excluding testFixturesApi components

src/test/java/benchmarks/HandlebarsOptimizedTemplateBenchmark.java, src/test/java/com/github/tomakehurst/wiremock/extension/responsetemplating/ResponseTemplateTransformerTest.java
It's a benchmark so it should be in benchmarks
=> Move template benchmark into benchmarks

src/main/java/com/github/tomakehurst/wiremock/common/AbstractFileSource.java
Specify which directory the file must be within when rejecting it
because it is not in that directory.
=> Make it easier to fix issue with file's path

src/main/java/com/github/tomakehurst/wiremock/matching/MatchResult.java
Currently partial matches cannot have sub events. This allows them to.
=> Support sub events on partial matchers

src/main/java/com/github/tomakehurst/wiremock/core/WireMockApp.java, src/main/java/com/github/tomakehurst/wiremock/verification/NearMissCalculator.java, src/test/java/com/github/tomakehurst/wiremock/verification/NearMissCalculatorTest.java
Currently the near miss calculator does not apply custom matchers; instead it assumes they did not match and applies a distance of 1.
This means that just having a custom matcher immediately distorts the distance dramatically, even if it matches, but also if it is a partial match (distance < 1).
=> Near miss takes custom matchers into account

src/main/java/com/github/tomakehurst/wiremock/matching/RequestPattern.java, src/main/java/com/github/tomakehurst/wiremock/verification/AbstractRequestJournal.java
I can't think of any reason why this wouldn't?
=> removeEventsMatching supports custom matchers

build.gradle
This PR is a fix for #2688 where `commons-fileupload` was not loading `commons-io` as a transitive dependency.  Now we have removed our dependency on `commons-io` we can now allow `commons-fileupload` to pull it in as a transitive dependency
https://github.com/wiremock/wiremock/issues/2688
- TODO
=> Allow commons-fileupload to load commons-io as a transitive dependency

src/main/java/com/github/tomakehurst/wiremock/extension/responsetemplating/helpers/MathsHelper.java, src/test/java/com/github/tomakehurst/wiremock/extension/responsetemplating/helpers/MathsHelperTest.java
Currently, when the result of the handlebars math helper is a negative number less than `java.lang.Integer.MIN_VALUE`, it's incorrectly coerced into a `java.lang.Integer`. This PR fixes that.
=> fix: handlebars math helper handles large negative integers

src/main/java/com/github/tomakehurst/wiremock/junit5/WireMockExtension.java
This is useful when subclasses want to use annotations to help configure them.
Prior to the addition of the upstream WireMockExtension, I had a WireMockExtension (same class name) which allowed users to set transformers via an annotation.
In other subclasses, I used the ExtensionContext to backup/restore state, such that if a test wanted to modify the settings, it would be restored to the defaults for that class.
=> Allow subclasses of WireMockExtension to get the ExtensionContext

src/main/java/com/github/tomakehurst/wiremock/common/Urls.java, src/test/java/com/github/tomakehurst/wiremock/common/UrlsTest.java
According to the documentation on request matching, Wiremock should be able to handle offsets in date/time query parameter values in all of the following three cases:
```
/resource?date=2021-06-24T13:40:27+01:00
/resource?date=2021-06-24T13:40:27Z
/resource?date=2021-06-24T13:40:27-01:00
```
In other words, it should be able to parse a date/time query parameter value with an offset ahead of UTC (`+HH:mm`), an offset of zero (`Z`) and an offset behind UTC (`-HH:mm`).
Right now only the last two work. Offsets ahead of UTC found in query parameters cannot be matched due to the `+` also having semantics in URL encoding. That is, in URL encoded strings `+` represents a space and as a result `2021-06-24T13:40:27+01:00` is decoded to `2021-06-24T13:40:27 01:00` which results in a …
=> Fix parsing of date/time query parameter values with an offset ahead of UTC

src/main/java/com/github/tomakehurst/wiremock/servlet/WireMockHttpServletRequestAdapter.java, src/test/java/com/github/tomakehurst/wiremock/MultipartBodyMatchingAcceptanceTest.java
When testing SOAP-Requests with MTOM enabled the Standard SAAJ Implementation sends a HTTP-Header `Content-Type: Multipart/Related; boundary=...`. This leads to a Failure on Wiremock Multipart Behaviour because it only has checked against lowercased `multipart/`.
Instead it checks against a case-insensitive Regular-Expression `^multipart/.*`.
Can this be also merged to the Java-8 related Versions?
=> Content-Type Header for Multipart-Requests should be checked case-insensitive

src/main/java/com/github/tomakehurst/wiremock/extension/responsetemplating/helpers/ArrayAddHelper.java, src/main/java/com/github/tomakehurst/wiremock/extension/responsetemplating/helpers/ArrayRemoveHelper.java, src/test/java/com/github/tomakehurst/wiremock/CustomMatchingAcceptanceTest.java, src/test/java/com/github/tomakehurst/wiremock/extension/responsetemplating/ResponseTemplateTransformerTest.java, src/test/java/com/github/tomakehurst/wiremock/extension/responsetemplating/helpers/ValHelperTest.java, src/test/java/com/github/tomakehurst/wiremock/store/InMemoryObjectStoreTest.java, src/test/java/com/github/tomakehurst/wiremock/store/files/FileSourceJsonObjectStoreTest.java
This PR adds new tests for the new helpers going into the `3.6.0` release along with padding out the tests for the new Stores implemetations.
The only new bit of functionality going into this PR is for the new `arrayAdd` and `arrayRemove` helpers where we now check for out of bounds `position` parameters
Docs will be updated in a separate PR
=> Additional tests for new helpers and Store implementations

src/main/java/com/github/tomakehurst/wiremock/stubbing/AbstractStubMappings.java, src/test/java/com/github/tomakehurst/wiremock/ResponseTemplatingAcceptanceTest.java, src/test/java/com/github/tomakehurst/wiremock/StubbingAcceptanceTest.java, src/test/java/com/github/tomakehurst/wiremock/client/HttpAdminClientTest.java
This pull request implements the fix outlined in [this issue](https://github.com/wiremock/wiremock/issues/2734) to prevent the creation of multiple stub mappings with the same ID.
https://github.com/wiremock/wiremock/issues/2734
=> Prevent creating multiple stub mappings with the same ID

src/main/java/com/github/tomakehurst/wiremock/verification/diff/Diff.java, src/test/java/com/github/tomakehurst/wiremock/verification/diff/PlainTextDiffRendererTest.java, src/test/resources/not-found-diff-sample_no_path_parameter_message.txt
Currently, when a request is not matched, its diff report always shows all path parameters matchers as not matching, regardless of if they actually were matched or not. This PR fixes that bug.
=> fix: stop showing path parameter non match message incorrectly.

src/main/java/com/github/tomakehurst/wiremock/admin/AdminRoutes.java, src/main/java/com/github/tomakehurst/wiremock/admin/tasks/GetStubFileTask.java, src/test/java/com/github/tomakehurst/wiremock/AdminApiTest.java
=> feat: add admin api route to get file contents from file store

src/main/java/com/github/tomakehurst/wiremock/core/Options.java, src/main/java/com/github/tomakehurst/wiremock/core/WireMockConfiguration.java, src/main/java/com/github/tomakehurst/wiremock/standalone/CommandLineOptions.java, src/test/java/com/github/tomakehurst/wiremock/core/WireMockConfigurationTest.java, src/test/java/com/github/tomakehurst/wiremock/standalone/CommandLineOptionsTest.java
This PR defaults the max template cache entries to 1000 instead of infinite.
* https://github.com/wiremock/wiremock/issues/2731
=> Default the max template cache entries to 1000 instead of infinite

src/main/java/com/github/tomakehurst/wiremock/core/Options.java, src/main/java/com/github/tomakehurst/wiremock/core/WireMockConfiguration.java, src/main/java/com/github/tomakehurst/wiremock/http/client/ApacheBackedHttpClient.java, src/main/java/com/github/tomakehurst/wiremock/http/client/ApacheHttpClientFactory.java, src/main/java/com/github/tomakehurst/wiremock/servlet/WarConfiguration.java, src/main/java/com/github/tomakehurst/wiremock/standalone/CommandLineOptions.java, src/test/java/com/github/tomakehurst/wiremock/ProxyAcceptanceTest.java, src/test/java/com/github/tomakehurst/wiremock/http/ProxyResponseRendererTest.java, src/test/java/com/github/tomakehurst/wiremock/standalone/CommandLineOptionsTest.java, src/test/java/ignored/Examples.java
On recent Wiremock versions the User-Agent is not preserved from the original request as in older versions. This PR adds the option to preserve it, it is based on the suggestion at this conversation: https://community.wiremock.io/t/16656487/hi-all-i-m-still-trying-to-find-a-way-to-keep-the-user-agent#c0f08603-a911-4754-a427-547c914ff259
- [Issue reported and suggestion of PR](https://community.wiremock.io/t/16656487/hi-all-i-m-still-trying-to-find-a-way-to-keep-the-user-agent#c0f08603-a911-4754-a427-547c914ff259)
=> Add preserveUserAgentProxyHeader to keep User-Agent header

src/main/java/com/github/tomakehurst/wiremock/core/Options.java, src/main/java/com/github/tomakehurst/wiremock/core/WireMockConfiguration.java, src/main/java/com/github/tomakehurst/wiremock/http/HttpClientFactory.java, src/main/java/com/github/tomakehurst/wiremock/http/client/ApacheBackedHttpClient.java, src/main/java/com/github/tomakehurst/wiremock/http/client/ApacheHttpClientFactory.java, src/main/java/com/github/tomakehurst/wiremock/servlet/WarConfiguration.java, src/main/java/com/github/tomakehurst/wiremock/standalone/CommandLineOptions.java, src/test/java/com/github/tomakehurst/wiremock/standalone/CommandLineOptionsTest.java
When proxying requests, wiremock created a new socket for each request, and closed the old one. At the same time, when the socket is closed, it is transferred to the TIME_WAIT status and it should take about 60 more seconds before the socket actually closes. Therefore, at high load, wiremock very quickly used ports out of the ephemeral port range. Accordingly, he cannot take the port to create a new connection and the request is queued
Moreover, when creating HttpClient, we pass the maxConnections parameter, the value of which is used as MaxConnTotal and maxConnPerRoute, but this code overridden the ConnectionManager parameters. Therefore, in fact, we had the following values - MaxConnTotal =25, maxConnPerRoute=5. Which had an even stronger effect on the performance of the proxying by …
=> Fix HttpClientBuilder сode and add options for Connection Management to increase the proxying performance

src/testFixtures/java/com/github/tomakehurst/wiremock/testsupport/TestNotifier.java
Prevents a client adding messages without calling `error` or `info` on
`TestNotifier` by modifying the Lists returned by `getInfoMessages` and
`getErrorMessages`.
More immediately usefully, saves a client from getting
`ConcurrentModificationException`s when iterating over the List returned
by those methods if other threads are concurrently altering them, which
should stop `WebhooksAcceptanceViaPostServeActionTest.firesASingleWebhookWhenRequested`
(and others?) being flaky.
=> TestNotifier.get{Level}Messages return a snapshot

src/main/java/com/github/tomakehurst/wiremock/store/DefaultStores.java
Previously getObjectStore was an unsynchronized check-then-act, with
the result of `putIfAbsent` ignored, so the returned store might not
even be the store kept in the objectStores map.
Using the atomic `computeIfAbsent` avoids this problem.
=> Fix race condition in getObjectStore

src/main/java/com/github/tomakehurst/wiremock/store/DefaultStores.java, src/main/java/com/github/tomakehurst/wiremock/store/Stores.java
Previously it was hardcoded to 10,000, this PR allows clients of
`Stores` to specify any max size whilst maintaining backwards
compatibility by overloading the `getObjectStore` method.
Note that the maxItems parameter only affects an ephemeral object store
at present.
=> Allow configuring max items of an ObjectStore

src/main/java/com/github/tomakehurst/wiremock/extension/responsetemplating/RequestTemplateModel.java, src/main/java/com/github/tomakehurst/wiremock/extension/responsetemplating/TemplateEngine.java, src/main/java/org/wiremock/webhooks/Webhooks.java, src/test/java/com/github/tomakehurst/wiremock/WebhooksAcceptanceViaServeEventTest.java, src/test/java/com/github/tomakehurst/wiremock/extension/responsetemplating/ResponseTemplateTransformerTest.java
This PR adds the unique serveEvent Id to the `request` template model and also exposes the same id in the webhook `originalRequest` template model.
resolves https://github.com/wiremock/wiremock/issues/2756
=> Add request id to the template model

src/main/java/com/github/tomakehurst/wiremock/client/WireMock.java, src/main/java/com/github/tomakehurst/wiremock/matching/EqualToXmlPattern.java, src/main/java/com/github/tomakehurst/wiremock/matching/StringValuePatternJsonDeserializer.java, src/test/java/com/github/tomakehurst/wiremock/matching/EqualToXmlPatternTest.java
Ignores the order of nodes on the same level by applying secondary sorting by the text content of the node. This allows to match requests where there can be multiple same tags in arbitrary order
Given example configuration:
```java
.withRequestBody(equalToXml("<body>" +
"   <entry>1</entry>" +
"   <entry>2</entry>" +
"</body>", false, true))
```
Will match
```xml
<body>
<entry>2</entry>
<entry>1</entry>
</body>
```
and match 
```xml
<body>
<entry>1</entry>
<entry>2</entry>
</body>
```
Added property to enable secondary sort by node text content. The property name is `ignoreOrderOfSameNode`. Tried to follow pattern similar to `equalToJson` implementation. Update existing `equalToXml` static methods to pass `null` value as the parameter to preserve existing behavior. Added two additional …
=> Ignore order of xml nodes on same level when matching request body

src/main/java/com/github/tomakehurst/wiremock/core/Options.java, src/main/java/com/github/tomakehurst/wiremock/core/WireMockConfiguration.java, src/main/java/com/github/tomakehurst/wiremock/extension/responsetemplating/RequestLine.java, src/main/java/com/github/tomakehurst/wiremock/extension/responsetemplating/RequestTemplateModel.java, src/main/java/com/github/tomakehurst/wiremock/extension/responsetemplating/TemplateEngine.java, src/main/java/com/github/tomakehurst/wiremock/extension/responsetemplating/TemplatedUrlPath.java, src/main/java/com/github/tomakehurst/wiremock/http/Request.java, src/main/java/com/github/tomakehurst/wiremock/http/RequestIdDecorator.java, src/main/java/com/github/tomakehurst/wiremock/http/RequestPathParamsDecorator.java, src/main/java/com/github/tomakehurst/wiremock/http/client/ApacheHttpClientFactory.java, src/main/java/com/github/tomakehurst/wiremock/matching/RequestPattern.java, src/main/java/com/github/tomakehurst/wiremock/servlet/WarConfiguration.java, src/main/java/com/github/tomakehurst/wiremock/standalone/CommandLineOptions.java, src/main/java/com/github/tomakehurst/wiremock/store/StubMappingStore.java, src/main/java/com/github/tomakehurst/wiremock/stubbing/AbstractStubMappings.java, src/main/java/com/github/tomakehurst/wiremock/stubbing/ServeEvent.java, src/main/java/com/github/tomakehurst/wiremock/verification/LoggedRequest.java, src/main/java/org/wiremock/webhooks/Webhooks.java, src/test/java/com/github/tomakehurst/wiremock/CustomMatchingAcceptanceTest.java, src/test/java/com/github/tomakehurst/wiremock/ResponseDefinitionTransformerV2AcceptanceTest.java, src/test/java/com/github/tomakehurst/wiremock/WebhooksAcceptanceViaServeEventTest.java, src/test/java/com/github/tomakehurst/wiremock/extension/responsetemplating/ResponseTemplateTransformerTest.java, src/test/java/com/github/tomakehurst/wiremock/matching/MockRequest.java, src/test/java/com/github/tomakehurst/wiremock/standalone/CommandLineOptionsTest.java
Add path parameters to the request object via decoration when possible i.e. when we know which stub we're trying to match against (and can thus get at the path parameters).
Also add the serve event ID to the request so that this can be utilised in the template model.
=> Path params and serve event ID in request

src/main/java/com/github/tomakehurst/wiremock/common/DefaultNetworkAddressRules.java, src/main/java/com/github/tomakehurst/wiremock/common/NetworkAddressRange.java, src/main/java/com/github/tomakehurst/wiremock/common/NetworkAddressRules.java, src/main/java/com/github/tomakehurst/wiremock/http/NetworkAddressRulesAdheringDnsResolver.java, src/test/java/com/github/tomakehurst/wiremock/http/NetworkAddressRulesAdheringDnsResolverTest.java
attempt to fix https://github.com/wiremock/wiremock/issues/2736
=> Disabled DNS filtering when no custom proxy security rules are set

src/main/java/org/wiremock/webhooks/Webhooks.java, src/test/java/com/github/tomakehurst/wiremock/FailingWebhookTest.java, src/test/java/com/github/tomakehurst/wiremock/WebhooksAcceptanceTest.java, src/test/java/com/github/tomakehurst/wiremock/WebhooksAcceptanceViaPostServeActionTest.java, src/test/java/com/github/tomakehurst/wiremock/WebhooksAcceptanceViaServeEventTest.java
This PR adds `INFO` sub events for the successful webhook request/response as well as `ERROR` sub events for any error conditions that occur. Requests and Responses are logged as a `LoggedRequest` and `LoggedResponse` where the `LoggedResponse` body limit is taken from the configured `maxLoggedResponseSize`
impements https://github.com/wiremock/wiremock/issues/2759
=> 2759 report webhook errors and results as sub events

src/main/java/com/github/tomakehurst/wiremock/store/InMemoryObjectStore.java, src/test/java/com/github/tomakehurst/wiremock/store/InMemoryObjectStoreTest.java
On attempting to read a value for a key not in the store we were adding
that key to the set of keys, and in the process wrongly concluding the
cache was over its limits and ejecting a real value.
=> Stop ejecting existing key on read of missing key

src/main/java/com/github/tomakehurst/wiremock/matching/AbstractDateTimeMatchResult.java, src/test/java/com/github/tomakehurst/wiremock/matching/EqualToDateTimePatternTest.java
Right now, Wiremock doesn't support matching multiple expected zoned date/time values with multiple actual local ones.
In other words, given the matchers below:
```
"request": {
"urlPath": "/resource",
"queryParameters": {
"date": {
"hasExactly": [
{
"equalToDateTime": "now",
"truncateExpected": "first hour of day",
"actualFormat": "yyyy-MM-dd"
},
{
"equalToDateTime": "now",
"expectedOffset": 1,
"expectedOffsetUnit": "days",
"truncateExpected": "first hour of day",
"actualFormat": "yyyy-MM-dd"
}
]
}
}
}
```
Then a GET request to the URL below should match (assuming the date is March 27th 2024):
```
/resource?date=2024-03-27&date=2024-03-28
```
Instead, we get a "request was not matched" message.
If we remove `hasExactly` then GET requests to the two following URIs do …
=> Fix matching of multiple expected zoned date/time values with multiple actual local ones

build.gradle
1.4.3 has important fixes to the SchemaLocation parsing around JSON
Pointers
=> com.networknt:json-schema-validator:1.4.0 -> 1.4.3

src/main/java/com/github/tomakehurst/wiremock/extension/responsetemplating/RequestPartTemplateModel.java, src/main/java/com/github/tomakehurst/wiremock/extension/responsetemplating/RequestTemplateModel.java, src/main/java/com/github/tomakehurst/wiremock/extension/responsetemplating/TemplateEngine.java, src/main/java/com/github/tomakehurst/wiremock/http/Body.java, src/main/java/com/github/tomakehurst/wiremock/http/ContentTypeHeader.java, src/main/java/com/github/tomakehurst/wiremock/http/multipart/FileItemPartAdapter.java, src/test/java/com/github/tomakehurst/wiremock/MultipartTemplatingAcceptanceTest.java, src/test/java/com/github/tomakehurst/wiremock/ResponseTemplatingAcceptanceTest.java
This PR exposes the multipart data to the request template model allowing it to be used in response templates.  Part of this change has also added the `Body` object to the request model which allows us to expose the base64 representation of the body to the template model.  This is for both the actual request and the individual parts of a multipart request.
=> Multipart request template model

src/main/java/com/github/tomakehurst/wiremock/extension/responsetemplating/RequestPartTemplateModel.java, src/test/java/com/github/tomakehurst/wiremock/MultipartTemplatingAcceptanceTest.java
Add a toString to the ResponsePartTemplateModel class
=> Add a toString to the ResponsePartTemplateModel class

src/main/resources/swagger/examples/health.yaml, src/main/resources/swagger/schemas/health.yaml, src/main/resources/swagger/wiremock-admin-api.json, src/main/resources/swagger/wiremock-admin-api.yaml
This PR updates the OpenAPI spec with the missing admin endpoints.
- TODO
=> Add missing admin endpoints to open api spec

src/main/java/com/github/tomakehurst/wiremock/store/InMemoryObjectStore.java, src/test/java/com/github/tomakehurst/wiremock/store/InMemoryObjectStoreTest.java
Previously, if the compute function returned null this was not considered a removal by the LRU cache.
=> correctly handle InMemoryObjectStore.compute returning null.

src/main/java/com/github/tomakehurst/wiremock/matching/MatchesJsonSchemaPattern.java, src/test/java/com/github/tomakehurst/wiremock/matching/MatchesJsonSchemaPatternTest.java
and include an explanatory sub event.
previously invalid json schemas were rejected on creation, but this is not guaranteed to be correct as external schema refs can change and make previously invalid schemas valid and vice versa.
=> update MatchesJsonSchemaPattern to handle invalid json schemas.

src/main/java/com/github/tomakehurst/wiremock/common/DateTimeParser.java, src/main/java/com/github/tomakehurst/wiremock/matching/AbstractDateTimePattern.java, src/test/java/com/github/tomakehurst/wiremock/common/DateTimeParserTest.java, src/test/java/com/github/tomakehurst/wiremock/matching/EqualToDateTimePatternTest.java
Currently Wiremock supports request matching with dynamic date/time values but not with dynamic year values. In other words, given the following matcher:
```
"request": {
"urlPath": "/resource",
"queryParameters": {
"year": {
"equalToDateTime": "now",
"truncateExpected": "first day of year"
}
}
}
```
A GET request to the following URI does not match (assuming the current year is 2024):
```
/resource?year=2024
```
Even though a GET request to the following three URIs matches (assuming the current year is 2024 and the system timezone is UTC):
```
/resource?year=2024-01-01T00:00:00.000Z
/resource?year=2024-01-01T00:00:00.000
/resource?year=2024-01-01
```
That is because the current implementation attempts to parse the actual date/time value using  `ZonedDateTime`, …
=> Add support for request matching with dynamic year and dynamic year/month values

src/main/java/com/github/tomakehurst/wiremock/extension/responsetemplating/helpers/PickRandomHelper.java, src/test/java/com/github/tomakehurst/wiremock/extension/responsetemplating/ResponseTemplateTransformerTest.java
* Return objects instead of `.toString()` to support further processing.
* Allow an optional `count` to be specified, returning a collection of items with no duplicates.
=> Pick random helper enhancements

src/main/java/com/github/tomakehurst/wiremock/matching/MatchesJsonSchemaPattern.java, src/test/java/com/github/tomakehurst/wiremock/JsonSchemaMatchingAcceptanceTest.java, src/test/java/com/github/tomakehurst/wiremock/matching/MatchesJsonSchemaPatternTest.java
https://github.com/wiremock/wiremock/pull/2803 explicitly allowed the creation of stubs containing invalid json schemas to account for the possibility of schemas becoming valid/invalid after creation. that pr went a bit too far by allowing json schemas that weren't even valid json (which will always be invalid schemas). this creates problems as other methods in MatchesJsonSchemaPattern expect the schema to at least be valid json. this pr disallows invalid json but keeps the other allowances.
=> disallow json schemas to be invalid json.

src/main/java/com/github/tomakehurst/wiremock/matching/AbstractDateTimePattern.java, src/main/java/com/github/tomakehurst/wiremock/matching/AfterDateTimePattern.java, src/main/java/com/github/tomakehurst/wiremock/matching/BeforeDateTimePattern.java, src/main/java/com/github/tomakehurst/wiremock/matching/EqualToDateTimePattern.java, src/main/java/com/github/tomakehurst/wiremock/matching/StringValuePatternJsonDeserializer.java, src/test/java/com/github/tomakehurst/wiremock/matching/AfterDateTimePatternTest.java, src/test/java/com/github/tomakehurst/wiremock/matching/BeforeDateTimePatternTest.java, src/test/java/com/github/tomakehurst/wiremock/matching/EqualToDateTimePatternTest.java
Given the matcher below:
```
"request": {
"urlPath": "/resource",
"queryParameters": {
"date": {
"equalToDateTime": "now +1 months",
"truncateExpected": "last day of month"
}
}
}
```
One would expect for the `last day of month` truncation to be applied to the `now +1 months` expected date/time value.
Instead, what currently happens is the `last day of month` truncation is applied to `now` and the result is then offset by `+1 months`.
This is very counterintuitive and not what someone would expect by looking at the matcher above.
This PR reverses the order of offsetting and truncating expected date/time values with the truncations now being applied last.
A more in depth discussion of the issue can be found in the enhancement proposal: #2789
=> Add support for reversing order of offsetting and truncating expected date/time values

src/main/java/com/github/tomakehurst/wiremock/verification/diff/Diff.java, src/test/java/com/github/tomakehurst/wiremock/verification/diff/DiffTest.java
Fixes diff report rendering failures when a stub contains multiple path parameters but only some have matchers.
Fixes https://github.com/wiremock/wiremock/issues/2826
=> fix failing diffing for multiple path params.

ui/package-lock.json, ui/package.json
Force glob to a version that no longer uses deprecated inflight.
Doesn't seem to break redocly.
=> chore: remove node vulnerabilities 2

src/main/java/com/github/tomakehurst/wiremock/extension/requestfilter/RequestWrapper.java, src/test/java/com/github/tomakehurst/wiremock/extension/requestfilter/RequestWrapperTest.java
The `RequestWrapper` `containsHeader` method performs a case-sensitive check on the header name.  This PR updates the method to make sure the check is case-insensitive.
Fixes #2845
=> Header checks should be case-insensitive in RequestWrapper

build.gradle, wiremock-jetty12/build.gradle
This is to resolve a Denial of Service (DoS) Affecting org.eclipse.jetty:jetty-server package, versions [9.3.12,9.4.56) [10.0.0,10.0.24) [11.0.0,11.0.24) [12.0.0,12.0.9)
See the following for more information:
* https://www.cve.org/CVERecord?id=CVE-2024-8184
* https://security.snyk.io/vuln/SNYK-JAVA-ORGECLIPSEJETTY-8186142
- TODO
=> Bump both versions of jetty to the latest versions

src/main/java/com/github/tomakehurst/wiremock/matching/EqualToXmlPattern.java, src/test/java/com/github/tomakehurst/wiremock/matching/EqualToXmlPatternTest.java
Fixes serialization of `ignoreOrderOfSameNode` property for the `equalToXml` body. Property was not serialized because getter was missing hence was never applied
https://github.com/wiremock/wiremock/pull/2747
=> fix serialization of ignoreOrderOfSameNode for equalToXml

src/main/java/com/github/tomakehurst/wiremock/extension/responsetemplating/helpers/AbstractFormattingHelper.java, src/main/java/com/github/tomakehurst/wiremock/extension/responsetemplating/helpers/FormatJsonHelper.java, src/main/java/com/github/tomakehurst/wiremock/extension/responsetemplating/helpers/FormatXmlHelper.java, src/main/java/com/github/tomakehurst/wiremock/extension/responsetemplating/helpers/HelperUtils.java, src/main/java/com/github/tomakehurst/wiremock/extension/responsetemplating/helpers/JsonArrayAddHelper.java, src/main/java/com/github/tomakehurst/wiremock/extension/responsetemplating/helpers/JsonMergeHelper.java, src/main/java/com/github/tomakehurst/wiremock/extension/responsetemplating/helpers/JsonRemoveHelper.java, src/main/java/com/github/tomakehurst/wiremock/extension/responsetemplating/helpers/ToJsonHelper.java, src/main/java/com/github/tomakehurst/wiremock/extension/responsetemplating/helpers/WireMockHelpers.java, src/test/java/com/github/tomakehurst/wiremock/extension/responsetemplating/ResponseTemplateTransformerTest.java, src/test/java/com/github/tomakehurst/wiremock/extension/responsetemplating/helpers/FormatJsonHelperTest.java, src/test/java/com/github/tomakehurst/wiremock/extension/responsetemplating/helpers/FormatXmlHelperTest.java, src/test/java/com/github/tomakehurst/wiremock/extension/responsetemplating/helpers/JsonArrayAddHelperTest.java, src/test/java/com/github/tomakehurst/wiremock/extension/responsetemplating/helpers/JsonMergeHelperTest.java, src/test/java/com/github/tomakehurst/wiremock/extension/responsetemplating/helpers/JsonRemoveHelperTest.java, src/test/java/com/github/tomakehurst/wiremock/extension/responsetemplating/helpers/ToJsonHelperTest.java, src/testFixtures/java/com/github/tomakehurst/wiremock/testsupport/MockWireMockServices.java
Add additional handlebars helpers for working with JSON and XML.
=> New JSON and XML handlebars helpers

src/main/java/com/github/tomakehurst/wiremock/junit5/WireMockExtension.java
When using `WireMockExtension` alongside other JUnit 5 extensions, a failure in another extension can prevent the WireMock server from starting. However, JUnit still calls the `afterAll` method on all extensions, which leads to a `NullPointerException` in `WireMockExtension.stopServerIfRunning()` because `wireMockServer` was never initialized.
https://github.com/wiremock/wiremock/issues/2627
=> Add null check in WireMockExtension.stopServerIfRunning()

src/main/java/com/github/tomakehurst/wiremock/WireMockServer.java, src/main/java/com/github/tomakehurst/wiremock/core/Options.java, src/main/java/com/github/tomakehurst/wiremock/core/WireMockConfiguration.java, src/main/java/com/github/tomakehurst/wiremock/extension/ExtensionFactory.java, src/main/java/com/github/tomakehurst/wiremock/extension/Extensions.java, src/main/java/com/github/tomakehurst/wiremock/http/DefaultFactory.java, src/main/java/com/github/tomakehurst/wiremock/http/HttpServerFactory.java, src/main/java/com/github/tomakehurst/wiremock/http/HttpServerFactoryLoader.java, src/main/java/com/github/tomakehurst/wiremock/jetty/JettyHttpServer.java, src/main/java/com/github/tomakehurst/wiremock/jetty/JettyHttpServerFactory.java, src/main/java/com/github/tomakehurst/wiremock/servlet/WarConfiguration.java, src/main/java/com/github/tomakehurst/wiremock/standalone/CommandLineOptions.java, src/test/java/com/github/tomakehurst/wiremock/StubRequestLoggingAcceptanceTest.java, src/test/java/com/github/tomakehurst/wiremock/core/WireMockConfigurationTest.java, src/test/java/com/github/tomakehurst/wiremock/extension/ExtensionLifeCycleAcceptanceTest.java, src/test/java/com/github/tomakehurst/wiremock/http/HttpServerFactoryLoaderTest.java, wiremock-jetty12/build.gradle, wiremock-jetty12/src/test/java/com/github/tomakehurst/wiremock/jetty12/Http2AcceptanceTest.java, wiremock-jetty12/src/test/java/com/github/tomakehurst/wiremock/jetty12/ProgrammaticHttpServerAcceptanceTest.java, wiremock-jetty12/src/test/java/com/github/tomakehurst/wiremock/jetty12/server/CustomHttpServer.java, wiremock-jetty12/src/test/java/com/github/tomakehurst/wiremock/jetty12/server/CustomHttpServerFactory.java
This factors out the HTTP server factory loading logic so that it can be properly tested and and enhances it to better handle situations where multiple extensions are found.
This is largely in support of enabling the gRPC extension to support Jetty12.
=> HTTP server loading refinement

src/main/java/com/github/tomakehurst/wiremock/http/Request.java, src/main/java/com/github/tomakehurst/wiremock/http/multipart/FileItemPartAdapter.java, src/main/java/com/github/tomakehurst/wiremock/matching/MultipartValuePattern.java, src/main/java/com/github/tomakehurst/wiremock/matching/MultipartValuePatternBuilder.java, src/main/java/com/github/tomakehurst/wiremock/servlet/WireMockHttpServletMultipartAdapter.java, src/main/java/com/github/tomakehurst/wiremock/verification/diff/MissingMultipart.java, src/main/resources/swagger/schemas/request-pattern.yaml, src/test/java/com/github/tomakehurst/wiremock/StubbingAcceptanceTest.java, src/test/java/com/github/tomakehurst/wiremock/extension/requestfilter/RequestWrapperTest.java, src/test/java/com/github/tomakehurst/wiremock/matching/MockMultipart.java
- Added getFilename() in Request.Part interface
- Implemented the new method in FileItemPartAdapter, MissingMultipart, MockMultipart, WireMockHttpServletMultipartAdapter  following the conventions getName() to get part name and getFilename() to get the part filename.
- Updated RequestWrapperTest.transformsMultiparts() to include filename
Issue:  FileItemPartAdapter returning multipart's field name instead of a filename #2750
Included Suggestion: Update FileItemPartAdapter.java #2764
=> Support filename capabilities for Multipart's part

src/main/java/com/github/tomakehurst/wiremock/http/HttpServerFactoryLoader.java, src/test/java/com/github/tomakehurst/wiremock/http/HttpServerFactoryLoaderTest.java
Due to a misconfiguration on my side, I had no HttpServerFactory available. Unfortunately the IndexOutOfBoundsException that was thrown (see below) for this, was not very helpful in figuring out what the issue was.
This is the originally thrown exception + stack trace:
```
java.lang.IndexOutOfBoundsException: Index 0 out of bounds for length 0
at java.base/jdk.internal.util.Preconditions.outOfBounds(Preconditions.java:100)
at java.base/jdk.internal.util.Preconditions.outOfBoundsCheckIndex(Preconditions.java:106)
at java.base/jdk.internal.util.Preconditions.checkIndex(Preconditions.java:302)
at java.base/java.util.Objects.checkIndex(Objects.java:385)
at java.base/java.util.ArrayList.get(ArrayList.java:427)
at com.github.tomakehurst.wiremock.http.HttpServerFactoryLoader.pickMostAppropriateFr …
```
=> Throw descriptive exception when no suitable HttpServerFactory extension was found

src/main/java/com/github/tomakehurst/wiremock/common/xml/Xml.java, src/main/java/com/github/tomakehurst/wiremock/extension/responsetemplating/helpers/FormatXmlHelper.java, src/main/java/com/github/tomakehurst/wiremock/matching/EqualToXmlPattern.java, src/test/java/com/github/tomakehurst/wiremock/matching/EqualToXmlPatternTest.java
this should have always been the case but seems to not be in certain situations.
=> make EqualToXmlPattern namespace aware by default.

src/main/java/com/github/tomakehurst/wiremock/matching/EqualToXmlPattern.java, src/test/java/com/github/tomakehurst/wiremock/matching/EqualToXmlPatternTest.java
removes use of DiffBuilder.ignoreComments which performs an xslt transform on the provided XML documents which is very memory intensive. now comments are ignored at read/parse time.
as part of this change, the Xml utility class was also refactored to (hopefully) make it more reusable.
=> improve performance of EqualToXmlPattern.

src/main/java/com/github/tomakehurst/wiremock/http/HttpClientFactory.java
https://github.com/wiremock/wiremock/issues/2948
With the update to apache httpclient 5.4 a new feature creeps into the codebase.
It adds TLS Upgrade (https://datatracker.ietf.org/doc/html/rfc2817#section-3.1) headers as a default.
This in turn breaks all communication via envoy (eg. k8s/istio)
https://github.com/envoyproxy/envoy/issues/36305
https://issues.apache.org/jira/browse/HTTPCLIENT-2344
This fix sets the "protocolUpgradeEnabled" flag for the httpclient to false (default is true).
https://github.com/wiremock/wiremock/issues/2948
- [-] Recommended: Join [WireMock Slack](https://slack.wiremock.org/) to get any help in `#help-contributing` or a project-specific channel like `#wiremock-java`
- [?] Test coverage that demonstrates that the change works as expected
- [-] For new …
=> Disable problematic protocol update for httpclient 5.4

src/main/resources/swagger/schemas/after-pattern.yaml
Correctly document after-pattern.yaml as being after a datetime rather than before
=> Update after-pattern.yaml to fix typo

src/main/java/com/github/tomakehurst/wiremock/extension/responsetemplating/helpers/FormatXmlHelper.java, wiremock-jetty12/src/test/java/com/github/tomakehurst/wiremock/jetty12/FaultsTest.java, wiremock-jetty12/src/test/java/com/github/tomakehurst/wiremock/jetty12/Http2AcceptanceTest.java, wiremock-jetty12/src/test/java/com/github/tomakehurst/wiremock/jetty12/Http2ClientFactory.java, wiremock-jetty12/src/test/java/com/github/tomakehurst/wiremock/jetty12/Http2DisabledAcceptanceTest.java, wiremock-jetty12/src/test/java/com/github/tomakehurst/wiremock/jetty12/Jetty12MultipartParser.java, wiremock-jetty12/src/test/java/com/github/tomakehurst/wiremock/jetty12/Jetty12MultipartParserLoader.java, wiremock-jetty12/src/test/java/com/github/tomakehurst/wiremock/jetty12/ProgrammaticHttpServerAcceptanceTest.java, wiremock-jetty12/src/test/java/com/github/tomakehurst/wiremock/jetty12/server/CustomHttpServer.java, wiremock-jetty12/src/test/java/com/github/tomakehurst/wiremock/jetty12/server/CustomHttpServerFactory.java, wiremock-jetty12/src/test/java/com/github/tomakehurst/wiremock/jetty12/servlet/AltHttpServerFactory.java, wiremock-jetty12/src/test/java/com/github/tomakehurst/wiremock/jetty12/servlet/AlternativeServletContainerTest.java
Closes #2911
Closes #2913
The implementation of `FormatXmlHelper` relies on a non-standard `TransformerFactory` attribute, `indent-number`, which is not supported by all implementations. By using `TransformerFactory.newDefaultInstance` instead of `TransformerFactory.newInstance`, the system default implementation (`com.sun.org.apache.xalan.internal.xsltc.trax.TransformerFactoryImpl` on OpenJDK-derived JDKs) will be used regardless of any other implementations which might be present on the classpath.
---
Unfortunately, I don't see any way to add or update any tests for this change without introducing a dependency on another XML library. To ensure this change has the expected behavior, I used the same reproduction steps as in #2911 (include Saxon-HE in a small test project): the exception …
=> Always use the system default `TransformerFactory` in `FormatXmlHelper`

build.gradle, wiremock-jetty12/build.gradle
When we updated to `7.x.x` we started having issues where files that hadn't been changed were reporting headers that needed updating.
This has been reported here:
https://github.com/diffplug/spotless/issues/2404
=> Drop to the version of spotless where we didn't have any issues

src/main/java/com/github/tomakehurst/wiremock/extension/responsetemplating/helpers/JsonMergeHelper.java, src/test/java/com/github/tomakehurst/wiremock/extension/responsetemplating/helpers/JsonMergeHelperTest.java
Adds an optional `removeNulls` parameter to the `jsonMerge` helper. When true this removes any attributes from the resulting JSON that have null values in the JSON to merge.
=> Support optional removal of null-valued attributes in jsonMerge helper

src/main/resources/swagger/schemas/request-pattern.yaml
#2888 introduced the fileName property in `MultipartValuePattern` and along with it in the `request-pattern.yaml` schema.
In the former, it was deserialized as `fileName` while in the latter it was defined as `filename`. Now both use `fileName`.
- #2888
=> Use camel-case format for the fileName property in the request-pattern schema

src/main/java/com/github/tomakehurst/wiremock/matching/EqualToXmlPattern.java, src/test/java/com/github/tomakehurst/wiremock/matching/EqualToXmlPatternTest.java
Currently, if the expected XML of an EqualToXmlPattern contains unbounded namespace prefixes, calling `getExpected()` on the pattern will throw an exception. This PR fixes that.
=> fix: handle unbound ns prefixes when printing xml.

.github/workflows/build-and-test.yml
`actions/cache@v1` is now deprecated as per this article:
https://github.blog/changelog/2024-12-05-notice-of-upcoming-releases-and-breaking-changes-for-github-actions/#actions-cache-v1-v2-and-actions-toolkit-cache-package-closing-down
- [ x] Test coverage that demonstrates that the change works as expected
=> Update `actions/cache@v1` to use `v4`

src/main/java/com/github/tomakehurst/wiremock/common/xml/Xml.java, src/test/java/com/github/tomakehurst/wiremock/common/xml/XmlTest.java
DocumentBuilders are not thread safe.
This was a bug I introduced in [this commit](https://github.com/wiremock/wiremock/commit/f91326573547a90fd143252d77961eaa0345dbb1)
=> fix: use thread local document builder.

src/main/java/com/github/tomakehurst/wiremock/common/xml/BuilderPerThreadDocumentBuilderFactory.java, src/main/java/com/github/tomakehurst/wiremock/common/xml/DelegateDocumentBuilderFactory.java, src/main/java/com/github/tomakehurst/wiremock/common/xml/SilentErrorDocumentBuilderFactory.java, src/main/java/com/github/tomakehurst/wiremock/common/xml/SkipResolvingEntitiesDocumentBuilderFactory.java, src/main/java/com/github/tomakehurst/wiremock/common/xml/Xml.java, src/main/java/com/github/tomakehurst/wiremock/matching/EqualToXmlPattern.java
Caches DocumentBuilderFactories, allowing caching DocumentBuilders, for EqualToXmlPattern.
fix: use thread local document builder. #2977
Fix XML bad performances on matching XPath #1096
=> Xml perf improvements

build.gradle
json-path is no longer lagging behind on its dependency version.
=> chore: remove json-smart dependency constraint.

.github/workflows/publish-snapshot.yml
add -SNAPSHOT to the end of the version. hopefully this will allow duplicate packages under the same version.
=> fix: publishing branch snapshots to github.

src/main/java/com/github/tomakehurst/wiremock/matching/MultipleMatchMultiValuePattern.java, src/main/java/com/github/tomakehurst/wiremock/recording/RequestPatternTransformer.java, src/main/java/com/github/tomakehurst/wiremock/recording/ScenarioProcessor.java, src/main/java/com/github/tomakehurst/wiremock/recording/SnapshotStubMappingBodyExtractor.java, src/test/java/com/github/tomakehurst/wiremock/RecordingDslAcceptanceTest.java, src/test/java/com/github/tomakehurst/wiremock/matching/MultiValuePatternTest.java
previously, query parameters of recorded requests were part of the url pattern. creating separate query parameter matchers adds more flexibility to the stub mapping.
=> feat: record query param matchers.

src/main/resources/swagger/schemas/equal-to-json-pattern.yaml, src/main/resources/swagger/schemas/equal-to-xml-pattern.yaml, src/main/resources/swagger/schemas/logged-request.yaml, src/main/resources/swagger/schemas/matches-json-schema-pattern.yaml, src/main/resources/swagger/schemas/not-pattern.yaml, src/main/resources/swagger/schemas/request-pattern.yaml, src/main/resources/swagger/wiremock-admin-api.yaml
Spotted a few more issues with the OpenAPI docs over the weekend, so have put a PR together to try and address them in bulk. Hope it is all okay.
- Fix `equal-to-json` to document that using a raw object is also valid, and add example.
- Rewrite schema for `matches-json-schema` as it was just copied from the `matches-xpath` schema.
- Removed undocumented `xPathNamespaces` attributes from `matches-json-schema`.
- Update description of `not` to match `or` and `and`.
- Fix example in `request-pattern` that was not valid JSON.
- Fix headers example in `logged-request`.
- Correctly trim whitespace out of `equal-to-pattern` example.
- Remove spurious whitespace from admin API descriptors.
- Convert raw JSON examples to raw YAML objects to make the example format clear in any generated …
=> Fix OpenAPI 3.0 schemas

src/main/java/com/github/tomakehurst/wiremock/http/StubResponseRenderer.java, src/test/java/com/github/tomakehurst/wiremock/DebugHeadersAcceptanceTest.java
non-iso_8859_1 characters fail to be hpack encoded by jetty's http2 implementation, and iso_8859_1 characters that are not ascii characters are not handled well by most clients because they assume utf-8 encoding.
https://www.rfc-editor.org/rfc/rfc9110.html#name-field-values
fixes https://github.com/wiremock/wiremock/issues/2872
=> fix: matched stub name header value encoding.

src/main/java/com/github/tomakehurst/wiremock/core/Options.java, src/main/java/com/github/tomakehurst/wiremock/core/WireMockConfiguration.java, src/main/java/com/github/tomakehurst/wiremock/extension/Extensions.java, src/main/java/com/github/tomakehurst/wiremock/servlet/WarConfiguration.java, src/main/java/com/github/tomakehurst/wiremock/standalone/CommandLineOptions.java, src/test/java/com/github/tomakehurst/wiremock/core/WireMockConfigurationTest.java, src/test/java/com/github/tomakehurst/wiremock/standalone/CommandLineOptionsTest.java
Adds an option to the WireMock config, the CLI options and War config. If not specified, it defaults to 10 which was the original hardcoded value.
Not sure if there is a nice way to test that the configured value is propagated to the `Executors.newScheduledThreadPool` creation. 
Docs PR still needed
- Implements suggestion in #2998
=> Allow the webhook scheduler thread pool size to be configured

src/main/java/com/github/tomakehurst/wiremock/junit5/WireMockExtension.java, src/test/java/com/github/tomakehurst/wiremock/junit5/JUnitJupiterExtensionResetOnEachTestTest.java
By default the JUnit `WireMockExtension` resets stubs and requests in the `beforeEach` method.  This is not always desirable (as per issue #2895).  This PR keeps the default behaviour with regards to reseting but adds a new method to allow the behaviour to be turned off
Docs PR still needs to be done
- #2895
=> Allow the WireMockExtension to not reset in beforeEach

src/main/java/com/github/tomakehurst/wiremock/extension/responsetemplating/TemplateEngine.java, src/test/java/com/github/tomakehurst/wiremock/MultipartTemplatingAcceptanceTest.java
According to RFC 2387, request part name is an optional parameter for multipart/related content. When global templating is enabled, null part names cause duplicate key issues in the template model map. This change ensures proper handling of null keys in RequestPartTemplateModel to prevent errors when processing multipart/related requests without part names.
- TODO
=> fix: handle null key in RequestPartTemplateModel for RFC 2387 compliance

src/main/java/com/github/tomakehurst/wiremock/client/BasicMappingBuilder.java, src/main/java/com/github/tomakehurst/wiremock/client/MappingBuilder.java, src/main/java/com/github/tomakehurst/wiremock/matching/RequestPattern.java, src/main/java/com/github/tomakehurst/wiremock/matching/RequestPatternBuilder.java, src/main/java/com/github/tomakehurst/wiremock/verification/diff/Diff.java, src/main/resources/swagger/wiremock-admin-api.json, src/test/java/com/github/tomakehurst/wiremock/StubbingWithBrowserProxyAcceptanceTest.java, src/test/java/com/github/tomakehurst/wiremock/matching/RequestPatternBuilderTest.java, src/test/java/com/github/tomakehurst/wiremock/verification/diff/DiffTest.java
This PR adds a new native matcher for client IP address that is available in wiremock's request ([see here](https://github.com/wiremock/wiremock/blob/7257dd665facf7329a656d14987ccfecff33606d/src/main/java/com/github/tomakehurst/wiremock/servlet/WireMockHttpServletRequestAdapter.java#L121) for reference where the actual value is loaded from). This improvement came up during a slack discussion available below. 
Usage looks like this:
```
wm.stubFor(get(anyUrl()).withClientIp(equalTo("127.0.0.1")));
```
As a native matcher, it benefits from a improved diff output in case of errors:
This new matcher is basically syntactic sugar for:
```
wm.stubFor(get(anyUrl()).andMatching(r -> equalTo("127.0.0.1").match(r.getClientIp())));
```
And the diff output without the native matcher would look like …
=> Expose native matcher for client ip address

src/main/java/com/github/tomakehurst/wiremock/WireMockServer.java, src/main/java/com/github/tomakehurst/wiremock/admin/AdminRoutes.java, src/main/java/com/github/tomakehurst/wiremock/admin/tasks/GetUnmatchedStubMappingsTask.java, src/main/java/com/github/tomakehurst/wiremock/admin/tasks/RemoveUnmatchedStubMappingsTask.java, src/main/java/com/github/tomakehurst/wiremock/client/HttpAdminClient.java, src/main/java/com/github/tomakehurst/wiremock/core/Admin.java, src/main/java/com/github/tomakehurst/wiremock/core/WireMockApp.java, src/main/java/com/github/tomakehurst/wiremock/junit/DslWrapper.java, src/main/resources/swagger/wiremock-admin-api.json, src/main/resources/swagger/wiremock-admin-api.yaml, src/test/java/com/github/tomakehurst/wiremock/AdminApiTest.java
This integrates the functionality of https://github.com/MasonM/wiremock-unused-stubs-extension into WireMock proper, as requested in https://github.com/wiremock/wiremock/issues/615#issuecomment-2724287164.
Specifically, it adds two endpoints:
* `GET /__admin/mappings/unmatched` - Retrieve stub mappings that haven't matched any requests in the journal.
* `DELETE /__admin/mappings/unmatched` - Remove all such stub mappings.
Note that the extension supports an additional `?remove_files=1` query parameter that I didn't include here because it introduces some additional complications (https://github.com/MasonM/wiremock-unused-stubs-extension/blob/424dfad1a21e25d588ac9230a46be820a579d7cf/src/main/java/com/github/masonm/wiremock/UnusedStubsAdminExtension.java#L71). I added that feature because …
=> feat: admin API endpoints to find/remove unmatched stub mappings

build.gradle.kts
version now uses double quotes, not single quotes.
=> fix: set gradle version correctly.

src/main/resources/swagger/schemas/equal-to-json-pattern.yaml, src/main/resources/swagger/schemas/equal-to-xml-pattern.yaml, src/main/resources/swagger/schemas/matches-json-schema-pattern.yaml, src/main/resources/swagger/schemas/not-pattern.yaml, src/main/resources/swagger/schemas/request-pattern.yaml, src/main/resources/swagger/wiremock-admin-api.yaml
Extend LogNormal to add an optional maxValue to force long tails to be truncated and the value resampled if greater than the max. The reason this might be necessary is that with some log normal configurations, a curve with quite a long tail can be experienced that can cause unexpected or unwanted timeouts in upstream systems. Setting a maximum delay value can prevent this from happening. If the value generated is greater than the max, then it is resampled a number of times (10) and then finally, the max of the two values is taken (to prevent resampling indefinitely)
Documentation changes will be raised in a subsequent PR but look as follows:
- This changes replaces [this original PR](https://github.com/wiremock/wiremock/pull/1694) which had `CappedLogNormal` as a new subclass of …
=> Extend LogNormal to add an optional maxValue

src/main/java/com/github/tomakehurst/wiremock/common/xml/Xml.java, src/main/java/com/github/tomakehurst/wiremock/common/xml/XmlNode.java
Closes #2454
Related #2913
Followup to recently merged https://github.com/wiremock/wiremock/pull/2918 which solved the issue partly.
The `newInstance()` method of aforementioned classes may return a different implementation based on classes present on classpath. For example when `oracle.xml.jaxp.JXDocumentBuilderFactory` is present on the classpath, the use use of the `http://xml.org/sax/features/validation` attribute in the `Xml.java` file causes `ParserConfigurationException`.
The `newDefaultInstance()` method ensures consistency across different environment by using the same implementation irrespective to the classpath.
- TODO
=> Always use the system default `DocumentBuilderFactory`, `TransformerFactory` and `XPathFactory`

src/main/java/com/github/tomakehurst/wiremock/client/BasicMappingBuilder.java, src/main/java/com/github/tomakehurst/wiremock/client/MappingBuilder.java, src/main/java/com/github/tomakehurst/wiremock/client/ScenarioMappingBuilder.java, src/test/java/com/github/tomakehurst/wiremock/StubbingAcceptanceTest.java
Existing methods in `MappingBuilder` only allow adding form param patterns for one key at a time by using one of
`withFormParam(String key, StringValuePattern formParamPattern)` or `withFormParam(String key, MultiValuePattern multiValueFormParamPattern)`.
In case of having a map with the form params (for example as the input from a `@ParameterizedTest` in a JUnit test) the current API requires to create a variable for the mapping builder and iterate over the map adding the patterns for each key individually, _**breaking the method chaining**_ that the builder is meant for:
```
Map<String, MultiValuePattern> formParamsMap; // given
MappingBuilder mappingBuilder = put(urlEqualTo("/form-params"));
formParamsMap.forEach(mappingBuilder::withFormParam);
stubFor(mappingBuilder);
```
This new …
=> Add method to MappingBuilder to add multiple form params

wiremock-common/src/main/java/com/github/tomakehurst/wiremock/recording/Recorder.java, wiremock-common/src/main/java/com/github/tomakehurst/wiremock/recording/SnapshotStubMappingPostProcessor.java, wiremock-common/src/main/java/com/github/tomakehurst/wiremock/recording/SnapshotStubMappingTransformerRunner.java
As far as we can see the `SnapshotStubMappingPostProcessor` and `SnapshotStubMappingTransformerRunner` do not need to be public API - they are instantiated explicitly by `Recorder` and cannot be injected anywhere.
We want to change their API, so reducing the visibility first.
Likewise, we see no benefit to `Recorder.getStubMappingPostProcessor` and `Recorder.serveEventsToStubMappings` being public, they are only called by `takeSnapshot`.
https://github.com/wiremock/wiremock/pull/3039
=> Reduce visibility of Recorder API that does not need to be public

src/main/java/com/github/tomakehurst/wiremock/recording/Recorder.java, src/main/java/com/github/tomakehurst/wiremock/recording/SnapshotStubMappingPostProcessor.java, src/main/java/com/github/tomakehurst/wiremock/recording/SnapshotStubMappingTransformerRunner.java
As far as we can see the `SnapshotStubMappingPostProcessor` and `SnapshotStubMappingTransformerRunner` do not need to be public API - they are instantiated explicitly by `Recorder` and cannot be injected anywhere.
We want to change their API in v4, so reducing the visibility first.
Likewise, we see no benefit to `Recorder.getStubMappingPostProcessor` and `Recorder.serveEventsToStubMappings` being public, they are only called by `takeSnapshot`.
https://github.com/wiremock/wiremock/pull/3038
=> Mark Recording API that does not need to be public deprecated

wiremock-common/src/main/java/com/github/tomakehurst/wiremock/recording/LoggedResponseDefinitionTransformer.java, wiremock-common/src/main/java/com/github/tomakehurst/wiremock/recording/RecordSpecBuilder.java, wiremock-common/src/main/java/com/github/tomakehurst/wiremock/recording/RequestPatternTransformer.java, wiremock-common/src/main/java/com/github/tomakehurst/wiremock/recording/ScenarioProcessor.java, wiremock-common/src/main/java/com/github/tomakehurst/wiremock/recording/SnapshotOutputFormatter.java, wiremock-common/src/main/java/com/github/tomakehurst/wiremock/recording/SnapshotStubMappingBodyExtractor.java, wiremock-common/src/main/java/com/github/tomakehurst/wiremock/recording/SnapshotStubMappingGenerator.java, wiremock-common/src/main/java/com/github/tomakehurst/wiremock/recording/SnapshotStubMappingTransformerRunner.java
Allows us to change it in future without worrying about breaking people.
N/A
=> Reduce visibility of API that does not need to be public

src/test/java/com/github/tomakehurst/wiremock/RecordingDslAcceptanceTest.java, wiremock-common/src/main/java/com/github/tomakehurst/wiremock/recording/RequestPatternTransformer.java
=> use single matcher for query params when only one.

src/main/java/com/github/tomakehurst/wiremock/recording/Recorder.java, src/main/java/com/github/tomakehurst/wiremock/recording/RequestPatternTransformer.java, src/main/java/com/github/tomakehurst/wiremock/recording/ScenarioProcessor.java, src/main/java/com/github/tomakehurst/wiremock/recording/SnapshotOutputFormatter.java, src/main/java/com/github/tomakehurst/wiremock/recording/SnapshotStubMappingBodyExtractor.java, src/main/java/com/github/tomakehurst/wiremock/recording/SnapshotStubMappingGenerator.java, src/main/java/com/github/tomakehurst/wiremock/recording/SnapshotStubMappingPostProcessor.java, src/test/java/com/github/tomakehurst/wiremock/recording/LoggedResponseDefinitionTransformerTest.java, src/test/java/com/github/tomakehurst/wiremock/recording/RequestPatternTransformerTest.java, src/test/java/com/github/tomakehurst/wiremock/recording/ScenarioProcessorTest.java, src/test/java/com/github/tomakehurst/wiremock/recording/SnapshotStubMappingBodyExtractorTest.java, src/test/java/com/github/tomakehurst/wiremock/recording/SnapshotStubMappingGeneratorTest.java, src/test/java/com/github/tomakehurst/wiremock/recording/SnapshotStubMappingPostProcessorTest.java, src/test/java/com/github/tomakehurst/wiremock/recording/SnapshotStubMappingTransformerRunnerTest.java
=> Mark APIs that will stop being public in v4.x as deprecated

src/test/java/com/github/tomakehurst/wiremock/standalone/JsonFileMappingsSourceTest.java, src/test/java/com/github/tomakehurst/wiremock/stubbing/RecordedStubPersistenceTest.java, src/test/java/com/github/tomakehurst/wiremock/stubbing/StubImportPersistenceTest.java, wiremock-common/src/main/java/com/github/tomakehurst/wiremock/core/MappingsSaver.java, wiremock-common/src/main/java/com/github/tomakehurst/wiremock/core/WireMockApp.java, wiremock-common/src/main/java/com/github/tomakehurst/wiremock/recording/ProxiedServeEventFilters.java, wiremock-common/src/main/java/com/github/tomakehurst/wiremock/recording/Recorder.java, wiremock-common/src/main/java/com/github/tomakehurst/wiremock/servlet/NotImplementedMappingsSaver.java
to allow implementations of MappingsSaver to be more efficient when persisting stubs.
=> import stubs in bulk where possible.

src/test/java/com/github/tomakehurst/wiremock/AcceptanceTestBase.java, src/test/java/com/github/tomakehurst/wiremock/AdminApiTest.java, src/test/java/com/github/tomakehurst/wiremock/RemoveStubMappingsAcceptanceTest.java, src/test/java/com/github/tomakehurst/wiremock/admin/tasks/RemoveMatchingStubMappingTaskTest.java, src/test/java/com/github/tomakehurst/wiremock/admin/tasks/RemoveUnmatchedStubMappingsTaskTest.java, src/test/java/com/github/tomakehurst/wiremock/stubbing/RemoveStubMappingsByMetadataPersistenceTest.java, src/test/java/com/github/tomakehurst/wiremock/stubbing/RemoveStubMappingsTest.java, src/test/java/com/github/tomakehurst/wiremock/stubbing/RemoveStubsPersistenceTest.java, wiremock-common/src/main/java/com/github/tomakehurst/wiremock/WireMockServer.java, wiremock-common/src/main/java/com/github/tomakehurst/wiremock/admin/tasks/RemoveMatchingStubMappingTask.java, wiremock-common/src/main/java/com/github/tomakehurst/wiremock/admin/tasks/RemoveUnmatchedStubMappingsTask.java, wiremock-common/src/main/java/com/github/tomakehurst/wiremock/client/HttpAdminClient.java, wiremock-common/src/main/java/com/github/tomakehurst/wiremock/client/WireMock.java, wiremock-common/src/main/java/com/github/tomakehurst/wiremock/core/Admin.java, wiremock-common/src/main/java/com/github/tomakehurst/wiremock/core/MappingsSaver.java, wiremock-common/src/main/java/com/github/tomakehurst/wiremock/core/WireMockApp.java, wiremock-common/src/main/java/com/github/tomakehurst/wiremock/junit/DslWrapper.java, wiremock-common/src/main/java/com/github/tomakehurst/wiremock/stubbing/StubMappingCollection.java
to allow implementations of MappingsSaver to be more efficient when persisting stubs.
this change necessitated adding the ability to delete stubs in bulk via the admin api, so RemoveMatchingStubMappingTask was updated to accept multiple stubs as well as a single stub mapping.
https://github.com/wiremock/wiremock/pull/3075
=> remove stubs in bulk where possible.

src/test/java/com/github/tomakehurst/wiremock/NetworkTrafficListenerAcceptanceTest.java, src/test/java/com/github/tomakehurst/wiremock/ProxyAcceptanceTest.java, src/test/java/com/github/tomakehurst/wiremock/http/HttpClientFactoryCertificateVerificationTest.java, src/test/java/com/github/tomakehurst/wiremock/http/ProxyResponseRendererTest.java, wiremock-common/src/main/java/com/github/tomakehurst/wiremock/http/HttpClientFactory.java, wiremock-common/src/main/java/com/github/tomakehurst/wiremock/http/client/ApacheHttpClientFactory.java
Set the default user-agent header sent by the proxy HTTP client to 'WireMock <version>' and added the ability to override it in the factory method.
=> More sensible default proxy user-agent and ability to override

src/test/java/com/github/tomakehurst/wiremock/archunit/JUnit4DetectionTest.java, wiremock-common/src/main/java/com/github/tomakehurst/wiremock/junit/WireMockStaticRule.java
=> WireMockStaticRule Deprecated(forRemoval = true)

src/main/java/com/github/tomakehurst/wiremock/standalone/CommandLineOptions.java, src/test/java/com/github/tomakehurst/wiremock/standalone/CommandLineOptionsTest.java
=> Fix global timeout CLI option
