.travis.yml, README.md, build.gradle
This pull request should be everything you need to address issue #186. All you should have to do is log into Travis-CI, turn on builds for this project, and merge this pull request. The merge will trigger a build, and the status of the build should show up in the project's README.
Originally I tried including 1.6 JDKs but there is a 1.7-specific subclass of `RuntimeException`.
I hope I didn't miss anything. Feel free to give feedback!
=> Added Travis-CI configuration file

docs/source/junit-rule.rst, docs/source/proxying.rst, docs/source/record-playback.rst
I fixed three typos in the Sphinx docs.
=> Some typos in Sphinx docs fixed.

docs/source/verifying.rst, src/main/java/com/github/tomakehurst/wiremock/WireMockServer.java, src/main/java/com/github/tomakehurst/wiremock/admin/AdminTasks.java, src/main/java/com/github/tomakehurst/wiremock/admin/ResetRequestsTask.java, src/main/java/com/github/tomakehurst/wiremock/client/HttpAdminClient.java, src/main/java/com/github/tomakehurst/wiremock/client/WireMock.java, src/main/java/com/github/tomakehurst/wiremock/core/Admin.java, src/main/java/com/github/tomakehurst/wiremock/core/WireMockApp.java, src/test/java/com/github/tomakehurst/wiremock/RequestQueryAcceptanceTest.java, src/test/java/com/github/tomakehurst/wiremock/stubbing/AdminRequestHandlerTest.java
Starting off with an easy one :)
=> Resetting requests

src/main/java/com/github/tomakehurst/wiremock/http/HttpHeader.java, src/test/java/com/github/tomakehurst/wiremock/http/HttpHeaderTest.java
I've implemented equals for HttpHeader as promised.
=> Implemented equals for HttpHeader

src/main/java/com/github/tomakehurst/wiremock/client/HttpAdminClient.java, src/test/java/com/github/tomakehurst/wiremock/client/HttpAdminClientTest.java
Resubmitting change on 2.0 beta branch as requested.
Added support for https for admin client.
Added builder to allow  selecting http or https scheme and custom http client.
=> Added https support and builder for HttpAdminClient

build.gradle, docs-v2/_docs/request-matching.md, src/test/java/com/github/tomakehurst/wiremock/matching/MatchesJsonPathPatternTest.java
Breaking change: $..book[(@.length-1)] doesn't work anymore
=> Bump JsonPath to 2.0.0 to 2.2.0

docs-v2/_docs/simulating-faults.md, docs-v2/_docs/stubbing.md
Fixes issue: https://github.com/tomakehurst/wiremock/issues/507
=> Documentation on how to customize default 404 response for unmapped requests

docs-v2/_docs/getting-started.md
result.wasSuccessFul -> result.wasSuccessful
=> corrected a minor typo

src/main/java/com/github/tomakehurst/wiremock/matching/UrlPathPattern.java, src/test/java/com/github/tomakehurst/wiremock/StubbingAcceptanceTest.java
=> use URI.rawPath() for url path matching - issue #527

src/main/resources/raml/wiremock-admin-api.raml
Not tested, but looks OK to me. I cribbed the response stuff from other delete sections, let me know if any tweaks are required.
=> Suggested API doc change to fix #581

.gitignore, src/main/java/com/github/tomakehurst/wiremock/common/JettySettings.java, src/main/java/com/github/tomakehurst/wiremock/jetty9/JettyHttpServer.java, src/main/java/com/github/tomakehurst/wiremock/standalone/CommandLineOptions.java, src/test/java/com/github/tomakehurst/wiremock/common/JettySettingsTest.java, src/test/java/com/github/tomakehurst/wiremock/standalone/CommandLineOptionsTest.java
Allow configuration of Jetty's stop timeout to address #710
=> enable stopTimeout option for jetty

src/main/java/com/github/tomakehurst/wiremock/client/HttpAdminClient.java
Wasn't sure if you wanted tests for the constructors over in HttpAdminClientTest, so I left them out for now.
=> Restored HttpAdminClient with host head and no proxy settings

src/main/java/com/github/tomakehurst/wiremock/matching/EqualToJsonPattern.java, src/test/java/com/github/tomakehurst/wiremock/WireMockServerTests.java
=> Issue 691 - NullpointerException

Vagrantfile
update vagrantfile to something that can be used to build wiremock, fixes #357
=> redo vagrantfile to something that can be used to build wiremock

build.gradle, docs-v2/package.json
This should fix the npm related build errors I got on windows
=> Fix build on windows

src/main/java/com/github/tomakehurst/wiremock/common/AsynchronousResponseSettings.java, src/main/java/com/github/tomakehurst/wiremock/core/Options.java, src/main/java/com/github/tomakehurst/wiremock/core/WireMockConfiguration.java, src/main/java/com/github/tomakehurst/wiremock/global/GlobalSettings.java, src/main/java/com/github/tomakehurst/wiremock/http/Response.java, src/main/java/com/github/tomakehurst/wiremock/http/StubResponseRenderer.java, src/main/java/com/github/tomakehurst/wiremock/jetty9/JettyHttpServer.java, src/main/java/com/github/tomakehurst/wiremock/servlet/WarConfiguration.java, src/main/java/com/github/tomakehurst/wiremock/servlet/WireMockHandlerDispatchingServlet.java, src/main/java/com/github/tomakehurst/wiremock/standalone/CommandLineOptions.java, src/test/java/com/github/tomakehurst/wiremock/ResponseDelayAsynchronousAcceptanceTest.java, src/test/java/com/github/tomakehurst/wiremock/ResponseDelaySynchronousFailureAcceptanceTest.java, src/test/java/com/github/tomakehurst/wiremock/standalone/CommandLineOptionsTest.java
This one adds asynchronous servlet-api in Wiremock. I've assembled what I found here:
https://github.com/tomakehurst/wiremock/issues/786
... and here:
https://github.com/hmalewska/wiremock/pull/1
@tomakehurst could you have a look and tell what you think?
=> #786 - asynchronous wiremock

src/main/java/com/github/tomakehurst/wiremock/stubbing/StubMappingJsonRecorder.java, src/test/java/com/github/tomakehurst/wiremock/stubbing/StubMappingJsonRecorderTest.java, src/test/java/com/github/tomakehurst/wiremock/testsupport/MockRequestBuilder.java
Also fixed an incorrect import in MockRequestBuilder
=> Implemented recording of multipart requests

docs-v2/_docs/response-templating.md, src/main/java/com/github/tomakehurst/wiremock/extension/responsetemplating/ResponseTemplateTransformer.java, src/test/java/com/github/tomakehurst/wiremock/extension/responsetemplating/ResponseTemplateTransformerTest.java
Hello Wiremock team,
As I told you in issue #1003 I write some code to add by default _ConditionalHelpers_ to _ResponseTemplateTransformer_. I write also a test and some doc. I hope it helps!
=> Add ConditionalHelpers support

src/main/java/com/github/tomakehurst/wiremock/common/Urls.java, src/test/java/com/github/tomakehurst/wiremock/common/UrlsTest.java
Fixing issue https://github.com/tomakehurst/wiremock/issues/1014
=> Resolve scenario name conflict restricting to two node parts

src/main/java/com/github/tomakehurst/wiremock/common/ClasspathFileSource.java, src/test/java/com/github/tomakehurst/wiremock/common/ClasspathFileSourceTest.java
=> Informative error when ZipEntry not found #1039

docs-v2/_docs/request-matching.md
When i used wire mock whit these option i notice that the documentation was not completely correct.
I really like using wiremock!
=> Fixed some small documentation issues.

build.gradle
It would be awesome if we can get this change in the upcoming release :slightly_smiling_face: 
Resolves https://github.com/tomakehurst/wiremock/issues/1171
=> Upgrade Jackson to 2.9.10 (fixing multiple CVEs)

docs-v2/_docs/response-templating.md
Fixes issue: https://github.com/tomakehurst/wiremock/issues/1078
=> Fix custom helper documentation typo

docs-v2/_docs/running-standalone.md
Here is the documentation PR that you requested. Should be sufficient.
=> Added clarification for proxy authentication.

src/main/java/com/github/tomakehurst/wiremock/WireMockServer.java, src/main/java/com/github/tomakehurst/wiremock/junit/Stubbing.java, src/test/java/com/github/tomakehurst/wiremock/VerificationAcceptanceTest.java
resolves https://github.com/tomakehurst/wiremock/issues/1280
=> add verify with CountMatchingStrategy

build.gradle, java7/src/main/java/com/github/tomakehurst/wiremock/admin/tasks/GetCaCertTask.java, java8/src/main/java/com/github/tomakehurst/wiremock/admin/tasks/GetCaCertTask.java, java8/src/test/java/com/github/tomakehurst/wiremock/HttpsBrowserProxyAcceptanceTest.java, src/main/java/com/github/tomakehurst/wiremock/admin/AdminRoutes.java, src/main/java/com/github/tomakehurst/wiremock/admin/tasks/GetCaCertTask.java, src/main/java/com/github/tomakehurst/wiremock/standalone/CommandLineOptions.java, src/main/resources/assets/recorder/index.html, src/test/java/com/github/tomakehurst/wiremock/standalone/CommandLineOptionsTest.java
=> Allow downloading the generated CA certificate

java8/build.gradle, java8/src/main/java/com/github/tomakehurst/wiremock/http/ssl/CertificateAuthority.java
It's even more verboten than using sun.security
=> Don't use keytool

docs-v2/_docs/record-playback.md
fixing typo as requested in #1382
=> fixing typo as requested in #1382

docs-v2/external-resources/index.md
Update `.md` for external resources to include new NodeJS/TS based client wiremock-captain
=> update external resources docs

docs-v2/_docs/simulating-faults.md
=> Update simulating-faults.md - fixed typo

src/main/java/com/github/tomakehurst/wiremock/common/Json.java, src/test/java/com/github/tomakehurst/wiremock/MappingsAcceptanceTest.java, src/test/resources/test-file-root/mappings/testjsonmapping.json
prevent applying scientific notation and rounding to big numbers by ObjectMapper
=> #1612 prevent applying scientific notation and rounding to big numbers

docs-v2/_docs/https.md, docs-v2/_docs/running-standalone.md
=> Updates to HTTPS related docs

build.gradle, gradle/wrapper/gradle-wrapper.properties, wiremock-webhooks-extension/build.gradle
As a step towards JDK 17 test runs in #1633, we need to support Gradle
7.
<details>
Before:
```
wiremock-jre8-standalone/2.31.0-ORIG:
total 19412
drwxr-xr-x 2 jamie jamie     4096 Oct 28 15:30 .
drwxr-xr-x 4 jamie jamie     4096 Nov  2 08:55 ..
-rw-r--r-- 1 jamie jamie 15730305 Oct 28 15:30 wiremock-jre8-standalone-2.31.0-ORIG.jar
-rw-r--r-- 1 jamie jamie     1159 Oct 28 15:30 wiremock-jre8-standalone-2.31.0-ORIG.pom
-rw-r--r-- 1 jamie jamie  1569532 Oct 28 15:30 wiremock-jre8-standalone-2.31.0-ORIG-javadoc.jar
-rw-r--r-- 1 jamie jamie  1693185 Oct 28 15:30 wiremock-jre8-standalone-2.31.0-ORIG-sources.jar
-rw-r--r-- 1 jamie jamie   862635 Oct 28 15:30 wiremock-jre8-standalone-2.31.0-ORIG-tests.jar
wiremock-jre8/2.31.0-ORIG:
total 6016
drwxr-xr-x 2 jamie jamie    4096 Oct 28 15:30 . …
```
=> Upgrade to Gradle 7 + some Gradle config cleanup

src/main/java/com/github/tomakehurst/wiremock/http/ProxyResponseRenderer.java, src/test/java/com/github/tomakehurst/wiremock/http/ProxyResponseRendererTest.java
=> Don't create request entity when it was not present in original request

src/main/java/com/github/tomakehurst/wiremock/matching/MultipartValuePattern.java, src/test/java/com/github/tomakehurst/wiremock/matching/MultipartValuePatternTest.java
=> Added equals and hashCode methods to MultipartValuePattern

src/main/java/com/github/tomakehurst/wiremock/client/WireMock.java, src/main/java/com/github/tomakehurst/wiremock/matching/NegativeContainsPattern.java, src/main/java/com/github/tomakehurst/wiremock/matching/StringValuePatternJsonDeserializer.java, src/test/java/com/github/tomakehurst/wiremock/StubbingAcceptanceTest.java, src/test/java/com/github/tomakehurst/wiremock/matching/NegativeContainsPatternTest.java, src/test/java/com/github/tomakehurst/wiremock/matching/RequestPatternTest.java
Hi, found this issue https://github.com/wiremock/wiremock/issues/1881 as [good first issue](https://github.com/wiremock/wiremock/labels/good%20first%20issue) during [Hacktoberfest](https://hacktoberfest.com/).
=> Add NegativeContainsPattern (aka notContaining) (#1881)

build.gradle
=> Bumping Handlebars library version to 4.3.1, #1990

src/main/resources/swagger/wiremock-admin-api.json, src/main/resources/swagger/wiremock-admin-api.yaml
Hi, I have created a doc for #1497 .
If you have time, could you please take a look at this PR. Thank you.
=> Add stub import doc

src/main/java/com/github/tomakehurst/wiremock/extension/responsetemplating/RequestLine.java, src/main/java/com/github/tomakehurst/wiremock/extension/responsetemplating/RequestTemplateModel.java, src/test/java/com/github/tomakehurst/wiremock/extension/responsetemplating/ResponseTemplateTransformerTest.java
=> [#2102] add requestIp to template model

README.md
Just a minor improvement for better navigation and for routing potential community members to Slack
=> Add community badges to the README

README.md
For https://github.com/wiremock/community/issues/25
=> Use HTTPs Slack redirect link

CONTRIBUTING.md, README.md
For https://github.com/wiremock/community/issues/7 and https://github.com/wiremock/community/issues/8. There is no production code changes
=> Update the WireMock Java contributor guide and README

build.gradle
There were two libraries whose dependency entries in build.gradle were duplicated. Both duplicates are removed.
None.
=> Remove duplicate dependencies

.github/release-drafter.yml, .github/workflows/changelog-draft,yml
=> Add changelog generation with Release Drafter

src/main/resources/swagger/schemas/request-pattern.yaml, src/main/resources/swagger/schemas/stub-mapping.yaml
- Added the `scheme`, `host`, `port`, `customMatcher` and `multipartPatterns` request-pattern properties to the JSON schema.
- Added the `serveEventListeners` property to the stub-mapping JSON schema. This was introduced in 3.0.0-beta-11.
None.
=> Add mising schema properties

.github/release-drafter.yml
=> Update the release drafter config for beta versioning

src/main/java/com/github/tomakehurst/wiremock/verification/diff/Diff.java, src/test/java/com/github/tomakehurst/wiremock/verification/diff/DiffTest.java
Reverts wiremock/wiremock#2336
Accidentally merged
=> Revert "Stop returning 500s for unmatched path patterns"

.github/release-drafter.yml
=> Revert Release Drafter to semver after the 3.0.0 release

build.gradle, wiremock-webhooks-extension/build.gradle
Fixes #2342.
Shadow JAR now always built last.
=> Ensure that the shadow JAR is always built last

src/main/java/com/github/tomakehurst/wiremock/common/NetworkAddressRange.java
Also add some defensive validation.
- TODO
=> Add working equals & readable toString to NetworkAddressRange

src/main/java/com/github/tomakehurst/wiremock/core/WireMockConfiguration.java, src/test/java/com/github/tomakehurst/wiremock/core/WireMockConfigurationTest.java
=> Added a setter for max template cache entries in WireMockConfiguration

src/main/java/com/github/tomakehurst/wiremock/common/filemaker/FilenameMaker.java, src/main/java/com/github/tomakehurst/wiremock/standalone/CommandLineOptions.java, src/test/java/com/github/tomakehurst/wiremock/StandaloneAcceptanceTest.java
=> Fix standalone missing filename extension bug

README.md
=> Fix MD links

src/main/java/com/github/tomakehurst/wiremock/WireMockServer.java, src/main/java/com/github/tomakehurst/wiremock/core/WireMockApp.java, src/main/java/com/github/tomakehurst/wiremock/http/HttpServerFactory.java, src/main/java/com/github/tomakehurst/wiremock/jetty/JettyHttpServer.java, src/test/java/com/github/tomakehurst/wiremock/WireMockServerTests.java
- Added template methods in JettyHttpServer to allow decoration of the context by subclasses
- Made HttpServerFactory an extension point
=> http server factory extension point

src/main/java/com/github/tomakehurst/wiremock/core/WireMockApp.java, src/main/java/com/github/tomakehurst/wiremock/extension/MappingsLoaderExtension.java, src/test/java/com/github/tomakehurst/wiremock/extension/mappingssource/DummyMappingsLoaderExtension.java, src/test/java/com/github/tomakehurst/wiremock/extension/mappingssource/MappingsLoaderExtensionTest.java, src/test/resources/extension-test-request/200-example.json
Exposing MappingsSource for extension point
https://github.com/wiremock/wiremock/issues/2331
- [ x] Recommended: Join [WireMock Slack](https://slack.wiremock.org/) to get any help in `#help-contributing` or a project-specific channel like `#wiremock-java`
- [ x] The PR request is well described and justified, including the body and the references
- [ x] The PR title represents the desired changelog entry
- [ x] The repository's code style is followed (see the contributing guide)
- [ x] Test coverage that demonstrates that the change works as expected
- [ x] For new features, there's necessary documentation in this pull request or in a subsequent PR to [wiremock.org](https://github.com/wiremock/wiremock.org)
Documentation PR - https://github.com/wiremock/wiremock.org/pull/149
=> Exposing MappingsSource for extension point

src/main/java/com/github/tomakehurst/wiremock/http/multipart/FileUpload.java, src/main/java/com/github/tomakehurst/wiremock/standalone/CommandLineOptions.java, src/test/java/com/github/tomakehurst/wiremock/http/ProxyResponseRendererTest.java
Removes unnecessary unboxing, and simplified one conditional.
=> feat: remove unnecessary unboxing

src/main/java/com/github/tomakehurst/wiremock/http/NetworkAddressRulesAdheringDnsResolver.java, src/test/java/com/github/tomakehurst/wiremock/http/NetworkAddressRulesAdheringDnsResolverTest.java
=> Ignore IPv6 addresses when checking network security rules

src/main/java/com/github/tomakehurst/wiremock/store/files/FileSourceBlobStore.java, src/test/java/com/github/tomakehurst/wiremock/store/files/FileSourceBlobStoreTest.java
Greetings, please look at my PR for #2420
=> Fix contract for FileSourceBlobStore 

src/test/java/com/github/tomakehurst/wiremock/http/BodyTest.java
Just adding a few unit tests which will help in a future pull request : https://github.com/wiremock/wiremock/pull/2551.
NA
=> Adding a few unit tests for Body

src/main/java/com/github/tomakehurst/wiremock/common/xml/Xml.java
This is a backport of #2603 for version 2.x.
=> Disable XML External Entities (2.x backport)

build.gradle
junit:junit:4.13 -> junit:junit:4.13.2
logback-classic:1.4.0 -> logback-classic:1.4.14
=> Mini update dependencies

build.gradle, src/test/java/com/github/tomakehurst/wiremock/WireMockClientWithProxyAcceptanceTest.java, src/test/java/com/github/tomakehurst/wiremock/client/WireMockClientWithProxyAcceptanceTest.java
Replace net.jockx:littleproxy by JDK
=> Replace net.jockx:littleproxy by JDK

src/main/java/com/github/tomakehurst/wiremock/WireMockServer.java, src/main/java/com/github/tomakehurst/wiremock/client/WireMock.java, src/main/java/com/github/tomakehurst/wiremock/junit/DslWrapper.java, src/main/java/com/github/tomakehurst/wiremock/junit/Stubbing.java, src/test/java/com/github/tomakehurst/wiremock/RemoveStubMappingAcceptanceTest.java
Each stubMapping can be removed by UUID
=> A Stubmapping can be removed by ID #2393

build.gradle
=> Remove dependencies

.idea/icon.svg
=> Add project icon for IntelliJ

.github/workflows/release.yml
AdoptOpenJDK is obsolete.  Use Temurin instead.
=> Use Temurin JDK

src/test/java/com/github/tomakehurst/wiremock/AdminApiTest.java, src/test/java/com/github/tomakehurst/wiremock/NearMissesAcceptanceTest.java, src/test/java/com/github/tomakehurst/wiremock/NearMissesRuleAcceptanceTest.java, src/test/java/com/github/tomakehurst/wiremock/NetworkTrafficListenerAcceptanceTest.java, src/test/java/com/github/tomakehurst/wiremock/StubbingAcceptanceTest.java, src/test/java/com/github/tomakehurst/wiremock/VerificationAcceptanceTest.java, src/test/java/com/github/tomakehurst/wiremock/matching/RequestPatternBuilderTest.java, src/test/java/com/github/tomakehurst/wiremock/matching/RequestPatternTest.java, src/test/java/com/github/tomakehurst/wiremock/verification/diff/DiffTest.java, src/test/java/com/github/tomakehurst/wiremock/verification/diff/PlainTextDiffRendererTest.java
Fix some Sonar or/and "IDEA inspect code" issues (partly)
=> Fix some Sonar or/and "IDEA inspect code" issues (partly)

src/main/java/com/github/tomakehurst/wiremock/client/HttpAdminClient.java, src/test/java/com/github/tomakehurst/wiremock/client/HttpAdminClientTest.java
WireMock.stubFor(..) should throw descriptive exception message on 404 error code from non-WireMock server instead of an unclear JsonException
- https://github.com/wiremock/wiremock/issues/2665
=> Fixes #2665 - WireMock.stubFor throws descriptive exception message on 404 error code from non-WireMock server instead of unclear JsonException

src/main/java/com/github/tomakehurst/wiremock/extension/responsetemplating/helpers/JoinHelper.java, src/main/java/com/github/tomakehurst/wiremock/extension/responsetemplating/helpers/WireMockHelpers.java, src/test/java/com/github/tomakehurst/wiremock/extension/responsetemplating/ResponseTemplateTransformerTest.java
Requested issue: https://github.com/wiremock/wiremock/issues/2710
=> Join - Handlebar helper

src/main/java/com/github/tomakehurst/wiremock/extension/responsetemplating/helpers/JoinHelper.java, src/main/java/com/github/tomakehurst/wiremock/extension/responsetemplating/helpers/WireMockHelpers.java, src/test/java/com/github/tomakehurst/wiremock/extension/responsetemplating/ResponseTemplateTransformerTest.java
=> Join handlerbars helper upgrade

src/test/java/com/github/tomakehurst/wiremock/extension/responsetemplating/ResponseTemplateTransformerTest.java
=> Fix test now that the new join helper has changed its name

.github/workflows/publish-snapshot.yml, build.gradle
Allows depending on pre-release WireMock versions
=> Publish snapshots on merge to master

src/test/scala/com/github/tomakehurst/wiremock/WireMockScalaAcceptanceTest.scala
=> Fix scala warnings

src/main/resources/swagger/schemas/absent-pattern.yaml, src/main/resources/swagger/schemas/after-pattern.yaml, src/main/resources/swagger/schemas/and-pattern.yaml, src/main/resources/swagger/schemas/before-pattern.yaml, src/main/resources/swagger/schemas/binary-equal-to-pattern.yaml, src/main/resources/swagger/schemas/contains-pattern.yaml, src/main/resources/swagger/schemas/content-pattern.yaml, src/main/resources/swagger/schemas/date-time-elements.yaml, src/main/resources/swagger/schemas/does-not-contain-pattern.yaml, src/main/resources/swagger/schemas/does-not-match-pattern.yaml, src/main/resources/swagger/schemas/equal-to-date-time-pattern.yaml, src/main/resources/swagger/schemas/equal-to-json-pattern.yaml, src/main/resources/swagger/schemas/equal-to-pattern.yaml, src/main/resources/swagger/schemas/equal-to-xml-pattern.yaml, src/main/resources/swagger/schemas/matches-json-path-pattern.yaml, src/main/resources/swagger/schemas/matches-json-schema-pattern.yaml, src/main/resources/swagger/schemas/matches-pattern.yaml, src/main/resources/swagger/schemas/matches-xpath-pattern.yaml, src/main/resources/swagger/schemas/not-pattern.yaml, src/main/resources/swagger/schemas/or-pattern.yaml, src/test/java/com/github/tomakehurst/wiremock/ContentPatternsJsonValidityTest.java, src/testFixtures/java/com/github/tomakehurst/wiremock/testsupport/TestFiles.java
Update and fix the matcher JSON schemas and add tests for each.
=> Updated and corrected JSON schemas for matcher in the OpenAPI spec

.github/workflows/build-and-test.yml
https://github.blog/changelog/2024-02-13-deprecation-notice-v1-and-v2-of-the-artifact-actions/
- TODO
=> Update the now deprecated upload-artifact action

src/main/java/com/github/tomakehurst/wiremock/extension/responsetemplating/helpers/RenderableDate.java, src/test/java/com/github/tomakehurst/wiremock/extension/responsetemplating/helpers/RenderableDateTest.java
=> write RenderableDate to JSON correctly.

README.md
Fix typo on Flaky word in README file
- TODO
=> Fix typo on Flaky in README file

.github/workflows/publish-snapshot.yml
* remove inputs.versionName. just use the branch name.
=> fix: publishing branch snapshots to github.
